(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[95838],{

/***/ 467611:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(59401);__web_req__(392190);__web_req__(809943);__web_req__(190240);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var ws;var vs;var Ns;var Fs;var xs;var fs=__c.fs;var gs=__c.gs;var ea=__c.ea;var eBb,fBb,iBb,qs,kBb,qBb,rBb,tBb,uBb,vBb,wBb,xBb,ABb,BBb,mBb,lBb;__c.cBb=function(a){return`rgb(${Math.round(a.r)},${Math.round(a.g)},${Math.round(a.b)})`};__c.ks=function(a,b,c){a=a.M4(b);try{return c(a)}finally{a.destroy()}};__c.ls=function(a,b){return __c.ks(a,b,c=>c.fc())};__c.ms=function(a,b){console.warn("SheetPages, SheetElements, and SheetItems are currently not supported. Call site:",a);return b};
__c.dBb=function(a){return a.type==="group"&&!!a.Tq&&a.Tq.app.id.startsWith("w:")};eBb=function(a,b,c){a.ov=window.setTimeout(c,b)};__c.ns=function(a,b,c){a.jab(b);const {E4:d,content:e,placement:f,arrow:g,key:h,Vyd:k=0}=c;eBb(b,k,(0,__c.AAb)(()=>{b.open=!0;b.position=d;b.placement=f;b.content=e;b.arrow=g;b.key=h;typeof b.content!=="string"&&b.$1a.current&&b.$1a.current.update()}))};__c.os=function(a,b){a.jab(b);b.open=!1};
fBb=function*(a){let b=0;for(let c=1;c<a.length;c++){const d=a[c-1],e=a[c];(__c.VAb.has(d)||__c.VAb.has(e))&&d!==e&&(yield a.slice(b,c),b=c)}yield a.slice(b)};__c.gBb=function(a){const [b,c]=a.toString().split(/[eE]/);[,a]=b.match(RegExp("[0-9]*\\.([0-9]*)"))||[];return Math.min(5,Math.max(0,((a===null||a===void 0?void 0:a.length)||0)-(parseInt(c,10)||0)))};
__c.ps=function([a,b],c){if(b.nF){var d=b.nF;d=__c.WAb.has(d)?d:void 0}else d=void 0;b=b.ct==null||b.ct===d?__c.hBb(d):b.ct;return[{...a,decimal:c>0?{length:0,padding:Math.min(5,c)}:void 0,minimumIntegerDigits:c>0?Math.max(a.minimumIntegerDigits,1):a.minimumIntegerDigits},{nF:d,ct:b}]};
iBb=function(a){const b=a.tXa,c=a.enter,d=a.update,e=a.exit;a=a.Es;return{tXa:b&&__c.go(b,f=>({...__c.ZAb,...f})),enter:__c.go(c,f=>({...__c.ZAb,...f})),update:__c.go(d,f=>({...__c.ZAb,...f})),exit:__c.go(e,f=>({...__c.ZAb,...f})),Es:a}};__c.jBb=function({children:a,getPosition:b}){const c=(0,__c.NAb)(null);(0,__c.LAb)(()=>(0,__c.BAb)(()=>{const {top:d,left:e}=b(),f=c.current;f===null||f===void 0||f.setAttribute("transform",`translate(${e}, ${d})`)}),[b]);return(0,__c.hs)("g",{ref:c,children:a})};
qs=function(a){return Object.freeze(a)};
kBb=function(a){switch(a.type){case "GROUPED_COLUMN":case "GROUPED_ROW":return{spacing:a.spacing,Hb:a.Hb,Ie:{...a.Ie,alignment:{...a.Ie.alignment}}};case "STACKED_ROW":case "STACKED_COLUMN":return{spacing:a.spacing,Hb:a.Hb,Ie:{...a.Ie,alignment:{...a.Ie.alignment}},qy:{...a.qy,alignment:{...a.Ie.alignment}}};case "PIE":case "DONUT":break;case "LINE":return{Ck:a.Ck,Jj:a.Jj};case "STACKED_AREA":break;case "SCATTERPLOT":case "BUBBLEPLOT":case "DOTPLOT":case "GROUPED_DOTPLOT":return{xL:a.xL,Jj:a.Jj};
case "PACKED_CIRCLES":break;case "TREEMAP":break;case "HISTOGRAM":return{Hb:a.Hb};case "RADAR":return{Ck:a.Ck,Gxa:a.Gxa};case "FUNNEL":break;case "BAR_RACE":return{spacing:a.spacing,Rza:a.Rza};case "PROGRESS":case "PICTOGRAM":break;case "POPULATION_PYRAMID":case "DUMBBELL":case "LOLLIPOP":case "SUNBURST":case "TIME_SERIES":break;default:throw new __c.r(a);}};
__c.nBb=function(a,b,{fireImmediately:c=!0}={}){return(d,e)=>lBb(()=>({I9b:a.jA,E5:d()}),({I9b:f,E5:g})=>{b===f&&e(g)},{fireImmediately:c,equals:(f,g)=>f.I9b===g.I9b&&mBb.shallow(f.E5,g.E5)})};__c.oBb=function(a,b){return __c.Gr.create(__c.Gr.Yg().attrs({"font-size":a.fontSize,"font-weight":a.fontWeight,"font-style":a.fontStyle,"font-family":a.hS}).uf(`${b}\n`).build())};__c.pBb=function(a,b){return{key:a,Hqd:0,type:"string",QBa:b,$pc:0}};
__c.fr.prototype.M4=ea(162,function(a){this.computed||(this.computed=new __c.er(this,a));this.c8b++;return new __c.dr(this.computed,()=>{__c.la(this.c8b>0);--this.c8b||(this.computed=void 0)})});__c.dr.prototype.IV=ea(146,function(...a){return __c.m(this.$l).IV(...a)});__c.er.prototype.IV=ea(145,function(...a){return this.Xxa(void 0,...a)});__c.fr.prototype.IV=ea(144,function(...a){return this.Xxa(void 0,...a)});
__c.Jmb.prototype.aF=ea(131,function(a){return typeof a==="string"?a?new __c.yq([new __c.wq(a)],a.length,0,0):__c.zmb:new __c.yq([new __c.$o(a)],0,1,0)});__c.fnb.prototype.aF=ea(130,function(a,b){return this.Yg().range(a,b).build()});__c.Dsb.prototype.aF=ea(129,function(a=this.cells.pP(),b=this.attrs.pP(),c=(()=>{var d;return(d=this.ud)===null||d===void 0?void 0:d.pP})()){__c.ja(!this.ud===!c);typeof a==="string"&&(a=this.cells.aF(a));return new __c.br(a,b,c)});__c.Hsb.prototype.aF=ea(128,function(a){return this.domain.aF(a)});
__c.Ksb.prototype.aF=ea(127,function(a){return this.domain.aF(a)});__c.rs=class{jab(a){window.clearTimeout(a.ov)}};qBb=/^("[^"]*")?((?:[,.\-:/ ZTymdhs]|000)+)(am\/pm)?("[^"]*")?$/i;rBb=/"/g;
__c.sBb=a=>{const [,b,c,d,e]=a.match(qBb)||[];if(c!=null){a=Array.from(fBb(c));d&&a.push("am/pm");var f=b?b.replace(rBb,""):void 0;const h=[];for(let k=0;k<a.length;k+=2){var g=a[k];const l=a[k+1];switch(g){case "ddd":case "dddd":h.push({kind:"weekday",format:g==="ddd"?"short":"long",separator:l});break;case "mmm":case "mmmm":h.push({kind:"month",format:g==="mmm"?"short":"long",separator:l});break;case "yy":case "yyyy":h.push({kind:"year",format:g==="yy"?"2-digit":"numeric",separator:l});break;case "d":case "dd":h.push({kind:"day",
format:g==="dd"?"2-digit":"numeric",separator:l});break;case "h":case "hh":h.push({kind:"hour",format:g==="hh"?"2-digit":"numeric",separator:l});break;case "m":case "mm":g=g==="mm"?"2-digit":"numeric";const n=h[h.length-1];n!=null&&n.kind==="hour"?h.push({kind:"minute",format:g,separator:l}):h.push({kind:"month",format:g,separator:l});break;case "s":case "ss":h.push({kind:"second",format:g==="ss"?"2-digit":"numeric",separator:l});break;case "000":h.push({kind:"millisecond",format:"3-digit",separator:l});
break;case "am/pm":h.push({kind:"ampm",separator:l});break;default:throw Error(`Invalid date component format '${g}'`);}}return{prefix:f,components:h,suffix:e?e.replace(rBb,""):void 0}}};__c.hBb=a=>{switch(a){case void 0:case ",":case "\u2019":return".";case ".":case "'":case " ":return",";default:throw new __c.r(a);}};tBb=/^([#0,]*)$/;uBb=/^([#0,.]+?)(,+)$/;vBb=/^([#0]+,?[#0]*)?(\.[0#]*)$/;wBb=/"/g;xBb=/0/g;
__c.ss=a=>{const [,b,c,d,e=a,f,g,h,k,l]=a.match(__c.YAb)||[];if(!c||!h)if(!d||!k){var n=c||h;if(!n||!g){var p=c?"prefix":h?"suffix":void 0;a=d||k;var [,q=e,u]=e.match(uBb)||[],w=q.match(tBb)||q.match(vBb);if(w!=null){var [,x,z]=w;n=p&&n?{position:p,symbol:n}:void 0;return{prefix:b?b.replace(wBb,""):void 0,suffix:l?l.replace(wBb,""):void 0,Xv:u!=null?u.length:0,locale:a,Cl:x?x.includes(","):!1,jCa:f!=null,decimal:z?{length:z.length-1,padding:(z.match(xBb)||[]).length}:void 0,minimumIntegerDigits:x?
(x.match(xBb)||[]).length:0,...(g!=null?{percent:!0}:{percent:!1,currency:n})}}}}};
__c.yBb=({prefix:a,suffix:b,Xv:c,percent:d,currency:e,locale:f,Cl:g,jCa:h,minimumIntegerDigits:k,decimal:l})=>{const n=[];a&&n.push(`"${a}"`);e!=null?e.position==="prefix"&&n.push(`[$${e.symbol}${f?`-${f}`:""}]`):f&&n.push(`[$-${f}]`);g&&n.push("#,##");k&&n.push("0".repeat(k));l&&(l.length>0||l.padding>0)&&(n.push("."),l.padding>0&&n.push("0".repeat(l.padding)),a=l.length-l.padding,a>0&&n.push("#".repeat(a)));n.length===0&&n.push("#");c&&n.push(",".repeat(c));h&&n.push("E+0");d&&n.push("%");(e===
null||e===void 0?void 0:e.position)==="suffix"&&n.push(`[$${e.symbol}${f?`-${f}`:""}]`);b&&n.push(`"${b}"`);return n.join("")};__c.zBb="yyyy-mm-ddThh:mm:ss.000Z;yyyy-mm-dd hh:mm:ss.000;yyyy-mm-dd hh:mm:ss;yyyy-mm-dd hh:mm;dd/mm/yy;dd/mm/yyyy;mm/dd/yy;mm/dd/yyyy;yyyy/mm/dd;dd-mm-yy;dd-mm-yyyy;mm-dd-yy;mm-dd-yyyy;dd.mm.yy;dd.mm.yyyy;yyyy-mm-dd;dd mmm yy;dd mmm yyyy;dd mmmm yy;dd mmmm yyyy;dd-mmm-yy;dd-mmm-yyyy;dd-mmmm-yy;dd-mmmm-yyyy;mm/yy;mm/yyyy;mmm yy;mmm yyyy;mmmm yy;mmmm yyyy;dd mmm;dd mmmm;mmm dd;mmmm dd;dd-mm;mm-dd;dd/mm;mm/dd;yyyy;mmmm;mmm;h:mm:ss am/pm;hh:mm am/pm;h am/pm;hh:mm;hh:mm:ss".split(";");
ABb=class{static F(a){__c.hb(a,{rPb:gs.ref,Kqd:fs,diff:fs})}subscribe(){return(0,__c.CAb)(()=>this.data.get(),()=>this.flush(),{fireImmediately:!0})}flush(){const a=this.$_c;this.$_c=this.data.get();a&&(this.rPb=a)}clear(){this.rPb=[];this.$_c=void 0}get Kqd(){const a=new Map;for(const b of this.rPb){const c=this.getKey(b);a.set(c,b)}return a}get diff(){const a=this.Kqd,b=this.getKey;var c=this.data.get();const d=new Map(a),e=new Map,f=new Map;for(const g of c)c=b(g),a.get(c)?(a.delete(c),f.set(c,
g)):e.set(c,g);return{enter:e,update:f,exit:a,prev:d}}constructor(a,b){this.data=a;this.getKey=b;this.rPb=(ABb.F(this),[])}};
__c.ts=class{static F(a){__c.hb(a,{c2b:gs.deep,zq:gs.ref,$r:gs.ref,Aq:gs.ref,JCa:gs.ref,mb:gs.shallow,gJ:gs.shallow,aN:gs.shallow,fca:fs})}set $e(a){this.c2b=iBb(a)}get $e(){return this.c2b}get fca(){var a;const b=(a=this.la.tTa)===null||a===void 0?void 0:a.get();return b!=null&&b!==0}constructor({Nb:a,la:b,WB:c=fs(()=>!__c.ye()),data:d,$e:e,getKey:f,zq:g,$r:h,Aq:k,yG:l=g,fL:n=k}){this.Nb=(__c.ts.F(this),void 0);this.JCa=!0;this.mb=new Map;this.gJ=new Map;this.aN=new Map;this.Nb=a;this.la=b;this.WB=
c;this.data=d;this.KY=new ABb(d,f);this.getKey=f;this.c2b=iBb(e);this.zq=g;this.$r=h;this.Aq=k;this.yG=l;this.fL=n;const p=b.tTa;this.BZ=p!=null?fs(()=>{const q=p.get();q!==0&&(this.wCe=q<=0?q+1:q);var u;return(u=this.wCe)!==null&&u!==void 0?u:q}):void 0;this.Xv=fs(()=>b.Xv)}};__c.us=a=>{const b=({children:c})=>__c.hs(__c.jBb,{getPosition:a,children:c});b.displayName=a.name!=null?`PositionedLayout(${a.name})`:"PositionedLayout";return b};BBb=__webpack_require__(519427);mBb=BBb.comparer;
vs=__c.vs=BBb.computed;lBb=BBb.reaction;ws=__c.ws=__webpack_require__(443763).jsx;var CBb=__webpack_require__(875604).memo;__c.DBb=__webpack_require__(214645).Pi;var EBb=new Map,FBb=[];Object.freeze({rotation:0});Object.freeze({vg:50});__c.GBb=Object.freeze({mda:void 0,brightness:0,contrast:0,saturation:0,d0:0,D5a:50,blur:0,Cla:0,bEa:0,yna:0,lua:0,highlights:0,m9:0,w0:0,zxa:0});__c.HBb=Object.freeze({cF:void 0,Dg:EBb,filter:void 0,aa:0,altText:void 0});__c.IBb=Object.freeze({Dg:EBb,filter:void 0,tu:FBb,aa:0,trim:void 0,ksa:1,autoplay:!0,playbackRate:void 0,volume:1,altText:void 0});Object.freeze({type:"linear",rotation:0});
Object.freeze({type:"radial",center:Object.freeze({top:.5,left:.5})});xs=__c.xs=Object.freeze({dropTarget:void 0,color:void 0,image:void 0,video:void 0,gradient:void 0,aa:0,locked:!1,KB:!1,PM:void 0,Fp:void 0,flipX:!1,flipY:!1});__c.JBb=Object.freeze({weight:0,color:"#000000",fill:xs,Xo:FBb,Pt:!1});var LBb,MBb,NBb,OBb,ys,PBb,QBb,RBb,SBb,UBb,VBb,WBb,zs,XBb,YBb,ZBb,$Bb,As,aCb,Bs,bCb,cCb,dCb,eCb;__c.KBb=Object.freeze({id:void 0,label:"",Wc:void 0});LBb=Object.freeze({top:0,right:0,bottom:0,left:0});MBb=Object.freeze({padding:LBb,background:xs});NBb=Object.freeze({pf:[]});OBb=Object.freeze({fontSize:void 0,fontFamily:void 0,fontWeight:void 0,fontStyle:void 0,color:void 0,Xn:void 0,textAlign:void 0,lineHeight:void 0});ys=Object.freeze({text:"",kd:NBb,Ng:OBb});PBb=Object.freeze({prefix:ys,AE:ys,url:void 0});
QBb=Object.freeze({title:ys,subtitle:ys,source:PBb});RBb=Object.freeze({uA:QBb,Zk:void 0,Fp:void 0,style:MBb,H2:!1,tN:!1,qO:!1,q4:!1,mM:!1});Object.freeze({type:"single"});SBb=Object.freeze({type:"columns",Ka:new Map});__c.TBb=Object.freeze({type:"rows",Ka:new Map});Object.freeze({type:"groups",Ka:new Map});UBb=Object.freeze({Ve:void 0,vertical:void 0});VBb=Object.freeze({visible:!1,position:void 0,alignment:UBb,ya:void 0,Ng:OBb});WBb=Object.freeze({visible:!1,alignment:UBb,color:void 0,Ng:OBb});
zs=Object.freeze({ya:void 0,Hc:void 0,Ca:void 0});XBb=Object.freeze({type:"TARGET_TICKS",dla:void 0});YBb=Object.freeze({type:"NUMERIC_LINEAR",min:void 0,max:void 0,spacing:XBb});ZBb=Object.freeze({type:"NUMERIC_BIN"});$Bb=Object.freeze({type:"CATEGORICAL"});As=Object.freeze({scale:YBb,title:ys});aCb=Object.freeze({scale:ZBb,title:ys});Bs=Object.freeze({scale:$Bb,title:ys});bCb=Object.freeze({...zs,type:"GROUPED_COLUMN",zg:void 0,kh:[],Fo:void 0,Yb:void 0,Ie:VBb,spacing:.075,Ry:!1,vB:void 0,Hb:void 0});
cCb=Object.freeze({...zs,type:"STACKED_COLUMN",zg:void 0,kh:[],Fo:void 0,Yb:void 0,Ie:VBb,qy:WBb,spacing:.075,Ry:!1,vB:void 0,Hb:void 0,ap:"stacked"});dCb=Object.freeze({...zs,type:"GROUPED_ROW",zg:void 0,kh:[],Fo:void 0,Yb:void 0,Ie:VBb,spacing:.075,Ry:!1,vB:void 0,Hb:void 0});eCb=Object.freeze({type:"STACKED_ROW",zg:void 0,kh:[],Fo:void 0,Yb:void 0,Ie:VBb,qy:WBb,...zs,spacing:.075,Ry:!1,vB:void 0,Hb:void 0,ap:"stacked"});
__c.fCb=Object.freeze({...zs,type:"PIE",zg:void 0,kh:void 0,Yb:void 0,spacing:.075,vB:void 0,Hb:void 0});Object.freeze({...zs,type:"DONUT",zg:void 0,kh:void 0,Yb:void 0,spacing:.075,vB:void 0,Hb:void 0});
var gCb=Object.freeze({...zs,type:"LINE",zg:void 0,kh:[],Yb:void 0,Ry:!1,Ck:void 0,Jj:void 0,Bm:void 0,WP:!1}),hCb=Object.freeze({...zs,type:"STACKED_AREA",zg:void 0,kh:[],Yb:void 0,Ry:!1,Ck:void 0,Jj:void 0,Bm:void 0,WP:!1,ap:void 0}),iCb=Object.freeze({...zs,type:"SCATTERPLOT",Ry:!1,Jj:void 0,Bm:void 0,xL:0,zg:void 0,i5:void 0,j5:[],Fo:void 0,Yb:void 0}),jCb=Object.freeze({...zs,type:"BUBBLEPLOT",xL:0,zg:void 0,i5:void 0,j5:[],Ro:void 0,Fo:void 0,Yb:void 0}),kCb=Object.freeze({...zs,type:"DOTPLOT",
xL:0,zg:void 0,i5:void 0,j5:[],Ro:void 0,Fo:void 0,Yb:void 0,ap:void 0}),lCb=Object.freeze({...zs,type:"GROUPED_DOTPLOT",xL:0,zg:void 0,i5:void 0,j5:[],Ro:void 0,Fo:void 0,Iva:void 0});Object.freeze({...zs,type:"PACKED_CIRCLES",groupBy:[],Ro:[],YI:2});Object.freeze({...zs,type:"TREEMAP",groupBy:[],Ro:[],YI:2});
var mCb=Object.freeze({...zs,type:"BAR_RACE",zg:void 0,Fo:[],kh:[],Yb:void 0,spacing:0,Hb:0,autoplay:!1,playbackRate:1,loop:1}),nCb=Object.freeze({...zs,type:"HISTOGRAM",kh:void 0,spacing:.075,vB:void 0,Hb:void 0,hna:void 0}),oCb=Object.freeze({...zs,type:"RADAR",zg:void 0,kh:[],Yb:void 0}),pCb=Object.freeze({...zs,type:"FUNNEL",zg:void 0,kh:void 0,Yb:void 0,spacing:.075,vB:void 0,Hb:void 0,WP:!1});Object.freeze({type:"POPULATION_PYRAMID",Ry:!1,spacing:.075,vB:void 0,Hb:void 0});
Object.freeze({type:"DUMBBELL",Ry:!1,Ck:void 0,Jj:void 0,Bm:void 0});Object.freeze({type:"LOLLIPOP",Ry:!1,Ck:void 0,Jj:void 0,Bm:void 0});var qCb=Object.freeze({...zs,type:"SUNBURST",groupBy:[],Ro:[],YI:2,ILa:"auto"});Object.freeze({type:"TIME_SERIES",Ck:void 0,WP:!1});Object.freeze({type:"PROGRESS",SPb:1,endpoint:1,s5a:.1});Object.freeze({type:"PICTOGRAM",sjc:[],spacing:.05});Object.freeze({...bCb,Dc:Bs,oc:As});Object.freeze({...cCb,Dc:Bs,oc:As});Object.freeze({...dCb,Dc:As,oc:Bs});Object.freeze({...eCb,Dc:As,oc:Bs});Object.freeze({...gCb,Dc:Bs,oc:As});Object.freeze({...hCb,Dc:Bs,oc:As});Object.freeze({...iCb,Dc:As,oc:As,Jj:20,ya:SBb});Object.freeze({...jCb,Bm:1,Jj:24,xL:.3,Dc:As,oc:As,ya:SBb});Object.freeze({...kCb,Bm:1,Jj:24,xL:.3,TO:"Y",wW:As,vY:Bs,ya:SBb});Object.freeze({...lCb,Bm:1,Jj:24,xL:.3,Dc:Bs,oc:Bs,ya:SBb});
Object.freeze({...mCb,spacing:.075,Hb:.08,Rza:10,Dc:As,oc:Bs});Object.freeze({...nCb,Dc:aCb,oc:As});Object.freeze({...oCb,Ck:3,Gxa:.6});Object.freeze({...qCb,$Gd:1,Gba:.33});Object.freeze({...pCb,oc:Bs});Object.freeze({oY:new Map});Object.freeze({text:"",uaa:!1});__c.Cs=Object.freeze({pf:[]});var Ds=new Map,Es=[],BCb,HCb,ICb,JCb,KCb,RCb,SCb,UCb,YCb,fDb;qs({width:-1,height:-1,units:4});Fs=__c.Fs=qs({rotation:0,aa:0,ew:void 0,$c:void 0,fb:void 0,tu:Es,animation:void 0,wt:void 0,transition:void 0,link:void 0,locked:!1,WI:void 0,KB:!1,PM:void 0,altText:void 0,zfa:void 0,zl:Es,N8:Ds,l4:Ds,anchor:void 0,Av:Ds});qs({type:"sequenced",animation:1,Wo:void 0});__c.rCb=qs({Za:void 0,hb:void 0,vg:void 0,scale:void 0,Jh:void 0,direction:void 0,color:void 0,Ema:void 0});
qs({kWa:Es,oWa:Es,Haa:Es,easing:1,fb:void 0,ruc:!1});__c.Gs=qs({fb:void 0,mask:void 0});__c.Hs=qs({fb:void 0,mask:void 0,reverse:void 0});qs({rotate:void 0,apa:void 0,nsa:void 0,yua:void 0});__c.sCb=qs({Vab:!1,p5a:!1});qs({...Fs,type:"group",Ina:"space",Tq:void 0,Ay:Ds});__c.tCb=qs({zna:0,Nsa:0});__c.uCb=qs({...Fs,type:"grid"});__c.vCb=qs({fill:xs,stroke:void 0,Hb:Es});qs({...Fs,type:"table"});qs({direction:void 0,jB:0,cellPadding:0,borderStyle:qs({weight:1,color:"#ffffff",Xo:Es})});
qs({kd:__c.Cs,Fp:void 0});qs({});__c.wCb=qs({fill:xs,WK:qs({Nc:void 0,Fd:void 0,Kc:void 0,Td:void 0}),borderColor:qs({Nc:void 0,Fd:void 0,Kc:void 0,Td:void 0}),RU:qs({Nc:void 0,Fd:void 0,Kc:void 0,Td:void 0}),Ll:2});__c.xCb=qs({all:void 0,Nc:void 0,Td:void 0,Fd:void 0,Kc:void 0});__c.yCb=qs({all:void 0,Wma:void 0,Vma:void 0,Uma:void 0,Tma:void 0});__c.zCb=qs({all:void 0,Nc:void 0,Fd:void 0,Kc:void 0,Td:void 0});__c.ACb=qs({alignSelf:void 0,justifySelf:void 0,padding:__c.zCb});
BCb=qs({Hb:__c.yCb,fill:xs,border:__c.xCb});__c.CCb=qs({...BCb,type:"element"});__c.DCb=qs({...Fs,type:"layout",padding:__c.zCb,border:__c.xCb,Hb:__c.yCb,fill:xs,direction:1,Tq:void 0});qs({type:"canonical",Sb:Es});qs({type:"invalid"});qs({type:"number"});qs({type:"boolean"});qs({type:"formula"});qs({type:"plaintext"});__c.ECb=qs({type:"media"});qs({type:"mention"});qs({type:"embed"});__c.FCb=qs({type:"text2",kd:__c.Cs});__c.GCb=qs({type:"text3"});HCb=qs({type:"plain",format:"0"});
ICb=qs({type:"currency",format:"[$$-en-US]#,##0.00"});JCb=qs({type:"percentage",format:"0%"});KCb=qs({type:"date",format:"dd mmm yyyy"});qs({type:"plain_number",fk:HCb});__c.LCb=qs({type:"currency",fk:ICb});__c.MCb=qs({type:"percentage",fk:JCb});__c.NCb=qs({type:"date",fk:KCb});__c.OCb=qs({type:"mention"});qs({type:"select",fk:HCb});__c.PCb=qs({type:"embed"});__c.QCb=qs({content:void 0,Wc:void 0,zl:Es});qs({Qo:Ds,Po:Ds,Eo:Ds,Un:Ds,cells:__c.orb,attrs:__c.arb});RCb=qs({cwa:void 0,L3a:void 0});
SCb=qs({freeze:RCb});__c.Is=qs({Yk:Ds,m6:[],sN:!1,view:SCb});qs({...Fs,type:"sheet"});__c.TCb=qs({...Fs,...RBb,type:"chart"});UCb=qs({marker:void 0,anchor:void 0,position:void 0});qs({Zp:"ref",top:.5,left:.5,hsa:2});qs({...Fs,type:"line",start:UCb,end:UCb,color:void 0,fill:xs,geometry:void 0,Xo:Es,Pt:!1,og:Es});qs({type:"elbowed",HG:Es,Hb:24});qs({type:"curved"});qs({position:.5,orientation:2,Sn:2,Oz:void 0,Fp:void 0});__c.Js=qs({...Fs,type:"rect",stroke:void 0,Hb:Es});
__c.VCb=qs({...Fs,type:"shape",slice:void 0,og:Es,resizeMode:void 0,Fv:void 0});__c.WCb=qs({stroke:void 0,Hb:0});qs({Ve:void 0,vertical:void 0,source:void 0,Ts:void 0,Ss:void 0});__c.Ks=qs({...Fs,type:"text",kd:__c.Cs,mc:void 0,placeholder:void 0,writingMode:void 0,Ta:void 0,Mb:void 0,kZ:!1,tna:void 0,Oz:void 0,Fp:void 0});__c.XCb=qs({...Fs,type:"embed"});YCb=qs({tracks:Es});
qs({"font-weight":void 0,"font-style":void 0,color:void 0,decoration:void 0,strikethrough:void 0,"font-family":void 0,"font-size":void 0,"font-kerning":void 0,"font-feature-liga":void 0,"font-feature-clig":void 0,"font-feature-calt":void 0,"font-size-modifier":void 0,"vertical-align":void 0,leading:void 0,spacing:void 0,direction:void 0,tracking:void 0,"text-transform":void 0,"text-align":void 0,"head-indent":void 0,"list-marker":void 0,"list-level":void 0});qs({aa:0,rotation:0,locked:!1,mc:void 0});
__c.Ls=qs({$e:void 0,title:void 0,Dca:void 0,we:!1,locked:!1,WI:void 0,KB:!1,fb:void 0,audio:YCb,transition:void 0,anchor:void 0,Av:Ds});__c.Ms=qs({type:"fixed",...__c.Ls,animation:void 0,Wo:void 0,qx:Es,zl:Es,Yk:Ds,dimensions:void 0,template:void 0,background:qs({...xs,color:"#ffffff"}),elements:Es,sheet:void 0});__c.ZCb=qs({type:"concatenated-fixed",...__c.Ls,pages:Es,Yk:Ds,direction:"vertical"});qs({type:"reference"});qs({type:"inline"});qs({locked:!1});
__c.$Cb=qs({trim:void 0,loop:2,volume:1,$c:void 0,fb:void 0,Y1:void 0,Z1:void 0});Ns=__c.Ns=qs({display:void 0,width:"100%",minWidth:void 0,maxWidth:void 0,Sza:void 0,alignment:void 0,altText:void 0});qs({...Ns,type:"rect",stroke:void 0,Hb:Es});qs({...Ns,type:"shape",slice:void 0,resizeMode:void 0,Fv:void 0});qs({...Ns,type:"table",Ta:void 0});qs({...Ns,type:"sheet"});var aDb=qs({wk:void 0});qs({...Ns,type:"page-break",width:"100cqw",marker:aDb});
__c.bDb=qs({...Ns,type:"separator",stroke:Object.freeze({...__c.JBb,color:"#bfc3c8",weight:1})});qs({...Ns,type:"embed"});qs({...Ns,type:"pill",display:2});var cDb=qs({fontFamily:void 0,fontSize:void 0,fontWeight:void 0,fontStyle:void 0,color:void 0,Xn:void 0});qs({...Ns,...RBb,type:"chart",Ng:cDb});qs({...Ns,type:"design",height:void 0,stroke:void 0,ida:void 0,Hb:Es});qs({...BCb,type:"text"});
qs({...Ns,type:"layout",padding:qs({Nc:0,Fd:0}),Tq:void 0,border:__c.xCb,fill:xs,Ta:"100%",fHa:void 0,dHa:void 0,eHa:void 0,direction:1,Hb:__c.yCb});__c.dDb=qs({template:void 0,Kp:aDb});__c.eDb=qs({type:"inline",We:void 0,le:void 0,pLb:void 0,MKb:void 0});qs({type:"reference"});fDb=qs({language:void 0,title:void 0,Yw:Ds,INa:void 0,rea:Ds});__c.gDb=qs({...fDb,Lm:"fixed",description:void 0,Ic:Es,HG:Es,audio:YCb,Za:void 0,hb:void 0,DVa:void 0,pages:Es});qs({...fDb,Lm:"responsive",rw:Es});
__c.Ps=qs({...__c.Ls,type:"responsive",Kp:aDb,Yk:Ds,template:void 0});__c.hDb=new Set("GROUPED_COLUMN STACKED_COLUMN GROUPED_ROW STACKED_ROW PIE DONUT LINE STACKED_AREA FUNNEL HISTOGRAM SCATTERPLOT BUBBLEPLOT DOTPLOT GROUPED_DOTPLOT BAR_RACE RADAR FUNNEL PACKED_CIRCLES TREEMAP".split(" "));__c.Qs=class{static F(a){__c.hb(a,{Qc:vs,mlc:vs,Qac:vs})}get base(){var a,b;return(b=(a=this.la.transition)===null||a===void 0?void 0:a.base)!==null&&b!==void 0?b:this._base}get uA(){return this.la.uA}get Fg(){var a,b;return(b=(a=this.la.transition)===null||a===void 0?void 0:a.Fg)!==null&&b!==void 0?b:this.G1b}get Qc(){var a;const b=(a=this.la.transition)===null||a===void 0?void 0:a.Fg.config.ref;if(b!=null&&this.llc(b))return b;a=this.Fg.config.ref;this.llc(a)&&(this.Jqd=a);return this.Jqd}get mlc(){return!this.llc(this.Fg.config.ref)}get ZU(){return this.Fg.id}get jA(){return this.Qc.type}get Qac(){return{Uj:this.Uj,
eq:this.eq,fontSize:this.fontSize,fontFamily:this.fontFamily,fontWeight:this.fontWeight,fontStyle:this.fontStyle,lI:this.lI,hX:this.hX,...kBb(this.Qc)}}get data(){return this.base.data}get Zk(){return this.base.Zk}get gga(){return this.base.gga}get w4a(){return!!this.Fg.qO}get hX(){return!this.Fg.tN}get RF(){return!this.Fg.H2}get mM(){return this.Fg.mM}get zoom(){return this.la.zoom}get width(){return this.la.width}get height(){return this.la.height}get rotation(){return this.la.rotation}get Hw(){return this.la.Hw}get fontSize(){return this.la.fontSize}get hS(){return this.la.hS}get fontFamily(){return this.la.fontFamily}get lI(){return this.la.lI}get fontStyle(){return this.la.fontStyle}get fontWeight(){return this.la.fontWeight}get Is(){return this.la.Is}get au(){return this.la.au}get On(){return this.la.On}get cUb(){return this.la.cUb}get Uka(){return this.la.Uka}get Uj(){return this.la.Uj}get eq(){return this.la.eq}get Ja(){return this.la.Ja}get padding(){return this.la.padding}get Ke(){return this.la.Ke}get Nz(){return this.la.Nz}get Vv(){return this.la.Vv}get Xv(){return this.la.Xv}get tTa(){return this.la.tTa}get KU(){return this.la.KU}get kJ(){return this.la.kJ}get Cma(){return this.la.Cma}get Ffa(){return this.la.Ffa}get bk(){return this.la.bk}constructor(a,
b,c,d,e){this.la=a;this._base=b;this.G1b=c;this.Jqd=d;this.llc=e;__c.Qs.F(this)}};__c.Qs.prototype.Zxa=__c.da(166);__c.Qs.prototype.NYa=__c.da(165);__c.iDb={};__c.iDb.Zua=__c.Qs;__c.iDb.NKf=__c.nBb;__c.Rs=Object.freeze({top:0,left:0,bottom:0,right:0});var jDb,kDb;jDb=__c.js("tspan",new Set(["y"]));kDb=CBb(({Tf:a,item:{lines:b,rotation:c},x:d,y:e,fontSize:f,lineHeight:g,opacity:h,textDecoration:k})=>{const l=vs(()=>c!=null?`translate(${d.get()},${e.get()}) rotate(${c})`:`translate(${d.get()},${e.get()})`);return ws(a,{transform:l,fontSize:f,opacity:h,textAnchor:"middle",dominantBaseline:"alphabetic",textDecoration:k,children:b.map((n,p)=>ws(jDb,{x:0,y:vs(()=>p*g.get()),children:n},p))})});
__c.lDb=CBb(a=>{const b=a.item.link;var c=a.Eg;return(c=b?c(b):void 0)?ws("a",{href:c.href,target:c.target,rel:c.rel,onClick:c.onClick,children:ws(kDb,{...a,textDecoration:"underline"})}):ws(kDb,{...a,textDecoration:b?"underline":"none"})});var nDb,mDb;
nDb=class{wwa(a,b){const c=a.AA(0);var d;var e={fontSize:(d=c["font-size"])!==null&&d!==void 0?d:__c.ir.Ui["font-size"],fontFamily:c["font-family"]||__c.ir.Ui["font-family"],fontWeight:c["font-weight"]||__c.ir.Ui["font-weight"],fontStyle:c["font-style"]||__c.ir.Ui["font-style"]};const {fontSize:f,fontFamily:g,fontWeight:h,fontStyle:k}=e;return`${a.jb.substring(0,a.charLength-1)}`+`.${f.toFixed(1)}`+`.${g}`+`.${__c.es(h)}`+`.${k}`+`.${b.toFixed(1)}`}mMa(a,b){return a.charLength===1||b===0?[]:this.cache.Xnc(a,
b)}constructor(a){this.sp=a;this.cache=new mDb((b,c)=>{if(b.charLength===1||c===0)var d=[];else{b=this.sp.obb(__c.ls(b,this.mv),1,"em-square");try{d=b.mMa(c)}finally{b.destroy()}}return d},(b,c)=>this.wwa(b,c));this.mv={styles:new Map,version:0}}};mDb=class{Xnc(a,b){const c=this.wwa(a,b),d=this.cache.get(c);if(d!=null)return d;a=this.mMa(a,b);this.cache.set(c,a);return a}constructor(a,b){this.mMa=a;this.wwa=b;this.cache=new Map}};__c.oDb={};__c.oDb.IId=nDb;__c.oDb.Vmg=__c.oBb;
}).call(self, self._5880d4398c473aa67256e87589eaef11);},

/***/ 582389:
(_, __, r) => r(467611)

}])
//# sourceMappingURL=sourcemaps/0ad7f92282d32649.js.map