(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[65446],{

/***/ 392190:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(59401);__web_req__(809943);__web_req__(868022);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var Xlb=__c.Xlb;var So=__c.So;var Gr;var rp=__c.rp;var sp=__c.sp;var tp=__c.tp;var pq=__c.pq;var cmb=__c.cmb;var Gq=__c.Gq;var lq=__c.lq;var mq=__c.mq;var kq=__c.kq;var nq=__c.nq;var jq=__c.jq;var bq=__c.bq;var Io=__c.Io;var No=__c.No;var lr;var Po=__c.Po;var Fq=__c.Fq;var kp=__c.kp;var oq=__c.oq;var Cq=__c.Cq;var hq=__c.hq;var Yp=__c.Yp;var $p=__c.$p;var Fo=__c.Fo;var Lo=__c.Lo;var Vo=__c.Vo;var qq=__c.qq;var Mo=__c.Mo;var Oo=__c.Oo;var gq=__c.gq;var Zp=__c.Zp;var To=__c.To;var Ho=__c.Ho;
var Eo=__c.Eo;var cq=__c.cq;var Go=__c.Go;var hb=__c.hb;var br;var m=__c.m;var da=__c.da;var Aq=__c.Aq;var la=__c.la;var cp=__c.cp;var mo=__c.mo;var ma=__c.ma;var ep=__c.ep;var Ro=__c.Ro;var r=__c.r;var ja=__c.ja;var Mrb,Nrb,Orb,Prb,Qrb,Trb,Urb,Vrb,Wrb,Xrb,Yrb,Zrb,$rb,asb,Sq,csb,hsb,Uq,Vq,Wq,Xq,nsb,ar,psb,qsb,ssb,tsb,vsb,wsb,ysb,cr,zsb,Asb,Bsb,Csb,Esb,bsb,Fsb,Gsb;Mrb=function(a,b){return a.Fi({values:b.values,Sb:b.Sb,attributes:b.attributes,computed:b.computed})};
Nrb=function(a){ja(!0);for(const b of a.Zx)switch(b.type){case 0:return b.state.startsWith("\n");case 2:break;case 1:return!1;default:throw new r(b);}return!1};Orb=function(a,b,c,d){const e=a.tqa("all");for(const f of Object.keys(b))a.KC(f)&&e(f)&&d(f,b[f],c[f])};__c.Qq=function(a,b,c){var d;return(d=b[c])!==null&&d!==void 0?d:a.attributes[c].defaultValue};__c.Rq=function(a,b){const c={...a.Ui};__c.op(a,b,"all",(d,e)=>d!=null&&(c[e]=d));return c};
Prb=function(a,b){const c={...a.UAb.as},d={...a.UAb.ss};Orb(a,b.as,b.ss,(e,f,g)=>{f!=null&&(c[e]=f);g!=null&&(d[e]=g)});return{as:c,ss:d}};Qrb=function(a,b){const c={};for(const d of b)c[d]=new Set;return new Proxy(c,{get:(d,e)=>d[e]||(a(e)?d[e]=new Set:void 0),ownKeys:()=>Object.keys(c)})};__c.Rrb=function(a){return Qrb(a.KC,a.jQa)};__c.Srb=function(a){return Qrb(a.KC,a.jQa)};Trb=function(a){return new __c.tq(typeof a==="function"?Ro(a):a)};
Urb=function(a,b,c){return c&&{ao:c.o,an:c.n,so:c.o!=null?a.nXa.encode(b,c.o):void 0,sn:c.n!=null?a.nXa.encode(b,c.n):void 0}};Vrb=function(a,b){const c={};for(const [d,e]of Object.entries(b))e&&(c[d]={r:Urb(a,d,e.r)});return c};Wrb=function(a,b,c,d){const e={};for(const f of __c.rjb(ep(c),ep(d)))c=a[f],d=b[f],c?d&&(ma(c.an,d.ao),ma(c.sn,d.so),c={ao:c.ao,so:c.so,an:d.an,sn:d.sn}):c=d,e[f]={r:c};return e};
Xrb=function(a,b,c,d){const e={},f={},g=__c.jo.vs();for(const h of __c.rjb(ep(c),ep(d))){c=a[h];d=b[h];c&&d?(ma(c.ao,d.ao),ma(c.so,d.so),c=__c.lo({ao:d.an,so:d.sn,an:c.an,sn:c.sn})):c=__c.ko(d,c);const {Fu:k,cv:l}=mo(g,c);f[h]={r:k};e[h]={r:l}}return g.build(f,e)};Yrb=function(a){const b={};__c.vjb(a,({r:c},d)=>b[d]={r:c&&{ao:c.an,so:c.sn,an:c.ao,sn:c.so}});return b};
Zrb=function(a,b,c,d,e){const f={};if(a.Prb.size){for(const g of a.Prb)f[g]={r:void 0},delete a.jFa[g],delete a.WSa[g];a.Prb.clear()}Object.keys(a.Srb).length&&(__c.fp(a.Srb,a.zVb,(g,h,k)=>{f[g]={r:{ao:d[g],so:e[g],an:h,sn:k}};a.jFa[g]=h;a.WSa[g]=k}),a.Srb={},a.zVb={});b&&c&&__c.fp(b,c,(g,h,k)=>{g in a.jFa&&(f[g]={r:{ao:h,so:k,an:a.jFa[g],sn:a.WSa[g]}})});return f};
$rb=function(a,b,c){const d=a.V1a;if(d){a.V1a=void 0;var e=new Set;__c.vjb(d,({r:f},g)=>{f?(a.mode==="apply"?(ma(c[g],f.so),a.c$.um(g,f.an,f.sn)):(ma(c[g],f.sn),a.c$.um(g,f.ao,f.so)),a.open.add(g),e.add(g)):(a.c$.um(g,b[g],c[g]),a.open.delete(g))});return e}};asb=function(a,b){const c=ep(a),d=ep(b),e=__c.rjb(c,d);return e.length===c.length&&e.length===d.length&&e.every(f=>a[f]===b[f])};Sq=function(a){return typeof a==="string"?a.length:1};
csb=function(a,b){const c=a.cells.cursor(a.length),d=new bsb;a=k=>{throw Error(String(k));};const e={...cp,jb:a},f={...cp,jb:()=>0,dk:a},g={...cp,jb:k=>d.retain(k.length),dk:()=>0},h={...cp,jb:k=>d.delete(k.length),dk:a};b.forEach({retain:(k,l)=>{d.change(l);c.VS(k,g)},insert:(k,l)=>{d.change(l);k.type!==2&&d.insert(k.state)},change:(k,l,n)=>{d.change(n);k.type===2?(c.VS(k.length,e),l.type!==2&&d.insert(l.state)):l.type===2?c.VS(k.length,h):(ja(k.state===l.state,"non-reflexive change: {} != {}",k,
l),c.VS(k.length,f),d.retain(k.length))}});return d.build()};__c.dsb=function(a,b){var c;const d=(c=a.Gzb.get(__c.Qq(a.wh,b,a.A4)))===null||c===void 0?void 0:c.as;return __c.Rq(a.wh,{...d,...b})};__c.esb=function(a,b,c){return(d,e)=>{const f=a.Gzb.get(c[a.A4]||e||a.wh.Ui[a.A4])||a.wh.UAb;e=__c.Pjb(a.wh,c,(g,h)=>g===f.as[h]?void 0:g);b.$Z(__c.qp(a.wh,e));b.retain(d);b.XO(e)}};__c.fsb=function(a,b){a.Er(a.domain.He(void 0,b))};
__c.gsb=function(a,b){const c=a.charLength;ja(a.isEmpty?b===0:0<=b&&b<c,"index out of bounds: {} \u2209 [{}, {})",b,0,c)};hsb=function(a,b){ja(!a.cells.sna||a.cells.jb().endsWith("\n"),"character stream must be empty or terminated with a \\n");a.forEach({...cp,jb:(c,d)=>b.gR(d),dk:(c,d)=>b.gR(d)})};__c.Tq=function(a){var b=isb.path;a=b(a);return!!a&&!a.s};Uq=function(a){return b=>{const c=a.exec(b);if(c)return{s:b.substring(c[0].length),value:c[0]}}};
Vq=function(a){return b=>{const c=[];for(;;){const d=a(b);if(!d)return{s:b,value:c};c.push(d.value);b=d.s}}};Wq=function(a,...b){return c=>{const d=[];for(const e of b){const f=e(c);if(!f)return;c=f.s;d.push(f.value)}return{s:c,value:a(...d)}}};Xq=function(a){return"A"<=a&&a<="Z"?"absolute":"relative"};
nsb=function(a){const b=a.jNc,c=a.nNc,d=a.KPc,e=a.rPc,f=a.MPc,g=a.DMc,h=a.JOc,k=a.nOc,l=a.YNc,n=a.cQc,p=a.mNc,q=a.JPc,u=a.qPc,w=a.LPc,x=a.CMc,z=a.fNc,B=a.dPc;var C=Wq((W,ba,ca)=>b(W,ca),Yq,Zq,Yq),E=Wq((W,ba)=>ba,Zq,C);a=Wq((W,ba,ca,na)=>h(Xq(W),ca,...na),Uq(/^[Mm]/),$q,C,Vq(E));const H=Wq((W,ba,ca,na)=>k(Xq(W),ca,...na),Uq(/^[Ll]/),$q,C,Vq(E)),I=Wq((W,ba,ca,na)=>l(Xq(W),ca,...na),Uq(/^[Hh]/),$q,Yq,Vq(jsb)),N=Wq((W,ba,ca,na)=>n(Xq(W),ca,...na),Uq(/^[Vv]/),$q,Yq,Vq(jsb));E=Wq((W,ba,ca,na,ka)=>c(W,ca,
ka),C,Zq,C,Zq,C);const M=Wq((W,ba,ca,na)=>p(Xq(W),ca,...na),Uq(/^[Cc]/),$q,E,Vq(Wq((W,ba)=>ba,Zq,E)));E=Wq((W,ba,ca)=>d(W,ca),C,Zq,C);const T=Wq((W,ba,ca,na)=>q(Xq(W),ca,...na),Uq(/^[Ss]/),$q,E,Vq(Wq((W,ba)=>ba,Zq,E)));E=Wq((W,ba,ca)=>e(W,ca),C,Zq,C);const U=Wq((W,ba,ca,na)=>u(Xq(W),ca,...na),Uq(/^[Qq]/),$q,E,Vq(Wq((W,ba)=>ba,Zq,E)));E=Wq(W=>f(W),C);const V=Wq((W,ba,ca,na)=>w(Xq(W),ca,...na),Uq(/^[Tt]/),$q,E,Vq(Wq((W,ba)=>ba,Zq,E)));C=Wq((W,ba,ca,na,ka,va,oa,pa,fa,ra,xa)=>g(W,ca,ka,oa,fa,xa),ksb,
Zq,ksb,Zq,Yq,lsb,msb,Zq,msb,Zq,C);const Y=Wq((W,ba,ca,na)=>x(Xq(W),ca,...na),Uq(/^[Aa]/),$q,C,Vq(Wq((W,ba)=>ba,Zq,C))),Z=Wq(W=>z(Xq(W)),Uq(/[Zz]/));return{moveTo:a,lineTo:H,N6f:I,QJg:N,ZLf:M,uBg:T,Vrg:U,vBg:V,arcTo:Y,closePath:Z,path:Wq(W=>B([].concat(...W)),Vq(Wq((W,ba)=>ba,$q,Wq((W,ba)=>[W,...ba],a,Vq(Wq((W,ba)=>ba,$q,W=>{if(W)switch(W[0].toUpperCase()){case "L":return H(W);case "H":return I(W);case "V":return N(W);case "C":return M(W);case "S":return T(W);case "Q":return U(W);case "T":return V(W);
case "A":return Y(W);case "Z":return Z(W)}}))))))}};ar=function(a){return(b,...c)=>{a:switch(b){case "absolute":b=0;break a;case "relative":b=1;break a;default:throw new r(b);}return new a(b,...c)}};__c.Nmb.prototype.Gka=__c.ea(138,function(a){la(!this.g2b);this.g2b=a});Aq.prototype.Gka=__c.ea(137,function(a){la(!this.i2b);this.i2b=a;this.domain.Gka(a.domain)});__c.ymb.prototype.CMa=__c.ea(123,function(){const a=__c.hjb(this.tjb),b=this.Cd.head;b&&b.type===2&&(this.Cd.Go(b.length),a&&a.dk&&a.dk(b.length))});
__c.yq.prototype.jJb=__c.ea(122,function(a){for(const b of this.Zx){const c=b.length;if(a<c)return b.gXb(a);a-=c}});psb=class extends __c.Ko{NP(){return!0}tx(a,b){return this.domain.zi(a,b)}stringify(a){return JSON.stringify(a)}constructor(){var a=__c.osb.domain;super(__c.osb.wta);this.domain=a}};
qsb=class{retain(a,b,c){if(b==null)return this.vs.retain(a),this;typeof b==="object"?this.vs.retain(a,Vrb(this,b)):this.vs.retain(a,b,Urb(this,b,c));return this}insert(a,b,c){if(b==null)return this.vs.insert(a),this;typeof b==="object"?this.vs.insert(a,Vrb(this,b)):this.vs.insert(a,b,Urb(this,b,c));return this}change(a,b){if(a==null)return this;typeof a==="object"?this.vs.change(Vrb(this,a)):this.vs.change(a,Urb(this,a,b));return this}build(){return this.vs.build()}constructor(a,b){this.vs=a;this.nXa=
b}};__c.rsb=class{encode(a,b){return b!=null?this.nXa.encode(a,b):void 0}retain(a){this.Vxa.retain(a);return this}insert(a){this.Vxa.insert(a);return this}open(a,b,c){this.Vxa.open(a,b,c!=null?c:this.encode(a,b));return this}close(a){this.Vxa.close(a);return this}$Z(a){this.Vxa.$Z(a,__c.go(a,(b,c)=>this.encode(c,b)));return this}XO(a){this.Vxa.XO(a);return this}build(){return this.Vxa.build()}constructor(a,b){this.Vxa=a;this.nXa=b}};__c.rsb.prototype.I9a=da(143);__c.rsb.prototype.Qya=da(125);
ssb=class{encode(a,b){return b!=null?this.nXa.encode(a,b):void 0}um(a,b){this.vs.um(a,b,this.encode(a,b));return this}attrs(a){this.vs.attrs(a,__c.go(a,(b,c)=>this.encode(c,b)));return this}Lc(a){this.vs.Lc(a);return this}append(a,b){this.vs.append(a,b);return this}build(){return this.vs.build()}constructor(a,b){this.vs=a;this.nXa=b}};
tsb=class{append(a,b){ja(b>=0,"{} < 0",b);if(!b)return this;var c=this.wVb;this.op&&this.op.type===a&&!ep(c).length?this.op={...this.op,length:this.op.length+b}:(this.op!=null&&this.ops.push(this.op),this.op={type:a,length:b,changes:c},this.wVb={});for(const [d,e]of Object.entries(c))(c=e&&e.r)?this.open[d]=c:delete this.open[d];switch(a){case 0:this.pre+=b;this.post+=b;break;case 1:this.post+=b;break;default:throw new r(a);}return this}change(a,b){if(a==null)return this;if(typeof a==="object")for(const [c,
d]of Object.entries(a))this.change(c,d&&d.r);else __c.ujb(this.open[a],b)?delete this.wVb[a]:this.wVb[a]={r:b};return this}retain(a,b,c){this.change(b,c);return this.append(0,a)}insert(a,b,c){this.change(b,c);return this.append(1,a)}build(){const a=this.op;a!=null&&(!Object.keys(this.open).length&&a.type===0&&[...Object.values(a.changes)].every(b=>!b||!b.r)?(this.pre-=a.length,this.post-=a.length):this.ops.push(a),this.op=void 0);return new __c.Vmb(this.ops,this.pre,this.post)}constructor(){this.ops=
[];this.open={};this.wVb={};this.post=this.pre=0}};
__c.usb=class{retain(a){this.right.move(a);return this}insert(a){const b=Zrb(this,{},{},this.right.wQ,this.right.Nja);this.c$.insert(a,b);return this}open(a,b,c){this.Prb.delete(a);a in this.WSa&&this.WSa[a]===c||(this.Srb[a]=b,this.zVb[a]=c);return this}close(a){delete this.Srb[a];delete this.zVb[a];a in this.jFa&&this.Prb.add(a);return this}$Z(a,b){__c.fp(a,b,(c,d,e)=>this.open(c,d,e));return this}XO(a){for(const b of ep(a))this.close(b);return this}build(){return this.c$.build()}constructor(a,b){this.c$=
new tsb;this.jFa={};this.WSa={};this.Prb=new Set;this.Srb={};this.zVb={};this.right=a.cursor(b,{cells:(c,d,e,f,g)=>this.c$.retain(c,Zrb(this,d,f,e,g))})}};__c.usb.prototype.I9a=da(142);__c.usb.prototype.Qya=da(124);
vsb=class{retain(a,b){ja(a>0);this.V1a=b;this.Cd.move(a);if(this.V1a)throw Error("ddas not consumed");return this}insert(a,b){ja(a>0);this.V1a=b;this.mode==="apply"?($rb(this,this.Cd.wQ,this.Cd.Nja),this.c$.Lc(a)):(this.iJc=!0,this.Cd.move(a),this.iJc=!1);if(this.V1a)throw Error("ddas not consumed");return this}result(){for(const a of this.open)this.c$.um(a,this.Cd.wQ[a],this.Cd.Nja[a]);this.open.clear();this.Cd.move(this.Cd.RB);this.Cd.finish();return this.c$.build()}constructor(a,b,c){this.mode=
a;this.c$=new __c.Smb;this.open=new Set;this.V1a=void 0;this.iJc=!1;this.Cd=b.cursor(c,{cells:(d,e,f,g,h)=>{const k=$rb(this,f,h);__c.fp(e,g,(l,n,p)=>{this.open.has(l)?ja(!(k===null||k===void 0||!k.has(l)),"unexpected gradient: {}: {}",l,p):this.c$.um(l,n,p)});this.iJc||this.c$.Lc(d)}})}};
wsb=class extends __c.Tp{Pg(a){const b=new tsb;return a?new qsb(b,a):b}q6(a,b,c){a=new __c.usb(a,b);return c?new __c.rsb(a,c):a}Yg(a){const b=new __c.Smb;return a?new ssb(b,a):b}pP(){return __c.Rmb}id(){return __c.Wmb}isIdentity(a){return a===__c.Wmb||!a.ops.length}compose(a,b){if(!a.ops.length)return b;if(!b.ops.length)return a;const c=this.Pg(),d=a.Cd(0,b.pre);a=b.Cd(a.post,0);b=d.next;for(var e=a.next;e;){if(e.type===1)b=e.length,e=a.pga(b),e=Wrb(d.cO,a.cO,{},e),c.insert(b,e);else if(b)if(b.type===
1){b=Math.min(b.length,e.length);e=d.pga(b);var f=a.lA(b);e=Wrb(d.cO,a.cO,e,f);c.insert(b,e)}else b=Math.min(b.length,e.length),e=d.lA(b),f=a.lA(b),e=Wrb(d.cO,a.cO,e,f),c.retain(b,e);else throw Error("length mismatch");b=d.next;e=a.next}d.finish();a.finish();return c.build()}transform(a,b){if(!a.ops.length||!b.ops.length)return __c.ko(b,a);var c=a.Cd(b.pre,0);const d=b.Cd(a.pre,0);var e=this.Pg();const f=this.Pg(),g=__c.jo.vs();for(var h=c.next,k=d.next;h||k;){if(h&&h.type===1){h=h.length;k=c.pga(h);
k=Xrb(c.cO,d.cO,k,{});const {Fu:l,cv:n}=mo(g,k);f.retain(h,l);e.insert(h,n)}else if(k&&k.type===1){h=k.length;k=d.pga(h);k=Xrb(c.cO,d.cO,{},k);const {Fu:l,cv:n}=mo(g,k);f.insert(h,l);e.retain(h,n)}else if(h&&k){h=Math.min(h.length,k.length);k=c.lA(h);const l=d.lA(h);k=Xrb(c.cO,d.cO,k,l);const {Fu:n,cv:p}=mo(g,k);f.retain(h,n);e.retain(h,p)}else throw Error(`unreachable case: ${h} x ${k}`);h=c.next;k=d.next}c.finish();d.finish();c=f.build();e=e.build();ma(c.post-c.pre,b.post-b.pre);ma(e.post-e.pre,
a.post-a.pre);return g.build(c,e)}Jl(a){if(!a.ops.length)return a;const b=this.Pg();for(const c of a.ops)switch(c.type){case 0:b.retain(c.length,Yrb(c.changes));break;case 1:b.retain(c.length,Yrb(c.changes));break;default:throw new r(c);}return b.build()}xk(a,b){return a.equals(b)}identity(){return __c.Wmb}apply(a,b){if(!b.ops.length)return a;a=new vsb("apply",a,b.pre);b.forEach(a);return a.result()}Vl(a,b){if(!b.ops.length)return a;a=new vsb("unapply",a,b.post);b.forEach(a);return a.result()}zi(a,
b){if(a===b)return!0;if(a.length!==b.length)return!1;a=a.Cd();b=b.Cd();let c=a.head,d=b.head;for(;c||d;){if(!c||!d)return!1;switch(c.type){case 1:if(d.type!==1||c.length!==d.length)return!1;a.Go(c.length);b.Go(d.length);break;case 0:if(d.type!==0||!asb(c.bI,d.bI))return!1;a.ww();b.ww();break;default:throw new r(c);}c=a.head;d=b.head}return!0}equals(a){return this===a||a instanceof wsb}};
__c.xsb=class{get prevValue(){return this.c.prevValue}get wQ(){return this.a.wQ}get Nja(){return this.a.Nja}VS(a,b){this.Yza=b;this.c.VS(a);this.Yza=void 0}ho(a,b){this.Yza=b;this.c.ho(a);this.Yza=void 0}CMa(){this.Yza=void 0;this.c.CMa();this.Yza=void 0}finish(){this.c.finish();this.a.finish()}constructor(a,b=0,c){b=Math.max(a.length,b);let d,e;this.a=a.attrs.cursor(b,{cells:(g,h,k,l,n)=>{var p=m(d);const q=p.length;ja(0<g&&g<=q);g<q?(p=p.TT(g),g=p[0],d=p[1]):(g=p,d=void 0);if(e)switch(g.type){case 0:e.jb&&
e.jb(g.state,h,k,l,n);break;case 1:e.item&&e.item(g.state,h,k,l,n);break;case 2:e.dk&&e.dk(g.state,h,k,l,n);break;default:throw new r(g);}}});const f=g=>{d=g;var h=this.Yza;e=h?c?{jb:__c.Xo(h.jb,c.jb),item:__c.Xo(h.item,c.item),dk:__c.Xo(h.dk,c.dk)}:h:c;this.a.move(g.length);la(d==null);e=void 0};this.c=a.cells.cursor(b,{jb:g=>f(new __c.wq(g)),item:g=>f(new __c.$o(g)),dk:g=>f(new __c.xq(g))})}};__c.xsb.prototype.CL=da(115);
br=__c.br=class{jJb(a){return this.cells.jJb(a)}cursor(a,b){return new __c.xsb(this,a,b)}forEach(a){this.cursor(0,a).VS(this.length)}RJ(a){return new br(this.cells.RJ(a),this.attrs,this.ud)}slice(a,b){var c;ja(0<=a&&a<=b,"invalid range: [{}, {})",a,b);if(0===a&&b>=this.length)return this;const d=this.cells.slice(a,b),e=this.attrs.slice(a,b),f=(c=this.ud)===null||c===void 0?void 0:c.slice(a,b);return new br(d,e,f)}toString(){return`${this.cells.toString()}|${this.attrs.toString()}`}constructor(a,b,
c){this.cells=a;this.attrs=b;this.ud=c;this.length=Math.max(a.length,b.length)}};
ysb=class{items(a){return this.uf(a)}uf(a){this.Z$.uf(a);this.MU.Lc(a.length);return this}item(a){this.Z$.item(a);this.MU.Lc(1);return this}M9(a){this.Z$.M9(a);this.MU.Lc(a);return this}um(a,b,c){this.MU.um(a,b,c);return this}attrs(a,b){this.MU.attrs(a,b);return this}append(a,b=0){this.Z$.append(a.cells,b);this.MU.append(a.attrs,b);return this}fpb(a){var b;(b=this.gpb)===null||b===void 0||b.Xe(a);return this}build(){var a;return new br(this.Z$.build(),this.MU.build(),(a=this.gpb)===null||a===void 0?
void 0:a.build())}constructor(a,b,c){this.Z$=a;this.MU=b;this.gpb=c}};
cr=class{forEach(a){const b=this.sR.Cd(this.pre,this.post);this.DR.forEach({retain:c=>{for(;c>0;){var d=m(b.next);switch(d.type){case 1:throw Error("op mismatch: retain|insert");case 0:d=Math.min(d.length,c);const e=b.lA(d);a.retain&&a.retain(d,e,b.cO);c-=d;break;default:throw new r(d);}}},update:c=>{var d=m(b.next);switch(d.type){case 1:throw Error("op mismatch: retain|insert");case 0:d=b.lA(1);a.update&&a.update(c,d,b.cO);break;default:throw new r(d);}},insert:c=>{for(;;){var d=m(b.next);switch(d.type){case 1:d=
Math.min(d.length,c.length);const e=b.pga(d);if(d===c.length){a.insert&&a.insert(c,e,b.cO);return}const [f,g]=c.TT(d);a.insert&&a.insert(f,e,b.cO);c=g;break;case 0:throw Error("op mismatch: insert|retain");default:throw new r(d);}}},change:(c,d)=>{for(;;){var e=m(b.next);switch(e.type){case 1:throw Error("op mismatch: change|insert");case 0:e=Math.min(e.length,c.length);const f=b.lA(e);if(e===c.length){a.change&&a.change(c,d,f,b.cO);return}const [g,h]=c.TT(e),[k,l]=d.TT(e);a.change&&a.change(g,k,
f,b.cO);c=h;d=l;break;default:throw new r(e);}}}},this.pre,this.post);b.finish()}RJ(a,b){return new cr(this.DR.RJ(a,b),this.sR,this.sd)}toString(){var a;return`${this.DR.toString()}|${this.sR.toString()}|${(a=this.sd)===null||a===void 0?void 0:a.toString()}}`}constructor(a,b,c){this.DR=a;this.sR=b;this.sd=c;this.pre=Math.max(this.DR.pre,this.sR.pre);this.post=Math.max(this.DR.post,this.sR.post)}};
zsb=class{Pya(a){var b;this.cells.Pya(a);this.attrs.insert(a.length,void 0);(b=this.ud)===null||b===void 0||b.insert(a.length);return this}retain(a,b){var c;this.cells.retain(a);this.attrs.retain(a,b);(c=this.ud)===null||c===void 0||c.retain(a);return this}update(a){var b;this.cells.update(a);this.attrs.retain(1);(b=this.ud)===null||b===void 0||b.retain(1);return this}expand(a){var b;this.cells.expand(a);this.attrs.insert(a);(b=this.ud)===null||b===void 0||b.insert(a);return this}insert(a,b){var c;
const d=Sq(a);this.cells.insert(a);this.attrs.insert(d,b);(c=this.ud)===null||c===void 0||c.insert(d);return this}Lsa(a){var b;this.cells.Lsa(a);this.attrs.retain(a);(b=this.ud)===null||b===void 0||b.retain(a);return this}i6a(a){var b;const c=Sq(a);this.cells.i6a(a);this.attrs.retain(c);(b=this.ud)===null||b===void 0||b.retain(c);return this}RY(a){var b;const c=Sq(a);this.cells.RY(a);this.attrs.retain(c);(b=this.ud)===null||b===void 0||b.retain(c);return this}replace(a,b){var c;const d=Sq(a);this.cells.change(a,
b);this.attrs.retain(d);(c=this.ud)===null||c===void 0||c.retain(d);return this}build(){var a;return new cr(this.cells.build(),this.attrs.build(),(a=this.ud)===null||a===void 0?void 0:a.build())}constructor(a,b,c){this.cells=a;this.attrs=b;this.ud=c}};
Asb=class{retain(a){var b;this.uf.retain(a);this.attrs.retain(a);(b=this.ud)===null||b===void 0||b.retain(a);return this}insert(a){var b;const c=typeof a==="string"?a.length:1;this.uf.insert(a);this.attrs.insert(c);(b=this.ud)===null||b===void 0||b.insert(c);return this}delete(a){var b;const c=typeof a==="string"?a.length:1;this.uf.RY(a);this.attrs.retain(c);(b=this.ud)===null||b===void 0||b.retain(c);return this}open(a,b,c){this.attrs.open(a,b,c);return this}update(a){var b;this.uf.update(a);this.attrs.retain(1);
(b=this.ud)===null||b===void 0||b.retain(1);return this}$Z(a){this.attrs.$Z(a);return this}close(a){this.attrs.close(a);return this}XO(a){this.attrs.XO(a);return this}build(){var a;return new cr(this.uf.build(),this.attrs.build(),(a=this.ud)===null||a===void 0?void 0:a.build())}constructor(a,b,c){this.uf=a;this.attrs=b;this.ud=c}};
Bsb=class{Pya(a){var b;const c=a.length;this.cells.Pya(a);this.attrs.insert(c,void 0);(b=this.ud)===null||b===void 0||b.insert(c);return this}retain(a,b){var c;this.cells.retain(a);this.attrs.retain(a,b);(c=this.ud)===null||c===void 0||c.retain(a);return this}update(a){var b;this.cells.update(a);this.attrs.retain(1);(b=this.ud)===null||b===void 0||b.retain(1);return this}expand(a){var b;this.cells.expand(a);this.attrs.insert(a);(b=this.ud)===null||b===void 0||b.insert(a);return this}insert(a,b){var c;
const d=Sq(a);this.cells.insert(a);this.attrs.insert(d,b);(c=this.ud)===null||c===void 0||c.insert(d);return this}Lsa(a){var b;this.cells.Lsa(a);this.attrs.retain(a);(b=this.ud)===null||b===void 0||b.retain(a);return this}i6a(a){var b;const c=Sq(a);this.cells.i6a(a);this.attrs.retain(c);(b=this.ud)===null||b===void 0||b.retain(c);return this}RY(a){var b;const c=Sq(a);this.cells.RY(a);this.attrs.retain(c);(b=this.ud)===null||b===void 0||b.retain(c);return this}replace(a,b){var c;const d=Sq(a);this.cells.change(a,
b);this.attrs.retain(d);(c=this.ud)===null||c===void 0||c.retain(d);return this}build(){var a;return new cr(this.cells.build(),this.attrs.build(),(a=this.ud)===null||a===void 0?void 0:a.build())}constructor(a,b,c){this.cells=a;this.attrs=b;this.ud=c}};
Csb=class{items(a){return this.uf(a)}uf(a){this.Z$.uf(a);this.MU.Lc(a.length);return this}item(a){this.Z$.item(a);this.MU.Lc(1);return this}M9(a){this.Z$.M9(a);this.MU.Lc(a);return this}um(a,b){this.MU.um(a,b);return this}attrs(a){this.MU.attrs(a);return this}append(a,b=0){this.Z$.append(a.cells,b);this.MU.append(a.attrs,b);return this}fpb(a){var b;(b=this.gpb)===null||b===void 0||b.Xe(a);return this}build(){var a;return new br(this.Z$.build(),this.MU.build(),(a=this.gpb)===null||a===void 0?void 0:
a.build())}constructor(a,b,c){this.Z$=a;this.MU=b;this.gpb=c}};
__c.Dsb=class extends __c.Tp{Pg(a){var b;const c=this.cells.Pg(),d=(b=this.ud)===null||b===void 0?void 0:b.Pg();return a?new Bsb(c,this.attrs.Pg(a),d):new zsb(c,this.attrs.Pg(),d)}q6(a,b){var c;return new Asb(this.cells.Pg(),this.attrs.q6(a.attrs,a.length,b),(c=this.ud)===null||c===void 0?void 0:c.Pg())}Yg(a){var b;const c=this.cells.Yg(),d=(b=this.ud)===null||b===void 0?void 0:b.Yg();return a?new Csb(c,this.attrs.Yg(a),d):new ysb(c,this.attrs.Yg(),d)}He(a=this.cells.id(),b=this.attrs.id(),c=(()=>
{var d;return(d=this.ud)===null||d===void 0?void 0:d.id()})()){ja(!this.ud===!c);return new cr(a,b,c)}FTa(a,b){return this.attrs.q6(a.attrs,a.length,b)}isIdentity(a){ja(!this.ud===!a.sd);return this.cells.isIdentity(a.DR)&&this.attrs.isIdentity(a.sR)&&(!this.ud||this.ud.isIdentity(a.sd))}compose(a,b){var c;ja(!this.ud===!a.sd);ja(!this.ud===!b.sd);return new cr(this.cells.compose(a.DR,b.DR),this.attrs.compose(a.sR,b.sR),(c=this.ud)===null||c===void 0?void 0:c.compose(a.sd,b.sd))}transform(a,b){var c;
ja(!this.ud===!a.sd);ja(!this.ud===!a.sd);const d=__c.jo.vs(),e=mo(d,this.cells.transform(a.DR,b.DR)),f=mo(d,this.attrs.transform(a.sR,b.sR)),g=mo(d,((c=this.ud)===null||c===void 0?void 0:c.transform(a.sd,b.sd))||__c.ko());return d.build(new cr(e.Fu,f.Fu,g.Fu),new cr(e.cv,f.cv,g.cv))}Jl(a){var b;ja(!this.ud===!a.sd);return new cr(this.cells.Jl(a.DR),this.attrs.Jl(a.sR),(b=this.ud)===null||b===void 0?void 0:b.Jl(a.sd))}xk(a,b){ja(!this.ud===!a.sd);ja(!this.ud===!b.sd);return this.cells.xk(a.DR,b.DR)&&
this.attrs.xk(a.sR,b.sR)&&(!this.ud||this.ud.xk(a.sd,b.sd))}identity(){return this.id}apply(a,b){var c;ja(!this.ud===!a.ud);ja(!this.ud===!b.sd);return new br(this.cells.apply(a.cells,b.DR),this.attrs.apply(a.attrs,b.sR),(c=this.ud)===null||c===void 0?void 0:c.apply(a.ud,b.sd))}Vl(a,b){var c;ja(!this.ud===!a.ud);ja(!this.ud===!b.sd);return new br(this.cells.Vl(a.cells,b.DR),this.attrs.Vl(a.attrs,b.sR),(c=this.ud)===null||c===void 0?void 0:c.Vl(a.ud,b.sd))}zi(a,b){if(a===b)return!0;ja(!this.ud===!a.ud);
ja(!this.ud===!b.ud);return this.cells.zi(a.cells,b.cells)&&this.attrs.zi(a.attrs,b.attrs)&&(!this.ud||this.ud.zi(a.ud,b.ud))}equals(a){return this===a?!0:a instanceof __c.Dsb?this.cells.equals(a.cells)&&this.attrs.equals(a.attrs)&&__c.Tp.equals(this.ud,a.ud):!1}constructor(a,b){super();this.ud=b;this.cells=new __c.Jmb(a);this.attrs=new wsb;this.id=this.He()}};__c.Dsb.prototype.aF=da(129);
Esb=class{forEach(a){const b=__c.bp.Pg();this.uf.forEach({retain:c=>b.retain(c),insert:c=>b.insert(c),delete:c=>b.Lsa(c)},this.pre,this.post);(new cr(b.build(),this.attrs)).forEach({retain:(c,d)=>a.retain&&a.retain(c,d),insert:(c,d)=>c.type!==2&&a.insert&&a.insert(c.state,d),change:(c,d,e)=>a.delete&&a.delete(c.length,e)})}constructor(a,b){this.uf=a;this.attrs=b;this.pre=Math.max(this.uf.pre,this.attrs.pre);this.post=Math.max(this.uf.post,this.attrs.post)}};
bsb=class{change(a){this.attrs.change(a);return this}retain(a,b){this.uf.retain(a);this.attrs.retain(a,b);return this}insert(a,b){this.uf.insert(a);this.attrs.insert(a.length,b);return this}delete(a,b){this.uf.delete(a);this.attrs.retain(a,b);return this}build(){return new Esb(this.uf.build(),this.attrs.build())}constructor(){this.uf=new __c.dp;this.attrs=new tsb}};
__c.dr=class{static F(a){hb(a,{isEmpty:Ro})}destroy(){m(this.$l).destroy();this.$l=void 0;this.Jca()}get charLength(){return m(this.$l).charLength}get jb(){return m(this.$l).jb}get isEmpty(){return m(this.$l).isEmpty}Xxa(a,...b){return m(this.$l).Xxa(a,...b)}AA(a){return m(this.$l).AA(a)}setAttribute(a,b,c){m(this.$l).setAttribute(a,b,c)}Sz(a,b){m(this.$l).Sz(a,b)}fc(){return m(this.$l).fc()}constructor(a,b){this.$l=a;this.Jca=b;__c.dr.F(this)}};__c.aa=__c.dr.prototype;__c.aa.pRa=da(161);
__c.aa.YJa=da(158);__c.aa.ZD=da(155);__c.aa.cya=da(152);__c.aa.Z6=da(149);__c.aa.IV=da(146);__c.aa.bP=da(135);
__c.er=class{static F(a){hb(a,{Gzb:Ro})}get charLength(){return this.specified.charLength}get jb(){return this.specified.jb}get isEmpty(){return this.specified.isEmpty}b6(a){return this.specified.b6(a)}Xxa(a){a=this.b6(a);const b=__c.Srb(this.wh),c=this.specified.state.cursor();c.ho(a.index);c.ho(a.length,{...cp,jb:(d,e,f)=>{d=__c.dsb(this,f);for(const g in d)b[g].add(d[g])}});return b}AA(a){return __c.dsb(this,this.specified.AA(a))}setAttribute(a,b,c){const d={};d[a]=b;this.Sz(d,c)}Sz(a,b){b=this.b6(b);
if(b.length!==0&&Object.keys(a).length!==0){var c=this.specified.state.cursor(),d=this.specified.FTa();c.ho(b.index,{...cp,jb:f=>d.retain(f.length),dk:f=>d.retain(f)});var e=__c.esb(this,d,a);c.ho(b.length,{...cp,jb:(f,g,h)=>e(f.length,h[this.A4]),dk:(f,g,h)=>e(f,h[this.A4])});__c.fsb(this.specified,d.build())}}fc(){let a=!0;const b=this.wh.Ui[this.A4];let c=b;const d=new Set,e=(g,h)=>{const k={},l={};var n=g[this.A4];n=this.A4 in g?n||b:c;const p=this.Gzb.get(n)||this.wh.UAb;if(a||c!==n)Orb(this.wh,
p.as,p.ss,(q,u,w)=>{d.has(q)||(k[q]=u,l[q]=w)}),a=!1,c=n;Orb(this.wh,g,h,(q,u,w)=>{u!=null?(k[q]=u,l[q]=w,d.add(q)):(k[q]=p.as[q],l[q]=p.ss[q],d.delete(q))});return{QYc:k,TYc:l}},f=this.specified.domain.Yg();this.specified.state.forEach({...cp,jb:(g,h,k,l)=>{const {QYc:n,TYc:p}=e(h,l);return f.attrs(n,p).uf(g)},dk:(g,h,k,l)=>{const {QYc:n,TYc:p}=e(h,l);return f.attrs(n,p)}});return f.build()}destroy(){}get Gzb(){return __c.Vg(this.mv.styles,a=>Prb(this.wh,a))}constructor(a,b){this.specified=a;this.mv=
b;this.wh=(__c.er.F(this),void 0);this.wh=a.wh;this.A4=a.A4}};__c.aa=__c.er.prototype;__c.aa.pRa=da(160);__c.aa.YJa=da(157);__c.aa.ZD=da(154);__c.aa.cya=da(151);__c.aa.Z6=da(148);__c.aa.IV=da(145);__c.aa.bP=da(134);
__c.fr=class extends __c.Wp{static F(a){hb(a,{charLength:Ro,jb:Ro,isEmpty:Ro,OTc:Ro})}b6(a){if(!a)return{index:0,length:this.charLength};const b=a.index,c=a.index+a.length,d=this.charLength;ja(b<=c,"invalid range: {}, {}",b,c);ja(0<=b&&c<=d,"range out of bounds: [{}, {}) \u2288 [{}, {})",b,c,0,d);return a}Xxa(a){a=this.b6(a);const b=__c.Rrb(this.wh);if(!a.length)return b;const c=this._state.get().cursor();c.ho(a.index);c.ho(a.length,{...cp,jb:(d,e,f)=>{this.wh.jQa.forEach(g=>b[g].add(f[g]))}});return b}AA(a){if(!this.charLength)return{};
__c.gsb(this,a);var b=[...this.wh.jQa];a=this.Xxa({index:a,length:1},...b);b={};for(const c in a){const d=a[c].values().next().value;d!=null&&(b[c]=d)}return b}get charLength(){return this._state.get().cells.sna}get jb(){return this._state.get().cells.jb()}get isEmpty(){const a=this.charLength;return a===0||a===1&&Nrb(this._state.get().cells)}get OTc(){const a=[];this._state.get().forEach({...cp,jb:(b,c,d)=>a.push({jb:b,attributes:{...d}})});return a}FTa(){const a=this._state.get();return this.domain.attrs.q6(a.attrs,
a.length,this.wh)}setAttribute(a,b,c){const d={};d[a]=b;this.Sz(d,c)}Sz(a,b){b=this.b6(b);if(b.length!==0&&Object.keys(a).length!==0){a=__c.qp(this.wh,a);var c=this._state.get(),d=this.FTa();c=c.cells.cursor(c.length,{...cp,jb:e=>d.retain(e.length),dk:e=>d.retain(e)});c.ho(b.index);c.CMa();d.$Z(a);c.ho(b.length);c.CMa();d.XO(a);__c.fsb(this,d.build())}}q6(){return this.domain.q6(this._state.get(),this.wh)}n0(a){const b=csb(this._state.get(),a);this._state.set(this.domain.apply(this._state.get(),a));
this.subject.next(b)}ROa(a){if(a.length){ja(a.every((e,f)=>{f=a[f+1];return e.length>0&&(f==null||e.index+e.length<=f.index)}));var b=this.q6(),c=0,d=this._state.get().cursor();for(const {index:e,length:f}of a){const g=e+f;d.ho(e-c,{...cp,jb:k=>b.retain(k.length),dk:k=>b.retain(k)});let h=!1;d.ho(f,{...cp,jb:(k,l,n)=>{h||(b.$Z(n),b.insert(void 0),b.XO(n),h=!0);b.delete(k)},dk:k=>b.retain(k)});c=g}this.Er(b.build())}}complete(){super.complete();this.subject.complete()}error(a){super.error(a);this.subject.error(a)}get state(){return this._state.get()}TU(){return this.state}destroy(a){ja(this.domain.zi(this._state.get(),
a))}ij(a){return this.domain.zi(this._state.get(),a)}constructor(a,b,c,d){super();this.domain=b;this.wh=c;this.A4=d;this._state=(__c.fr.F(this),void 0);this.subject=new __c.flb;this.c8b=0;this._state=new __c.Xp(a)}};__c.aa=__c.fr.prototype;__c.aa.M4=da(162);__c.aa.pRa=da(159);__c.aa.YJa=da(156);__c.aa.ZD=da(153);__c.aa.cya=da(150);__c.aa.Z6=da(147);__c.aa.IV=da(144);__c.aa.bP=da(133);
Fsb=class{uf(a){a.length>0&&(this.C5c=a.endsWith("\n"),this.vs.uf(a));return this}um(a,b){this.vs.um(a,this.wh.normalize(a,b));return this}attrs(a){this.vs.attrs(__c.qp(this.wh,a));return this}build(){const a=this.vs.build();la(a.length===0||this.C5c);return a}constructor(a,b){this.vs=a;this.wh=b;this.C5c=!1}};
Gsb=class{retain(a){this.uf.retain(a);this.attrs.retain(a);return this}insert(a){this.uf.insert(a);this.attrs.insert(a.length);return this}delete(a){this.uf.delete(a);this.attrs.retain(a);return this}open(a,b){this.attrs.open(a,this.wh.normalize(a,b));return this}$Z(a){this.attrs.$Z(__c.qp(this.wh,a));return this}close(a){this.attrs.close(a);return this}XO(a){this.attrs.XO(a);return this}build(){return new Esb(this.uf.build(),this.attrs.build())}constructor(a,b){this.wh=a;this.attrs=b;this.uf=new __c.dp}};
__c.Hsb=class extends __c.Vp{Yg(){return new Fsb(this.domain.Yg(this.wh),this.wh)}q6(a){a=this.domain.FTa(a,this.wh);return new Gsb(this.wh,a)}Dn(a){return a}nA(a){hsb(a,this.wh);return new __c.fr(a,this.domain,this.wh,this.A4)}connect(a,b){return this.Dn(a).connect(b)}fc(a){return this.Dn(a).fc()}destroy(a,b){return this.Dn(a).destroy(b)}ij(a,b){return this.Dn(a).ij(b)}constructor(){var a=__c.ir;super(__c.Up,__c.Up);this.wh=a;this.A4="style";this.domain=new __c.Dsb(__c.vmb)}};
__c.Hsb.prototype.NUa=da(164);__c.Hsb.prototype.aF=da(128);
__c.Isb=class extends __c.Wp{static F(a){hb(a,{fpb:Ro.struct,isEmpty:Ro,items:Ro({equals:__c.blb.shallow}),mZd:Ro})}get fpb(){return this.ud.get().Xe}Er(a){a=this.B0d!=null?this.B0d(a):a;super.Er(a)}get isEmpty(){const {Or:a,sna:b}=this.cells.get();return a===0&&(b===0||b===1&&Nrb(this.cells.get()))}get items(){const a=new Set;this.cells.get().forEach(0,{item:b=>a.add(b.mutable)});return a}get mZd(){if(this.cells.get().sna<4E3){const a=Math.ceil(Math.log(this.cells.get().sna)/Math.log(2));return Math.pow(2,
a)}return Math.round(this.cells.get().sna/1E3)*1E3}get length(){return Math.max(this.cells.get().length,this.attrs.get().length)}q6(){var a;return new Asb(new __c.Imb(()=>!0),this.domain.attrs.q6(this.attrs.get(),this.cells.get().length,this.wh),(a=this.domain.ud)===null||a===void 0?void 0:a.Pg())}NMa(a){const b=g=>{a:{var h=this.cells.get();let k=0;for(const l of h.Zx){if(l.type===1&&l.state===f){h=k;break a}k+=l.length}h=-1}la(h>=0,"cell not found");return __c.Uo(this).retain(h).update(g).build()},
c=__c.Ao(this,g=>b(g)),{mutable:d,Ox:e}=__c.Bo(this.type,a,c),f={mutable:d,to:e,from:c};return f}F$b(a,b){__c.Co(this.type,b,a.to,a.mutable)}insertAt(a,b){a=a.resolve(this.cells.get());ja(0<=a&&a<=Math.max(0,this.cells.get().length-1),"Position {} is not in range [0, {}]",a,Math.max(0,this.cells.get().length-1));a===this.cells.get().length&&ja(typeof b==="string"&&b.endsWith("\n"));this.Er(this.domain.Pg().retain(a).insert(b).build());if(typeof b!=="string"){b=this.cells.get().jJb(a);if(b==null||
typeof b==="string")throw Error(`item expected at ${a}, found: ${b}`);return b.mutable}}setSelection(a,b){const c=this.ud.get().Xe.get(a);var d=b===null||b===void 0?void 0:b.resolve(this.cells.get());b=this.domain.Pg();d=d&&[d.start,d.end];var e;(e=b.ud)===null||e===void 0||e.r3a(a,c,d);a=b.build();this.Er(a)}cursor(a,b){return(new br(this.cells.get(),this.attrs.get(),this.ud.get())).RJ(c=>c.mutable).cursor(a,b)}forEach(a){(new br(this.cells.get(),this.attrs.get(),this.ud.get())).forEach({...a,item:(b,
c,d,e,f)=>a.item(b.mutable,c,d,e,f)})}n0(a){var b=a.DR,c=a.sR;a=a.sd;const d=new __c.Amb,e=new __c.Imb(k=>k),f=this.cells.get().Cd(b.pre);for(b=b.Cd(this.cells.get().length,0);;){let k=f.head;var g=b.head;if(!g)break;if(g.type===2)k=void 0,g=__c.Zo(b);else if(k){var h=Math.min(k.length,g.Gca);k=f.Go(h);g=__c.kjb(b,h)}if(g.type===2)k=g.state.RJ(l=>this.NMa(l)),d.region(k),e.Pya(k);else if(k)switch(g.type){case 0:d.region(k);e.retain(g.length);break;case 1:ja(k.type===1);k.state.to.next(g.delta);d.region(k);
e.retain(1);break;case 3:h=g.oldState;g=g.newState;k.type===1?(ja(k.type===h.type,"{} != {}",k.type,h.type),this.F$b(k.state,h.state)):__c.mjb(this.domain.cells,k,h);h=k;k=g.RJ(l=>this.NMa(l));d.region(k);__c.Yo(e,h,k);break;default:throw new r(g);}else throw Error("reader exhausted prematurely");}f.finish();b.finish();this.cells.set(d.build());this.attrs.set(this.domain.attrs.apply(this.attrs.get(),c));this.ud.set(this.domain.ud.apply(this.ud.get(),m(a)));c=new cr(e.build(),c,a);this.PMb.next(c)}complete(){super.complete();
this.PMb.complete()}error(a){super.error(a);this.PMb.error(a)}destroy(a){ja(this.domain.zi(this.fc(),a))}TU(){return(new br(this.cells.get(),this.attrs.get(),this.ud.get())).RJ(a=>this.type.fc(a.mutable))}ij(a){var b=this.length;const c=this.domain.cells.Pg();c.Qya(a.cells);this.cells.get().forEach(b,{item:g=>c.RY(this.type.fc(g.mutable)),jb:g=>c.RY(g),dk:g=>c.retain(g)});const d=this.domain.attrs.q6(this.attrs.get(),b+a.length);d.Qya(a.attrs,a.length);this.attrs.get().forEach(b,{grad:(g,h)=>d.$Z(__c.go(g,
()=>{}),__c.go(h,()=>{})),Lc:g=>d.retain(g)});let e;if(this.domain.ud){var f;e=(f=this.domain.ud)===null||f===void 0?void 0:f.Pg();b=this.ud.get().Xe;a=a.ud?a.ud.Xe:new Map;f=__c.ho([...b.keys(),...a.keys()]);for(const g of f)e.r3a(g,b.get(g),a.get(g))}this.Er(this.domain.He(c.build(),d.build(),e&&e.build()));return!0}constructor(a,b,c,d){super();this.wh=a;this.type=b;this.domain=c;this.cells=(__c.Isb.F(this),void 0);this.PMb=new __c.flb;m(c.ud);this.cells=new __c.Xp(d.cells.RJ(f=>this.NMa(f)));this.attrs=
new __c.Xp(d.attrs);this.ud=new __c.Xp(m(d.ud));d.attrs.forEach(0,{grad:f=>a.gR(f)});const e=(0,__c.jlb)(f=>this.wh.KC(f)&&this.attrs.get().attributes[f]||new Set,{equals:__c.blb.shallow});this.attributes=new Proxy({},{get:(f,g)=>e(g),has:(f,g)=>this.wh.KC(g),ownKeys:()=>Object.keys(this.attrs.get().attributes),getOwnPropertyDescriptor:(f,g)=>{f=this.wh.KC(g)?this.attrs.get().attributes[g]:void 0;if(f!=null)return{enumerable:!0,configurable:!0,value:f}}})}};__c.Isb.prototype.bP=da(132);
__c.Ksb=class extends __c.Vp{Pg(){return this.domain.Pg(this.wh)}Yg(){return this.domain.Yg(this.wh)}Dn(a){return a}nA(a){return new __c.Isb(this.wh,this.type,this.domain,a)}connect(a,b){return this.Dn(a).connect(b)}create(a,b,c){return this.Dn(super.create(a,b,c))}destroy(a,b){return this.Dn(a).destroy(b)}fc(a){return this.Dn(a).fc()}ij(a,b){return this.Dn(a).ij(b)}constructor(){var a=__c.Iq,b=Jsb;super(__c.Up,__c.Up);this.wh=a;this.type=b;this.domain=new __c.Dsb(this.type.domain,__c.gnb)}};
__c.Ksb.prototype.NUa=da(163);__c.Ksb.prototype.aF=da(127);
var Lsb=class extends __c.Lob{ETa(){return new Lsb(this.scope,this,!0)}isValid(a){return Number.isInteger(a)&&this.min<=a&&a<=this.max}TDa(a,b){return a===b}constructor(a,{min:b=Number.MIN_SAFE_INTEGER,max:c=Number.MAX_SAFE_INTEGER,defaultValue:d=0}={},e=!1){super(a,d,e);ja(Number.isInteger(b)&&b>=Number.MIN_SAFE_INTEGER);ja(Number.isInteger(c)&&c<=Number.MAX_SAFE_INTEGER);this.min=b;this.max=c;__c.Kjb(this)}},Msb=__webpack_require__(519427),jr=Msb.computed,Nsb=Msb.observable,Osb=Msb.reaction;var Psb,Qsb,Rsb,Ssb,Usb;Psb=Go({$c:cq,Dw:cq});Qsb=Go({type:Eo("logistic_sigmoid")});Rsb=Go({fb:cq,easing:Ho({logistic_sigmoid:Qsb},a=>a.type)});Ssb=To({values:{audio:Zp,id:gq},attributes:{trim:Oo(Psb),loop:Mo(__c.Pnb),volume:Mo(__c.Jo(0,4)),$c:qq,fb:qq,Y1:Oo(Rsb),Z1:Oo(Rsb)}});__c.Tsb=Vo(Ssb);Usb=To({Sb:{tracks:__c.Tsb}});var Vsb,Wsb,Xsb,Ysb,Zsb,$sb,atb,btb,ctb,dtb,etb,ftb,gtb,itb;Vsb=Go({video:Zp});Wsb=Go({fb:__c.Zlb,mask:Lo(Vsb)});Xsb=Go({fb:__c.Zlb,mask:Lo(Vsb),reverse:__c.Wlb});Ysb=Go({kWa:Fo(__c.Plb),oWa:Fo(__c.Plb),Haa:Fo($p),easing:Eo(1,2,3,4,5),fb:__c.Ylb,ruc:Yp});Zsb=Go({vg:hq,scale:hq,direction:Lo(Eo(1,2,3,4,5)),Jh:Lo(Eo(1,2,3,4,5)),color:gq,Za:Lo(Wsb),hb:Lo(Xsb),Ema:Lo(Ysb)});$sb=Go({type:Eo("none")});atb=Go({type:Eo("sequenced"),animation:$p,Wo:Lo(Zsb)});btb=Go({type:Eo("independent"),animation:$p,Wo:Lo(Zsb)});
ctb=Ho({none:$sb,sequenced:atb,independent:btb},a=>a.type);dtb=Go({vg:__c.unb,direction:Eo(1,2)});etb=Go({vg:__c.unb,mVe:Yp});ftb=Go({vg:__c.unb,direction:Eo(1,2)});gtb=Go({vg:__c.unb});__c.htb=To({attributes:{rotate:Oo(dtb),apa:Oo(etb),nsa:Oo(ftb),yua:Oo(gtb)}});itb=To({values:{Zp:Zp},attributes:{trigger:Mo(Eo(1)),C6d:Mo(Eo(1))}});__c.jtb=Vo(itb);var ktb=class{static F(a){hb(a,{value:Nsb.ref})}set(a){la(this.value==null||this.value===a);this.value=a}get(){return this.value}constructor(){this.value=(ktb.F(this),void 0)}},ltb=class{static F(a){hb(a,{map:Nsb.shallow})}set(a,b){const c=this.map.get(a);c?ja(b===c,"value already registered for key: {}",a):this.map.set(a,b)}get(a){return this.map.get(a)}constructor(){this.map=(ltb.F(this),new Map)}};var mtb,ntb,otb,ptb,qtb,rtb,stb,utb,vtb,wtb,xtb,ytb,ztb,Atb,Btb,Ctb,Dtb,Etb,kr,Ftb,Gtb,Ktb,Ltb,Mtb,Ntb,mr,Otb,Ptb,Qtb,Rtb,Stb,Ttb,Utb,Vtb,Wtb,Xtb,Ytb,Ztb,$tb,aub,bub,cub,dub,fub,nr,gub,hub,iub,or,jub,kub,lub,mub,nub,oub,pub,qub,rub,tub,uub,vub,wub,xub,yub,zub,Aub,pr,qr,Bub,Cub,Dub,Eub,Fub,Gub,Iub,Jub,Kub,Lub,Mub,Nub,Oub,Pub,Qub,Rub,Sub,Tub,Uub,Vub,Wub,Xub,Yub,Zub,$ub,avb,bvb,cvb,dvb,evb,fvb,hvb,ivb,kvb;mtb=Eo(1,2);ntb=Go({type:Eo("palette"),Ka:Fo(Cq)});
otb=Go({type:Eo("interpolate"),colorSpace:mtb,from:Cq,to:Cq});ptb=Ho({palette:ntb,interpolate:otb},a=>a.type);qtb=Eo(1,2,3,4,5);rtb=Mo(qtb);stb=Mo(Lo(qtb));__c.ttb=Vo(__c.iq);utb=Go({format:Zp,nF:Lo(__c.Olb),ct:Lo(__c.Olb)});vtb=Eo("stacked","proportional-stacked");wtb=Lo(Eo("stacked","proportional","unstacked","stream"));xtb=Eo("auto","radial","circular");ytb=To({Sb:{values:__c.ttb},attributes:{id:oq,ya:Oo(ptb),label:oq,Wc:Oo(utb)}});ztb=To({values:{type:Eo("COUNT")}});Atb=To({values:{type:Eo("AVERAGE")}});
Btb=To({values:{type:Eo("MIN")}});Ctb=To({values:{type:Eo("MAX")}});Dtb=To({values:{type:Eo("SUM")}});Etb=To({values:{type:Eo("MEDIAN")}});kr=kp({COUNT:ztb,AVERAGE:Atb,MIN:Btb,MAX:Ctb,SUM:Dtb,MEDIAN:Etb},a=>a.type,a=>a.type);Ftb=To({Sb:{fill:Fq}});Gtb=Po(Ftb);__c.Htb=To({values:{type:Eo("single")},Sb:{color:Ftb}});__c.Itb=To({values:{type:Eo("columns")},Sb:{Ka:Gtb}});__c.Jtb=To({values:{type:Eo("rows")},Sb:{Ka:Gtb}});lr=__c.lr=To({values:{type:Eo("groups")},Sb:{Ka:Gtb}});
Ktb=kp({single:__c.Htb,columns:__c.Itb},a=>a.type,a=>a.type);Ltb=kp({single:__c.Htb,groups:lr},a=>a.type,a=>a.type);Mtb=kp({columns:__c.Itb,groups:lr},a=>a.type,a=>a.type);Ntb=kp({rows:__c.Jtb,groups:lr},a=>a.type,a=>a.type);mr=kp({single:__c.Htb,columns:__c.Itb,groups:lr},a=>a.type,a=>a.type);Otb=Go({start:hq,end:hq});Ptb=Go({start:gq,end:gq});Qtb=To({values:{type:Eo("buttons")},Sb:{tq:Fq}});Rtb=To({values:{type:Eo("dropdown")},Sb:{tq:Fq}});Stb=kp({buttons:Qtb,dropdown:Rtb},a=>a.type,a=>a.type);
Ttb=To({values:{type:Eo("slider")},Sb:{tq:Fq}});Utb=kp({slider:Ttb},a=>a.type,a=>a.type);Vtb=To({values:{type:Eo("single")},Sb:{control:No(Stb)},attributes:{Dga:oq}});Wtb=To({values:{type:Eo("multi")},Sb:{control:No(Stb)},attributes:{Zna:Mo(Fo(Zp))}});Xtb=To({values:{type:Eo("range")},Sb:{control:No(Utb)},attributes:{xw:Oo(Ptb)}});Ytb=kp({single:Vtb,multi:Wtb,range:Xtb},a=>a.type,a=>a.type);Ztb=To({values:{type:Eo("range")},Sb:{control:No(Utb)},attributes:{xw:Oo(Otb)}});
$tb=kp({range:Ztb},a=>a.type,a=>a.type);aub=To({values:{type:Eo("column")},Sb:{config:No(Ytb)}});bub=To({values:{type:Eo("row-text")},attributes:{xV:oq},Sb:{config:No(Ytb)}});cub=To({values:{type:Eo("row-numeric")},attributes:{xV:oq},Sb:{config:No($tb)}});dub=kp({column:aub,"row-text":bub,"row-numeric":cub},a=>a.type,a=>a.type);__c.eub=Vo(dub);fub=To({Sb:{filters:__c.eub}});nr=No(Lo(fub));gub=To({values:{type:Eo("none")}});hub=To({values:{type:Eo("populate")}});
iub=To({values:{type:Eo("playthrough")},attributes:{loop:Mo(__c.Pnb)}});or=kp({none:gub,populate:hub},a=>a.type,a=>a.type);jub=kp({none:gub,playthrough:iub},a=>a.type,a=>a.type);kub=Eo(1,2);lub=Eo("start","center","end");mub=To({attributes:{Ve:Oo(lub),vertical:Oo(lub)}});nub=To({attributes:{text:Mo(Cq)},Sb:{background:Fq}});oub=To({Sb:{Hba:nub,Tca:nub}});pub=To({attributes:{fontFamily:Oo(Io(__c.Nob)),fontSize:Oo(bq),fontWeight:Oo(Eo(...__c.Mob)),fontStyle:Oo(Eo(...__c.Oob))}});
qub=To({attributes:{visible:jq,position:Oo(kub)},Sb:{alignment:mub,ya:No(Lo(oub)),Ng:pub}});rub=To({attributes:{visible:jq},Sb:{alignment:mub,color:No(Lo(nub)),Ng:pub}});__c.sub=["start","center","end"];tub=To({attributes:{fontSize:Oo(bq),fontFamily:Oo(Io(__c.Nob)),fontWeight:Oo(Eo(...__c.Mob)),fontStyle:Oo(Eo(...__c.Oob)),color:Oo(Cq),Xn:Oo(Eo(...__c.Pob)),textAlign:Oo(Eo(...__c.sub)),lineHeight:Oo(bq)}});uub=To({attributes:{text:Mo(Io(/^[^\r\n]*$/)),kd:__c.Vnb},Sb:{Ng:tub}});
vub=Go({type:Eo("TARGET_TICKS"),dla:Lo($p)});wub=Ho({TARGET_TICKS:vub},a=>a.type);xub=Go({type:Eo("NUMERIC_LINEAR"),min:Lo(bq),max:Lo(bq),spacing:wub});yub=Go({type:Eo("CATEGORICAL")});zub=Go({type:Eo("NUMERIC_BIN")});Aub=To({Sb:{title:uub}});pr=Aub.Fi({attributes:{scale:Mo(xub)}});qr=Aub.Fi({attributes:{scale:Mo(yub)}});Bub=Aub.Fi({attributes:{scale:Mo(zub)}});
Cub=To({values:{type:Eo("GROUPED_COLUMN")},attributes:{zg:oq,kh:nq,Fo:oq,spacing:kq,Ry:jq,vB:qq,Hb:qq},Sb:{Yb:No(Lo(kr)),Ie:qub,ya:No(Lo(mr)),Hc:No(Lo(or)),Ca:nr,Dc:qr,oc:pr}});Dub=To({values:{type:Eo("STACKED_COLUMN")},attributes:{zg:oq,kh:nq,Fo:oq,spacing:kq,Ry:jq,vB:qq,Hb:qq,ap:Mo(vtb)},Sb:{Yb:No(Lo(kr)),Ie:qub,qy:rub,ya:No(Lo(mr)),Hc:No(Lo(or)),Ca:nr,Dc:qr,oc:pr}});
Eub=To({values:{type:Eo("GROUPED_ROW")},attributes:{zg:oq,kh:nq,Fo:oq,spacing:kq,Ry:jq,vB:qq,Hb:qq},Sb:{Yb:No(Lo(kr)),Ie:qub,ya:No(Lo(mr)),Hc:No(Lo(or)),Ca:nr,Dc:pr,oc:qr}});Fub=To({values:{type:Eo("STACKED_ROW")},attributes:{zg:oq,kh:nq,Fo:oq,spacing:kq,Ry:jq,vB:qq,Hb:qq,ap:Mo(vtb)},Sb:{Yb:No(Lo(kr)),Ie:qub,qy:rub,ya:No(Lo(mr)),Hc:No(Lo(or)),Ca:nr,Dc:pr,oc:qr}});Gub=To({values:{type:Eo("PIE")},attributes:{zg:oq,kh:oq,spacing:qq,vB:qq,Hb:qq},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ntb)),Hc:No(Lo(or)),Ca:nr}});
Iub=To({values:{type:Eo("DONUT")},attributes:{zg:oq,kh:oq,spacing:qq,vB:qq,Hb:qq},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ntb)),Hc:No(Lo(or)),Ca:nr}});Jub=To({values:{type:Eo("LINE")},attributes:{zg:oq,kh:nq,Ry:jq,Ck:qq,Jj:qq,Bm:stb,WP:jq},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ktb)),Hc:No(Lo(or)),Ca:nr,Dc:qr,oc:pr}});Kub=To({values:{type:Eo("STACKED_AREA")},attributes:{zg:oq,kh:nq,Ry:jq,Ck:qq,Jj:qq,Bm:stb,WP:jq,ap:Mo(wtb)},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ktb)),Hc:No(Lo(or)),Ca:nr,Dc:qr,oc:pr}});
Lub=To({attributes:{xL:mq,zg:oq,i5:oq,j5:nq,Fo:oq},Sb:{Hc:No(Lo(or)),Ca:nr}});Mub=Lub.Fi({values:{type:Eo("SCATTERPLOT")},attributes:{Ry:jq,Jj:qq,Bm:stb},Sb:{Yb:No(Lo(kr)),ya:No(Lo(mr)),Dc:pr,oc:pr}});Nub=Lub.Fi({values:{type:Eo("BUBBLEPLOT")},attributes:{Jj:mq,Bm:rtb,Ro:oq},Sb:{Yb:No(Lo(kr)),ya:No(Lo(mr)),Dc:pr,oc:pr}});Oub=To({values:{type:Eo("BEESWARM")},attributes:{padding:kq}});Pub=kp({BEESWARM:Oub},a=>a.type,a=>a.type);
Qub=Lub.Fi({values:{type:Eo("DOTPLOT")},attributes:{Jj:mq,Bm:rtb,Ro:oq,TO:Mo(Eo("X","Y"))},Sb:{Yb:No(Lo(kr)),ya:No(mr),vY:qr,wW:pr,ap:No(Lo(Pub))}});Rub=Lub.Fi({values:{type:Eo("GROUPED_DOTPLOT")},attributes:{Jj:mq,Bm:rtb,Ro:oq},Sb:{ya:No(Mtb),Dc:qr,oc:qr,Iva:No(Lo(Oub))}});Sub=To({values:{type:Eo("PACKED_CIRCLES")},attributes:{Ro:nq,groupBy:nq,YI:lq},Sb:{ya:No(Lo(lr)),Hc:No(Lo(or)),Ca:nr}});Tub=To({values:{type:Eo("TREEMAP")},attributes:{Ro:nq,groupBy:nq,YI:lq},Sb:{ya:No(Lo(lr)),Hc:No(Lo(or)),Ca:nr}});
Uub=To({values:{type:Eo("BAR_RACE")},attributes:{zg:oq,Fo:nq,kh:nq,Rza:lq,spacing:mq,Hb:mq,autoplay:jq,playbackRate:mq,loop:Mo(__c.Pnb)},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ltb)),Hc:No(Lo(jub)),Ca:nr,Dc:pr,oc:qr}});Vub=To({values:{type:Eo("HISTOGRAM")},attributes:{kh:oq,spacing:qq,vB:qq,Hb:qq,hna:qq},Sb:{ya:No(Lo(__c.Htb)),Hc:No(Lo(or)),Ca:nr,Dc:Bub,oc:pr}});Wub=To({values:{type:Eo("RADAR")},attributes:{zg:oq,kh:nq,Ck:mq,Gxa:mq},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ktb)),Hc:No(Lo(or)),Ca:nr}});
Xub=To({values:{type:Eo("POPULATION_PYRAMID")},attributes:{Ry:jq,spacing:qq,vB:qq,Hb:qq}});Yub=To({values:{type:Eo("FUNNEL")},attributes:{zg:oq,kh:oq,spacing:qq,vB:qq,Hb:qq,WP:jq},Sb:{Yb:No(Lo(kr)),ya:No(Lo(Ntb)),Hc:No(Lo(or)),Ca:nr,oc:qr}});Zub=To({values:{type:Eo("DUMBBELL")},attributes:{Ry:jq,Ck:qq,Jj:qq,Bm:stb}});$ub=To({values:{type:Eo("LOLLIPOP")},attributes:{Ry:jq,Ck:qq,Jj:qq,Bm:stb}});
avb=To({values:{type:Eo("SUNBURST")},attributes:{Ro:nq,groupBy:nq,YI:lq,ILa:Mo(xtb),$Gd:Mo(Eo(1,2)),Gba:mq},Sb:{ya:No(lr),Hc:No(Lo(or)),Ca:nr}});bvb=To({values:{type:Eo("TIME_SERIES")},attributes:{Ck:qq,WP:jq}});cvb=To({values:{type:Eo("PROGRESS")},attributes:{SPb:Mo(Eo(1,2,3,4)),endpoint:Mo(Eo(1,2)),s5a:kq}});dvb=To({values:{type:Eo("PICTOGRAM")},attributes:{sjc:nq,spacing:kq}});
__c.rr=kp({GROUPED_COLUMN:Cub,STACKED_COLUMN:Dub,GROUPED_ROW:Eub,STACKED_ROW:Fub,PIE:Gub,DONUT:Iub,LINE:Jub,STACKED_AREA:Kub,SCATTERPLOT:Mub,BUBBLEPLOT:Nub,DOTPLOT:Qub,GROUPED_DOTPLOT:Rub,PACKED_CIRCLES:Sub,TREEMAP:Tub,BAR_RACE:Uub,HISTOGRAM:Vub,RADAR:Wub,POPULATION_PYRAMID:Xub,FUNNEL:Yub,DUMBBELL:Zub,LOLLIPOP:$ub,SUNBURST:avb,TIME_SERIES:bvb,PROGRESS:cvb,PICTOGRAM:dvb},a=>a.type,a=>a.type);evb=Go({top:cq,right:cq,bottom:cq,left:cq});fvb=To({attributes:{padding:Mo(evb)},Sb:{background:Fq}});
__c.gvb=Vo(ytb);hvb=To({attributes:{url:oq},Sb:{prefix:uub,AE:uub}});ivb=To({Sb:{title:uub,subtitle:uub,source:hvb}});__c.jvb=new ktb;
kvb=To({Sb:{uA:ivb,config:No(__c.rr),data:__c.gvb,style:fvb},attributes:{Zk:Oo(__c.fob),H2:jq,tN:jq,qO:jq,q4:jq,mM:jq},computed:{Sb:{data:void 0,U_a:void 0},attributes:{},create:a=>{const b=jr(()=>{var c;return(c=__c.jvb.get())===null||c===void 0?void 0:c(a)});return{Sb:{data:Trb(jr(()=>{var c;return((c=b.get())===null||c===void 0?void 0:c.data)||a.data})),U_a:jr(()=>{var c;return(c=b.get())===null||c===void 0?void 0:c.U_a})},attributes:{}}}}});var lvb=Fo(Fo(Io(/^[a-zA-Z][a-zA-Z0-9_-]*$/)),a=>{if(a.length===0||a[0].length===0||!a.every(c=>c.length===a[0].length))return!1;const b=new Map;for(let c=0;c<a.length;c++)for(let d=0;d<a[c].length;d++){const e=a[c][d],f=b.get(e);f?b.set(e,{count:f.count+1,bfa:Math.min(f.bfa,d),qSa:Math.max(f.qSa,d+1),Qn:Math.min(f.Qn,c),To:Math.max(f.To,c+1)}):b.set(e,{count:1,bfa:d,qSa:d+1,Qn:c,To:c+1})}return Array.from(b.values()).every(({count:c,bfa:d,qSa:e,Qn:f,To:g})=>c===(e-d)*(g-f))}),mvb=Fo(Lo(Io(/^[0-9]+(\.[0-9]+)?fr$/))),
nvb=Go({template:lvb,Ana:mvb,Tw:mvb,zna:cq,Nsa:cq},a=>a.Tw.length===a.template.length&&a.Ana.length===a.template[0].length),ovb=To({Sb:{fill:Fq,stroke:No(Lo(Gq))},attributes:{Hb:cmb}}),pvb=Po(ovb);var qvb,rvb,svb,tvb,uvb,vvb,wvb,xvb,yvb,Avb,Bvb,Dvb,Evb;qvb=Mo(Lo(Eo("start","center","end")));rvb=Mo(Lo(Eo("start","center","end")));svb=Mo(Lo(Io(/^[1-9]\d*$/)));tvb=To({attributes:{all:pq,Nc:pq,Fd:pq,Kc:pq,Td:pq}});uvb=To({Sb:{padding:tvb},attributes:{gridColumnStart:svb,gridColumnEnd:svb,gridRowStart:svb,gridRowEnd:svb,alignSelf:qvb,justifySelf:rvb}});vvb=Po(uvb);wvb=Mo(Fo(Io(/^auto$|^[0-9]+(\.[0-9]+)?(fr|px)$/)));
xvb=To({Sb:{gA:vvb},attributes:{gridTemplateColumns:wvb,gridTemplateRows:wvb,columnGap:kq,rowGap:kq}});yvb=To({Sb:{grid:xvb},attributes:{Hj:qq}});__c.zvb=Vo(yvb);Avb=To({Sb:{rules:__c.zvb}});Bvb=To({attributes:{all:pq,Wma:pq,Vma:pq,Uma:pq,Tma:pq}});__c.Cvb=To({Sb:{all:No(Lo(Gq)),Nc:No(Lo(Gq)),Td:No(Lo(Gq)),Fd:No(Lo(Gq)),Kc:No(Lo(Gq))}});Dvb=To({Sb:{fill:Fq,border:__c.Cvb,Hb:Bvb}});Evb=Mo(Eo(1,2));__c.sr=class{constructor(a,b){this.x=a;this.y=b}};__c.tr=class{constructor(a,...b){this.mode=a;this.type=0;this.params=b}};__c.ur=class{constructor(a,...b){this.mode=a;this.type=1;this.params=b}};__c.Fvb=class{constructor(a,...b){this.mode=a;this.type=2;this.params=b}};__c.Gvb=class{constructor(a,...b){this.mode=a;this.type=3;this.params=b}};__c.vr=class{constructor(a,b,c){this.eV=a;this.tC=b;this.end=c}};__c.wr=class{constructor(a,...b){this.mode=a;this.type=4;this.params=b}};
__c.Hvb=class{constructor(a,b){this.tC=a;this.end=b}};__c.Ivb=class{constructor(a,...b){this.mode=a;this.type=5;this.params=b}};__c.xr=class{constructor(a,b){this.control=a;this.end=b}};__c.yr=class{constructor(a,...b){this.mode=a;this.type=6;this.params=b}};__c.Jvb=class{constructor(a){this.end=a}};__c.Kvb=class{constructor(a,...b){this.mode=a;this.type=7;this.params=b}};__c.zr=class{constructor(a,b,c,d,e,f){this.hEa=a;this.jEa=b;this.nSa=c;this.KLa=d;this.sweep=e;this.end=f}};
__c.Lvb=class{constructor(a,...b){this.mode=a;this.type=8;this.params=b}};__c.Ar=class{constructor(a=0){this.mode=a;this.type=9}};var ksb,Yq,msb,lsb,Zq,$q,jsb,Br,isb;ksb=Wq(parseFloat,Uq(/^(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][-+]?\d+)?/));Yq=Wq((a,b)=>(a==="-"?-1:1)*b,Uq(/^[-+]?/),ksb);msb=Wq(a=>parseInt(a,10)===1,Uq(/^[01]/));lsb=Uq(/^(?:\s+,?\s*|,\s*)/);Zq=Uq(/^\s*,?\s*/);$q=Uq(/^\s*/);jsb=Wq((a,b)=>b,Zq,Yq);Br=()=>!0;isb=nsb({jNc:Br,nNc:Br,KPc:Br,rPc:Br,MPc:Br,DMc:Br,JOc:Br,nOc:Br,YNc:Br,cQc:Br,mNc:Br,JPc:Br,qPc:Br,LPc:Br,CMc:Br,fNc:Br,dPc:Br});
__c.Mvb=nsb({jNc:(a,b)=>new __c.sr(a,b),nNc:(a,b,c)=>new __c.vr(a,b,c),KPc:(a,b)=>new __c.Hvb(a,b),rPc:(a,b)=>new __c.xr(a,b),MPc:a=>new __c.Jvb(a),DMc:(a,b,c,d,e,f)=>new __c.zr(a,b,c,d?1:0,e?1:0,f),JOc:ar(__c.tr),nOc:ar(__c.ur),YNc:ar(__c.Fvb),cQc:ar(__c.Gvb),mNc:ar(__c.wr),JPc:ar(__c.Ivb),qPc:ar(__c.yr),LPc:ar(__c.Kvb),CMc:ar(__c.Lvb),fNc:ar(__c.Ar),dPc:a=>a});var Nvb,Ovb,Qvb,Rvb,Svb,Tvb;Nvb=__c.Do(function(a){return __c.Tq(a)});Ovb=To({Sb:{fill:Fq,stroke:No(Lo(Gq))},attributes:{d:Mo(Nvb),Hb:mq}});__c.Pvb=Vo(Ovb);Qvb=Lo(Eo(1,2));Rvb=To({values:{Ve:Qvb,vertical:Qvb},attributes:{source:__c.Tnb,Ts:qq,Ss:qq}});Svb=Go({Twa:Yp,O$b:Yp});Tvb={Sb:{paths:__c.Pvb,slice:Lo(Rvb)},attributes:{viewBox:__c.Tnb,Fv:Oo(Svb)}};var Uvb,Vvb,Yvb,Zvb,$vb,awb,bwb,cwb,dwb,ewb,fwb,gwb;Uvb=To({Sb:{oJ:__c.Hnb},attributes:{height:mq,minHeight:mq}});Vvb=To({values:{id:Zp},attributes:{width:mq}});__c.Wvb=Vo(Uvb);__c.Xvb=Vo(Vvb);Yvb=To({attributes:{Nc:qq,Fd:qq,Kc:qq,Td:qq}});Zvb=Go({color:__c.Cnb});$vb=Oo(Zvb);awb=To({attributes:{Nc:$vb,Fd:$vb,Kc:$vb,Td:$vb}});bwb=Go({Xo:__c.Jnb});cwb=Oo(bwb);dwb=To({attributes:{Nc:cwb,Fd:cwb,Kc:cwb,Td:cwb}});ewb=a=>To({Sb:{content:a,fill:Fq,WK:Yvb,borderColor:awb,RU:dwb},attributes:{Ll:__c.Nnb}});
fwb=To({attributes:{weight:mq,color:__c.Dnb,Xo:__c.Knb}});gwb=To({Sb:{rows:__c.Wvb,columns:__c.Xvb,borderStyle:fwb},attributes:{direction:Oo(Eo(1,2)),jB:mq,cellPadding:mq}});var Cr=To({attributes:{fb:mq}}),hwb=Cr.Fi({values:{type:Eo("chop")},attributes:{direction:Mo(Eo(1,2)),origin:Mo(Eo(1,2,3,4))}}),iwb=Cr.Fi({values:{type:Eo("color-wipe")},attributes:{Ka:Mo(Fo(Cq,a=>a.length<=6)),direction:Mo(Eo(1,2,3,4,5,6,7,8))}}),jwb=Cr.Fi({values:{type:Eo("cross-dissolve")}}),kwb=Cr.Fi({values:{type:Eo("match")}}),lwb=Cr.Fi({values:{type:Eo("flow")},attributes:{direction:Mo(Eo(1,2,3,4))}}),mwb=Cr.Fi({values:{type:Eo("slide")},attributes:{direction:Mo(Eo(1,2,3,4))}}),nwb=Cr.Fi({values:{type:Eo("stack")},
attributes:{direction:Mo(Eo(1,2,3,4))}}),owb=Cr.Fi({values:{type:Eo("wipe-circle")},attributes:{direction:Mo(Eo(1,2))}}),pwb=Cr.Fi({values:{type:Eo("wipe-line")},attributes:{direction:Mo(Eo(1,2,3,4))}}),qwb=kp({chop:hwb,"color-wipe":iwb,"cross-dissolve":jwb,flow:lwb,match:kwb,slide:mwb,stack:nwb,"wipe-circle":owb,"wipe-line":pwb},a=>a.type,a=>a.type),rwb=No(Lo(qwb));var swb="normal thin extralight light medium semibold bold ultrabold heavy".split(" "),twb=["normal","italic"],uwb=["none","normal"],vwb=["off","on"],wwb=["off","on"],xwb=["off","on"],ywb=["none","underline"],zwb=["none","strikethrough"],Awb=/^Y[A-Za-z0-9_-]{10},\d+$/,Bwb=["ltr","rtl"],Cwb=["none","uppercase","lowercase","capitalize"],Dwb=["start","center","end","justify"],Ewb="none disc circle square decimal lower-alpha lower-roman".split(" "),Fwb=tp("inline",swb),Gwb=tp("inline",twb),Hwb=tp("inline",
uwb),Iwb=tp("inline",vwb),Jwb=tp("inline",wwb),Kwb=tp("inline",xwb),Lwb=sp("inline",__c.olb,"1"),Mwb=sp("inline",__c.qlb,"0%"),Nwb=sp("inline",__c.llb,"#000000"),Owb=tp("inline",ywb),Pwb=tp("inline",zwb),Qwb=rp("inline",{min:-1E3,max:1E3,aza:"fixed"}),Rwb=sp("inline",__c.klb,""),Swb,Twb,Er,Uwb,Wwb,Xwb,Zwb,dxb,exb,gxb,hxb,ixb,jxb,kxb,lxb,pxb,qxb,txb,uxb,vxb,wxb,xxb,yxb,zxb,Axb,Bxb,Cxb,Dxb,Fxb,Gxb,Hxb,Ixb,Jxb,Kxb,Lxb,Nxb,Qxb,Rxb,Vxb;Swb=new Lsb("inline",{min:0});
__c.Dr={"font-weight":Fwb,"font-style":Gwb,"font-kerning":Hwb,"font-feature-liga":Iwb,"font-feature-clig":Jwb,"font-feature-calt":Kwb,"font-size-modifier":Lwb,"vertical-align":Mwb,color:Nwb,decoration:Owb,strikethrough:Pwb,kerning:Qwb,link:Rwb,"start-us":Swb,"font-family":sp("block",Awb,"YACgEZ1cb1Q,0"),"font-size":rp("block",{min:0,defaultValue:16,aza:"fixed"}),leading:rp("block",{min:500,max:2500,defaultValue:1400,aza:"fixed"}),spacing:rp("block",{min:0,max:5E3,aza:"fixed"}),direction:tp("block",
Bwb),tracking:rp("block",{min:-200,max:800,aza:"fixed"}),"text-transform":tp("block",Cwb),"text-align":tp("block",Dwb),"head-indent":rp("block",{min:0,aza:"fixed"}),"list-marker":tp("block",Ewb),"list-level":__c.Rjb({min:0}),style:tp("block","body pretitle title subtitle heading1 heading2 heading3 details caption header footer".split(" ")),semantics:tp("block","p h1 h2 h3 h4 h5 h6 blockquote".split(" "))};__c.ir=__c.Wjb({static:__c.Dr,mWa:{},hw:{}});Twb=Go({Vab:Yp,p5a:Yp});
Er=To({attributes:{top:kq,left:kq,width:mq,height:mq,rotation:__c.Bnb,aa:__c.Anb,ew:oq,$c:qq,fb:qq,link:Oo(Io(__c.klb)),locked:jq,WI:Oo(Twb),KB:jq,PM:oq,altText:Oo(__c.Onb),zfa:oq,zl:nq,anchor:oq,animation:Oo(ctb)},Sb:{N8:__c.rnb,l4:__c.rnb,Av:__c.Hnb,tu:__c.vob,wt:No(Lo(__c.htb)),transition:rwb}});__c.Fr=Er.Fi({values:{type:Eo("rect")},Sb:{fill:Fq,stroke:No(Lo(Gq))},attributes:{Hb:cmb}});Gr=__c.Gr=new __c.Hsb;__c.wqb.Gka(Gr);
Uwb=To({Sb:{text:Gr},attributes:{box:__c.Tnb,kd:__c.Vnb,Ll:__c.Nnb,R5:cmb,Fp:oq}});__c.Vwb=Vo(Uwb);Wwb=To({values:{type:Eo("block")},attributes:{minBlockSize:mq}});Xwb=kp({block:Wwb},a=>a.type,a=>a.type);__c.Ywb=Er.Fi(Tvb).Fi({values:{type:Eo("shape")},Sb:{og:__c.Vwb,resizeMode:Lo(Xwb)}});Zwb=Go({text:Zp,style:gq});__c.$wb=To({values:{type:Zp},Sb:{parameters:Po(__c.Qo(Zp))}});__c.axb=Vo(__c.$wb);__c.osb=To({Sb:{mc:__c.axb}});__c.bxb=new ktb;
__c.Hr=Er.Fi({values:{type:Eo("text"),kZ:Yp},Sb:{text:Gr,mc:No(Lo(__c.osb))},attributes:{kd:__c.Vnb,Ta:qq,Mb:qq,placeholder:Oo(Zwb),tna:__c.dmb,Sn:Mo(Eo(1,2,3)),writingMode:Oo(Eo(1,2,3)),Oz:Oo(Eo(1,2)),Fp:oq},computed:{Sb:{},attributes:{width:void 0,height:void 0},create:a=>{const b=a.width,c=a.height;if(!a.kZ)return{Sb:{},attributes:{width:b,height:c}};const d=jr(()=>{const e=__c.bxb.get();return e===null||e===void 0?void 0:e(a)});return{Sb:{},attributes:{width:So({get:()=>{var e,f;return(f=(e=d.get())===
null||e===void 0?void 0:e.width)!==null&&f!==void 0?f:b.value},set:e=>{b.value=e}}),height:So({get:()=>{var e,f;return(f=(e=d.get())===null||e===void 0?void 0:e.height)!==null&&f!==void 0?f:c.value},set:e=>{c.value=e}})}}}}});__c.cxb=Er.Fi({values:{type:Eo("embed"),url:Zp},attributes:{Ta:mq,Mb:mq}});dxb=Go({Zp:Zp,top:__c.xnb,left:__c.xnb,hsa:Lo(Eo(1,2))});exb=To({attributes:{marker:Oo(Eo(1,2,3,4,5,6,7,8,9)),anchor:Oo(dxb),position:Oo(__c.Qnb)}});__c.fxb=To({values:{direction:Eo(1,2)},attributes:{position:kq}});
gxb=Vo(__c.fxb);hxb=To({values:{type:Eo("elbowed")},Sb:{HG:gxb},attributes:{Hb:mq}});ixb=To({values:{type:Eo("curved")},attributes:{depth:kq,QCa:kq}});jxb=kp({elbowed:hxb,curved:ixb},a=>a.type,a=>a.type);kxb=To({Sb:{text:Gr},attributes:{width:mq,height:mq,position:__c.Anb,orientation:Mo(Eo(1,2)),Sn:Mo(Eo(1,2,3)),Oz:Oo(Eo(1,2)),Fp:oq}});lxb=Vo(kxb);__c.mxb=new ktb;
__c.nxb=Er.Fi({values:{type:Eo("line")},Sb:{start:exb,end:exb,fill:Fq,geometry:No(Lo(jxb)),og:lxb},attributes:{weight:lq,color:__c.Dnb,Xo:__c.Knb,Pt:jq},computed:{Sb:{},attributes:{top:void 0,left:void 0,width:void 0,height:void 0,rotation:void 0},create:a=>{const b=jr(()=>{const h=__c.mxb.get();return h===null||h===void 0?void 0:h(a)}),c=a.top,d=a.left,e=a.width,f=a.height,g=a.rotation;return{Sb:{},attributes:{top:So({get:()=>{var h,k;return(k=(h=b.get())===null||h===void 0?void 0:h.top)!==null&&
k!==void 0?k:c.value},set:h=>c.value=h}),left:So({get:()=>{var h,k;return(k=(h=b.get())===null||h===void 0?void 0:h.left)!==null&&k!==void 0?k:d.value},set:h=>d.value=h}),width:So({get:()=>{var h,k;return(k=(h=b.get())===null||h===void 0?void 0:h.width)!==null&&k!==void 0?k:e.value},set:h=>e.value=h}),height:So({get:()=>{var h,k;return(k=(h=b.get())===null||h===void 0?void 0:h.height)!==null&&k!==void 0?k:f.value},set:h=>f.value=h}),rotation:So({get:()=>{var h,k;return(k=(h=b.get())===null||h===void 0?
void 0:h.rotation)!==null&&k!==void 0?k:g.value},set:h=>g.value=h})}}}}});__c.oxb=Er.Fi({values:{type:Eo("grid")},Sb:{cells:pvb},attributes:{layout:Mo(nvb)}});pxb=To({attributes:{kd:__c.Vnb,Fp:oq},Sb:{text:Gr}});qxb=ewb(pxb);__c.rxb=Mrb(Er,To({Sb:{cells:Po(qxb),layout:gwb}})).Fi({values:{type:Eo("table")},attributes:{Mb:mq,Ta:mq}});
__c.sxb=Er.Fi({values:{type:Eo("sheet"),id:Zp},Sb:{config:__c.xrb}}).Fi({computed:{attributes:{width:void 0,height:void 0},Sb:{},create:a=>({attributes:{width:So({get:()=>a.config.width,set:b=>{a.config.width=b}}),height:So({get:()=>a.config.height,set:b=>{a.config.height=b}})},Sb:{}})}});txb=new Aq;uxb=To({attributes:{all:pq,Nc:pq,Fd:pq,Kc:pq,Td:pq}});vxb=kp({layout:txb,rect:__c.Fr,shape:__c.Ywb,text:__c.Hr},a=>a.type,a=>a.type);wxb=Dvb.Fi({values:{type:Eo("element")},Sb:{element:vxb}});
xxb=kp({element:wxb},a=>a.type,a=>a.type);yxb=Po(xxb);zxb=new Aq;Axb=To({values:{type:Eo("string"),value:Zp}});Bxb=To({values:{type:Eo("boolean"),value:Yp}});Cxb=To({values:{type:Eo("double"),value:bq}});Dxb=To({values:{type:Eo("int32"),value:__c.Plb}});__c.Exb=Po(zxb);Fxb=To({values:{type:Eo("dict")},Sb:{value:__c.Exb}});Gxb=Vo(zxb);Hxb=To({values:{type:Eo("list")},Sb:{value:Gxb}});Ixb=To({values:{type:Eo("fill")},Sb:{value:Fq}});Jxb=To({values:{type:Eo("stroke")},Sb:{value:Gq}});
Kxb=To({values:{type:Eo("text2")},Sb:{value:Gr}});Lxb=kp({boolean:Bxb,int32:Dxb,double:Cxb,string:Axb,list:Hxb,dict:Fxb,text2:Kxb,fill:Ixb,stroke:Jxb},a=>a.type,a=>a.type);zxb.Gka(Lxb);__c.Mxb=Er.Fi({values:{type:Eo("layout")},Sb:{padding:uxb,cells:yxb,behavior:Avb,fill:Fq,border:__c.Cvb,Hb:Bvb,Tq:Lo(__c.tnb)},attributes:{direction:Evb,Ta:mq,Mb:mq}});txb.Gka(__c.Mxb);Nxb=kp({line:__c.nxb,rect:__c.Fr,shape:__c.Ywb,text:__c.Hr,embed:__c.cxb},a=>a.type,a=>a.type);__c.Oxb=Vo(Nxb);
__c.Ir=Mrb(Er,kvb).Fi({values:{type:Eo("chart"),id:Lo(__c.Lnb)},Sb:{Pc:__c.Oxb,labels:__c.ttb},attributes:{Fp:oq,Ke:__c.Tnb,Mb:mq,Ta:mq,Ng:Mo(__c.Fib(Zp,Zp))},computed:{Sb:{ooc:void 0},attributes:{top:void 0,left:void 0,width:void 0,height:void 0,Ta:void 0,Mb:void 0,Ke:void 0},create:a=>{function b(u,w){return So({get:()=>{const x=q.get();return x?u.value+w(x):u.value},set:x=>{const z=q.get();u.value=z?x-w(z):x}})}function c(){const u=p.padding;return(g.value-u.left-u.right)/k.value}function d(){const u=
p.padding;return(h.value-u.top-u.bottom)/l.value}const e=a.top,f=a.left,g=a.width,h=a.height,k=a.Ta,l=a.Mb,n=a.Ke,p=a.style,q=Nsb.box();return{Sb:{ooc:q},attributes:{top:b(e,u=>-u.top*d()),left:b(f,u=>-u.left*c()),width:b(g,u=>(u.left+u.right)*c()),height:b(h,u=>(u.top+u.bottom)*d()),Ta:b(k,u=>u.left+u.right),Mb:b(l,u=>u.top+u.bottom),Ke:So({get:()=>{const u=q.get();return u?{width:n.value.width,height:n.value.height,top:n.value.top+u.top,left:n.value.left+u.left}:n.value},set:u=>{const w=q.get();
n.value=w?{width:u.width,height:u.height,top:u.top-w.top,left:u.left-w.left}:u}})}}}}});__c.Pxb=new ltb;Qxb=new Aq;Rxb=kp({group:Qxb,layout:__c.Mxb,chart:__c.Ir,grid:__c.oxb,table:__c.rxb,sheet:__c.sxb,line:__c.nxb,rect:__c.Fr,shape:__c.Ywb,text:__c.Hr,embed:__c.cxb},a=>a.type,a=>a.type);__c.Jr=Vo(Rxb);
__c.Sxb=Er.Fi({values:{type:Eo("group"),Ina:Eo("space","time")},Sb:{Tq:Lo(__c.tnb),Ay:__c.Exb,Pc:__c.Jr},attributes:{Mb:mq,Ta:mq},computed:{attributes:{},Sb:{Ay:void 0,Pc:void 0},create:a=>{const b=a.Tq;if(!b)return{attributes:{},Sb:{Ay:a.Ay,Pc:a.Pc}};const c=Nsb.box(a.Pc);let d;const e=Osb(()=>{const f=b&&__c.Pxb.get(b.app.id);return f?{oGd:f,Tq:b}:void 0},f=>{if(f){const g=f.oGd,h=f.Tq;f=jr(()=>h.oY,{set:n=>h.oY=n});const {Pc:k,Jca:l}=g.uga({oY:f,Ay:a.Ay});d=l;c.set(new __c.vq(k))}else d===null||
d===void 0||d(),d=void 0,c.set(a.Pc)},{fireImmediately:!0});return{attributes:{},Sb:{Ay:a.Ay,Pc:Trb(c)},Jca:()=>{e();d===null||d===void 0||d()}}}}});Qxb.Gka(__c.Sxb);__c.Txb=kp({group:__c.Sxb,chart:__c.Ir,grid:__c.oxb,layout:__c.Mxb,table:__c.rxb,sheet:__c.sxb,line:__c.nxb,rect:__c.Fr,shape:__c.Ywb,text:__c.Hr,embed:__c.cxb},a=>a.type,a=>a.type);__c.Uxb=Vo(__c.Txb);Vxb=Go({mc:Lo(new psb),top:bq,left:bq,aa:__c.xnb,rotation:__c.ynb,locked:Yp});var Wxb,Xxb,Yxb,Zxb,$xb,ayb,byb,cyb,dyb,eyb,fyb,gyb,iyb,jyb,kyb,lyb,myb,nyb,oyb,pyb,qyb,Lr,ryb,syb,tyb,uyb,vyb,wyb,xyb,yyb,zyb,Ayb,Byb,Dyb,Eyb,Fyb,Gyb,Hyb,Iyb,Jyb,Kyb,Lyb,Myb,Nyb,Oyb,Pyb,Qyb,Jsb,Ryb,Syb,Uyb;Wxb=new Aq;Xxb=Eo(1,3,2,4);Yxb=__c.Do(a=>a===-1||cq.NP(a));Zxb=Go({width:Yxb,height:Yxb,units:Xxb},a=>a.width===-1===(a.height===-1));$xb=Mo(Zxb);ayb=To({attributes:{rotation:Oo(__c.ynb)}});byb=Po(ayb);cyb=Go({type:Eo("reference"),Ub:Zp,YR:$p,mP:gq});dyb=Go({type:Eo("inline"),mP:gq});
eyb=Ho({reference:cyb,inline:dyb},a=>a.type);fyb=Go({id:Zp,version:$p,Rk:Xlb});gyb=To({values:{id:gq},Sb:{audio:Usb,transition:rwb,Av:__c.Hnb},attributes:{$e:Oo(eyb),title:oq,Dca:oq,we:jq,locked:jq,WI:Oo(Twb),KB:jq,fb:qq,anchor:oq}});__c.Kr=gyb.Fi({values:{type:Eo("fixed")},Sb:{background:Fq,qx:__c.jtb,elements:__c.Uxb,Yk:byb,sheet:Lo(__c.Brb)},attributes:{animation:__c.emb,Wo:Oo(Zsb),zl:nq,dimensions:Oo(Zxb),template:Oo(fyb)}});__c.hyb=Vo(__c.Kr);iyb=Po(__c.mnb);
jyb=gyb.Fi({values:{type:Eo("concatenated-fixed")},Sb:{pages:__c.hyb,Yk:iyb},attributes:{direction:Mo(Eo("vertical"))}});kyb=Go({type:Eo("reference"),id:Zp,version:$p});lyb=Go({type:Eo("inline"),width:Yxb,height:Yxb,units:Xxb,We:Xlb,le:Xlb,pLb:Xlb,MKb:Xlb},a=>{if(a.width===-1!==(a.height===-1))return!1;const b=a.pLb!=null||a.MKb!=null;if((a.We!=null||a.le!=null)&&b)return!1;var c,d;return((c=a.pLb)!==null&&c!==void 0?c:0)<=((d=a.MKb)!==null&&d!==void 0?d:Infinity)});
myb=Mo(Ho({inline:lyb,reference:kyb},a=>a.type));
nyb=Go({"font-weight":Lo(Eo(...swb)),"font-style":Lo(Eo(...twb)),"font-size-modifier":Lo(Io(__c.olb)),"vertical-align":Lo(Io(__c.qlb)),color:Lo(Io(__c.llb)),decoration:Lo(Eo(...ywb)),strikethrough:Lo(Eo(...zwb)),"font-family":Lo(Io(Awb)),"font-size":hq,"font-kerning":Lo(Eo(...uwb)),"font-feature-liga":Lo(Eo(...vwb)),"font-feature-clig":Lo(Eo(...wwb)),"font-feature-calt":Lo(Eo(...xwb)),leading:hq,spacing:hq,direction:Lo(Eo(...Bwb)),tracking:hq,"text-transform":Lo(Eo(...Cwb)),"text-align":Lo(Eo(...Dwb)),
"head-indent":hq,"list-marker":Lo(Eo(...Ewb)),"list-level":Lo(__c.Plb)});oyb=Go({attributes:nyb,jb:Zp});pyb=Go({text:oyb,Ccb:Vxb});qyb=Io(/^[0-9]+(\.[0-9]+)?(%|px|cqw)$/);Lr=To({attributes:{display:Oo(Eo(1,2)),width:Mo(qyb),minWidth:Oo(__c.Enb),maxWidth:Oo(qyb),Sza:Oo(__c.Gnb),alignment:Oo(__c.Fnb),altText:Oo(__c.Onb)}});ryb=Lr.Fi({values:{type:Eo("rect")},Sb:{fill:Fq,stroke:No(Lo(Gq))},attributes:{Ta:qq,Mb:qq,Hb:cmb}});syb=Lr.Fi(Tvb).Fi({values:{type:Eo("shape")}});
tyb=Lr.Fi({values:{type:Eo("separator")},Sb:{stroke:Gq}});uyb=Lr.Fi({values:{type:Eo("embed"),url:Zp},attributes:{Ta:mq,Mb:mq}});vyb=Lr.Fi({values:{type:Eo("pill")},Sb:{uh:__c.Lrb}});wyb=To({attributes:{fontFamily:Oo(Io(__c.Nob)),fontSize:Oo(bq),fontWeight:Oo(Eo(...__c.Mob)),fontStyle:Oo(Eo(...__c.Oob)),color:Oo(Cq),Xn:Oo(Eo(...__c.Pob))}});xyb=Mrb(Lr,kvb).Fi({values:{type:Eo("chart"),id:Lo(__c.Mnb)},Sb:{Ng:wyb}});yyb=Io(/^[0-9]+(\.[0-9]+)?cqh$/);zyb=To({values:{type:Eo("sticky-scroll")},attributes:{JRb:Mo(yyb)}});
Ayb=To({values:{type:Eo("viewport-scroll")},attributes:{YTb:kq,XCb:kq}});Byb=kp({"sticky-scroll":zyb,"viewport-scroll":Ayb},a=>a.type,a=>a.type);__c.Cyb=Lr.Fi({values:{type:Eo("design")},Sb:{pages:__c.hyb,stroke:No(Lo(Gq)),ida:No(Lo(Byb))},attributes:{height:Oo(yyb),doctype:myb,dimensions:$xb,Hb:cmb}});Dyb=To({attributes:{Nc:kq,Fd:kq}});Eyb=Dvb.Fi({values:{type:Eo("text")},Sb:{text:Wxb}});Fyb=kp({text:Eyb},a=>a.type,a=>a.type);Gyb=Po(Fyb);Hyb=Io(/^100%|100cqw|[0-9]+(\.[0-9]+)?px$/);Iyb=Io(/^100(%|cqw)$/);
Jyb=Lr.Fi({values:{type:Eo("layout")},Sb:{padding:Dyb,cells:Gyb,behavior:Avb,fill:Fq,border:__c.Cvb,Hb:Bvb,Tq:Lo(__c.tnb)},attributes:{Ta:Mo(Hyb),fHa:Oo(__c.Enb),dHa:Oo(Iyb),eHa:Oo(__c.Gnb),direction:Evb}});Kyb=To({Sb:{text:Wxb}});Lyb=ewb(Kyb);Myb=Mrb(Lr,To({Sb:{cells:Po(Lyb),layout:gwb}})).Fi({values:{type:Eo("table")},attributes:{Ta:Oo(__c.Gnb)}});
Nyb=Lr.Fi({values:{type:Eo("sheet"),id:Zp},Sb:{config:__c.zrb}}).Fi({computed:{attributes:{Ta:void 0,Mb:void 0},Sb:{},create:a=>({attributes:{Ta:So({get:()=>a.config.width,set:b=>{a.config.width=b}}),Mb:So({get:()=>a.config.height,set:b=>{a.config.height=b}})},Sb:{}})}});Oyb=kp({rect:ryb,design:__c.Cyb,layout:Jyb},a=>a.type,a=>a.type);Pyb=To({Sb:{wk:No(Lo(Oyb))}});Qyb=Lr.Fi({values:{type:Eo("page-break")},Sb:{marker:Pyb}});
Jsb=kp({rect:ryb,shape:syb,"page-break":Qyb,separator:tyb,embed:uyb,pill:vyb,chart:xyb,design:__c.Cyb,layout:Jyb,table:Myb,sheet:Nyb},a=>a.type,a=>a.type);__c.Mr=new __c.Ksb;Wxb.Gka(__c.Mr);__c.yqb.Gka(__c.Mr);Ryb=Go({id:Zp,version:$p,V0d:__c.Rlb});Syb=To({Sb:{Kp:Pyb,text:__c.Mr},attributes:{template:Oo(Ryb)}});__c.Tyb=Vo(Syb);Uyb=Po(__c.mnb);__c.Vyb=gyb.Fi({values:{type:Eo("responsive")},Sb:{Kp:Pyb,text:__c.Mr,Yk:Uyb},attributes:{template:Oo(fyb)}});
__c.Nr=kp({fixed:__c.Kr,"concatenated-fixed":jyb,responsive:__c.Vyb},a=>a.type,a=>a.type);__c.Wyb=Vo(__c.Nr);var Xyb,Zyb,$yb,azb,bzb,czb,dzb,ezb,fzb;Xyb=To({values:{direction:Eo(1,2)},attributes:{position:kq,locked:jq}});__c.Yyb=Vo(Xyb);Zyb=Go({type:Eo("text","image","chart"),name:Zp});$yb=Go({fields:__c.Fib(Zp,Zyb)});azb=To({Sb:{attributes:__c.Hnb}});__c.Or=Po(azb);bzb=To({values:{userId:Zp,timestamp:__c.aq},attributes:{mga:oq}});czb=Po(bzb);dzb=To({attributes:{doctype:myb,dimensions:$xb,language:oq,title:oq,INa:Oo(pyb)},Sb:{rea:czb,Yw:__c.Or}});
ezb=dzb.Fi({values:{Lm:Eo("fixed")},attributes:{description:oq,Ic:nq,DVa:Oo($yb)},Sb:{HG:__c.Yyb,audio:Usb,Za:rwb,hb:rwb,pages:__c.Wyb}});fzb=dzb.Fi({values:{Lm:Eo("responsive")},Sb:{rw:__c.Tyb}});__c.gzb=kp({fixed:ezb,responsive:fzb},a=>a.Lm,a=>a.Lm);
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/2bea61cc9fa2a99e.js.map