(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[88999],{

/***/ 201099:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(568954);__web_req__(993605);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var R=__c.R;var Q=__c.Q;var y=__c.y;var gi=__c.gi;var P=__c.P;var F=__c.F;var wg=__c.wg;var qKe,rKe,tKe,vKe,wKe,xKe;__c.pKe=function(a={}){return __c.xg(wg(wg(wg(__c.tg(wg(wg(wg(__c.ug("/design/play"),"type",a.Ub),"category",a.Ea),"template",a.Cg),a.dimensions&&{width:a.dimensions.width,height:a.dimensions.height,units:a.dimensions.units&&__c.EBa(a.dimensions.units)}),"locale",a.locale),"ui",a.Qa),"layoutQuery",a.qfd))};
qKe=function(a){switch(a){case 1:return 1;case 2:return 2;case 3:return 3;case 4:return 4;default:throw new __c.r(a);}};rKe=function(a){switch(a){case 1:return 1;case 3:return 3;case 2:return 2;default:throw new __c.r(a);}};
__c.BH=function(a){const b=a.id;var c=a.ew,d=a.jP,e=a.HHa;const f=a.cia,g=a.BVa,h=a.msa,k=a.width,l=a.height,n=a.Io,p=a.jWa;var q=a.yc;const u=a.TG,w=a.rD;var x=a.Ns;const z=a.contentType,B=a.status;var C=a.filters;const E=a.accessToken;var H=a.title;a=a.Ws.map(I=>new __c.Rfc({...I,container:qKe(I.container),url:__c.m(I.url)}));d=d.map(I=>new __c.Ufc({...I,container:qKe(I.container),url:__c.m(I.url)}));e=e.map(I=>new __c.Vfc({...I,url:__c.m(I.url)}));x=x.map(I=>new __c.Wfc({$c:I.q8e,url:__c.m(I.url)}));
c=c===null||c===void 0?void 0:c.source;C=C.map(rKe);a:switch(q){case 2:q=2;break a;case 3:q=3;break a;case 1:q=1;break a;default:throw new __c.r(q);}return new __c.agc({id:b,title:H,files:a,jP:d,HHa:e,cia:f,BVa:g,msa:h,width:k,height:l,rA:n||p,Ns:x,Gtb:w,contentType:z,source:c,KJ:B,modifiers:C,yc:q,Qfd:(u===null||u===void 0?void 0:u.type)==="STANDARD"&&b!==u.videoId?u.videoId:void 0,accessToken:E})};__c.sKe=F(()=>({zmc:P(1),Hh:P(2)}));tKe=__c.G(()=>[1,2,3,4]);__c.uKe=F(()=>({status:__c.D(1,tKe)}));
vKe=F(()=>({Xlg:P(1)}));wKe=F(()=>({Gga:gi(1),QPb:gi(2),yLb:gi(4),Vqa:gi(8),$Wb:gi(5),YOa:gi(6),PVa:gi(7)}));xKe=F(()=>({userId:P(1),xa:P(2)}));var yKe=F(()=>({$t:P("schema",1,"web-2"),content:__c.v("content",2,__c.Et)}));var zKe=F(()=>({JYd:P(1),IYd:P(2)}));var AKe=F(()=>({source:P(1),location:P(2),mode:P(3)}));__c.BKe=F(()=>({credentials:__c.v(1,__c.cn),cjb:y(19,xKe),ZR:y(2,yKe),pfe:Q(7),dg:Q(10),Xwa:Q(11),state:Q(3),UTb:Q(4),vAa:Q(14),$4d:Q(5),Bpc:R(6),bGf:Q(8),yGf:Q(9),Ucg:y(12,zKe),Af:y(13,__c.In),o6e:R(15),headers:(0,__c.ki)(16),QW:__c.Ca(17,__c.z6a),Uy:y(20,AKe),HTa:Q(21)}));var CKe=F(()=>({token:P(1),D9f:Q(2)}));var DKe=F(()=>({JYd:P(1),IYd:P(2)}));__c.EKe=F(()=>({locale:Q("locale",2),displayName:Q("displayName",4),kP:__c.ci("dateOfBirth",35),credentials:__c.v("credentials",6,__c.cn),dHf:y("childAccount",37,vKe),Vyg:Q("selfSignupToken",7),Ef:Q("analyticsId",8),H8f:Q("initialDesignType",9),MAf:Q("apiBrandId",10),referrer:Q("referrer",11),QG:Q("journey",13),qVc:Q("brandAccessToken",14),C9f:y("invitation",31,CKe),Wbf:__c.Da("userActions",23,__c.tn),oeg:gi("marketingEmailConsent",16),ctg:Q("referrerCode",18),$4d:Q("clickId",20),sE:__c.Ca("productVariant",
21,__c.vgc),dg:Q("documentId",29),Xwa:Q("documentExtension",30),ZR:y("documentContent",17,yKe),pfe:Q("documentCategory",24),$ka:R("supportErrorResponse",19),Bpc:R("mintAtt",22),PAg:y("signupMedia",32,DKe),Af:y("riskContext",33,__c.In),exc:y("privacyPreferences",34,wKe),h8f:R("includeEncryptedNextSteps",36),headers:(0,__c.ki)("headers",38),QW:__c.Ca("productSuite",39,__c.z6a),HTa:Q("authnState",40)}));__c.FKe=F(()=>({$t:__c.Ca("schema",1,__c.V2a),openSession:R("openSession",2),rg:Q("analyticsCorrelationId",6),body:y("body",3,__c.Et),EXe:__c.fi("resourceOrigins",7),template:P("template",4,'"-"'),duplicate:P("duplicate",5,'"-"'),type:Q("type",8),dimensions:Q("dimensions",9)}));
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/4fa9b4829e324830.js.map