(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[45262],{

/***/ 78349:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(728027);__web_req__(437917);__web_req__(279380);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var hd=__c.hd;var L=__c.L;var od=__c.od;var Oi=__c.Oi;var rcf,xcf,ycf,Acf,Lcf,Mcf,Ncf,Pcf,Scf,Tcf,Ucf,Xcf,Ycf,Zcf,$cf,tcf,SK,RK;__c.qcf=function(a,b){var c;(c=a.observer)===null||c===void 0||c.disconnect();a.observer=new IntersectionObserver(a.Xaf,{threshold:.7,...b});a.init()};
rcf=function(a){const b=a.L.Kf("subpage_first_meaningful_paint",a.fja);a.A5e=b;const c=a.fja;let d=!1,e=!1;return{Wua:f=>{(0,__c.fb)(()=>{d||(b.sV(),d=!0)},[]);return f.children},Xua:f=>{(0,__c.fb)(()=>{d||(b.sV(),d=!0);e||(c.sV(),a.JFa.mj()&&a.JFa.sV(),e=!0)},[]);return f.children}}};__c.scf=function(){const a=(0,__c.Na)(__c.hsa).current,[{Wua:b,Xua:c}]=(0,__c.cb)(()=>a?rcf(a):{Wua:({children:d})=>d,Xua:({children:d})=>d});return{Wua:b,Xua:c}};
__c.ucf=function(a){const b=__c.wc({default:"content",ye:"2/4",El:"2/5"}),c=RK(__c.PK,{name:void 0,wB:"small",Wk:"none",expand:a.NF?"none":"medium",children:[a.j5a,a.rkd,a.yec&&SK("div",{className:"_5s8Tvw",children:a.yec}),a.xec&&SK("div",{className:"il6_JA",children:a.xec}),a.wsa&&a.wsa]});return SK(__c.If,{wb:"NAVIGATION_FLYOUT",children:RK(__c.we,{spacing:{default:"2u",ye:"3u"},yg:"center",children:[a.NF&&RK(tcf,{children:[SK(Oi,{width:b,children:a.NF}),SK(Oi,{width:"content",children:SK(od,{className:"_3TWzTA",
children:SK(__c.vf,{direction:"vertical"})})})]}),SK(Oi,{width:"fluid",children:c})]})})};__c.wcf=function({EJ:a,KSa:b,G:c,qa:d,up:e,NF:f}){const {cvb:g}=__c.dva({G:c,qa:d,up:e});return{HOc:vcf(({jy:h,Mo:k,Rn:l,Cte:n,D$c:p,j5a:q})=>{h=(h===null||h===void 0?0:h.tags.length)?SK(b,{jy:h,KDa:!1}):void 0;k=p&&k?SK(g,{Mo:k,Rn:l}):void 0;l=n&&a?SK(a.Wub,{}):void 0;n=n&&a?SK(a.Lua,{}):void 0;return SK(__c.ucf,{yec:l,xec:n,wsa:h,rkd:k,j5a:q,NF:f})})}};
xcf=function(a){switch(a){case "af-ZA":return L("GP3tGg");case "ar":return L("9fpz9Q");case "ar-AE":return L("bUQscQ");case "ar-EG":return L("Su/pSw");case "ar-SA":return L("pooITA");case "as-IN":return L("M5ei6g");case "az-AZ":return L("3Spbxg");case "bg-BG":return L("fTUpwg");case "bn-BD":return L("MZctSg");case "ca-ES":return L("Qw2UXA");case "ceb-PH":return L("SjodfQ");case "cs-CZ":return L("4aYRyA");case "cy-GB":return L("YxnMsw");case "da-DK":return L("olqOfw");case "de-DE":return L("0T9plw");
case "el-GR":return L("mE0o0w");case "en":return L("M+GdZQ");case "en-AU":return L("KVhL6Q");case "en-GB":return L("hUQ5nA");case "en-IN":return L("OTF4KA");case "en-PH":return L("EYENAw");case "en-psaccent":return L("Q2Ql0Q");case "es-419":return L("MYqFig");case "es-AR":return L("ULJmgA");case "es-CO":return L("I6pCeQ");case "es-ES":return L("d5FbeA");case "es-MX":return L("yreaKg");case "es-US":return L("PPrdsw");case "et-EE":return L("doIGZA");case "eu-ES":return L("R6KWcQ");case "fa-IR":return L("jA/Zig");
case "ff-SN":return L("rMpJFQ");case "fi-FI":return L("Zfzw/A");case "fr-BE":return L("fkz4bg");case "fr-CA":return L("TutTyg");case "fr-FR":return L("IoqwYQ");case "gl-ES":return L("023CgQ");case "gu-IN":return L("9JiLXg");case "ha-NG":return L("dZozAQ");case "he-IL":return L("kCr0uA");case "hi-IN":return L("UE3YQA");case "hr-HR":return L("XWHEtw");case "hu-HU":return L("Y5W5/g");case "hy-AM":return L("RjPsLQ");case "id-ID":return L("qRj64w");case "ig-NG":return L("yO3pfQ");case "it-IT":return L("IXf4zg");
case "ja-Hira":return L("k16iMQ");case "ja-JP":return L("LmRmmw");case "jv-ID":return L("ASQOJA");case "ka-GE":return L("V+saGw");case "kk-KZ":return L("jqW6hA");case "km-KH":return L("I5K6WA");case "kn-IN":return L("CmAKmQ");case "ko-KR":return L("0u9lYA");case "ku-TR":return L("Cs6KxA");case "ky-KG":return L("n6x3xA");case "lt-LT":return L("QoSgoA");case "lv-LV":return L("++vKFg");case "ma-IN":return L("P0NX7w");case "mg-MG":return L("vfde2A");case "mk-MK":return L("qQ1YYw");case "ml-IN":return L("UEsDxw");
case "mn-MN":return L("qcNv8A");case "mr-IN":return L("LhuLjw");case "ms-MY":return L("Lk0c2Q");case "my-MM":return L("Ruzj8w");case "nb-NO":return L("U+f1MA");case "ne-NP":return L("pRfFcw");case "nl-BE":return L("30GaYA");case "nl-NL":return L("89KeWQ");case "om-ET":return L("TMsXrA");case "pa-IN":return L("2onibg");case "pa-PK":return L("Y/LT1g");case "pl-PL":return L("Z82yrA");case "pt-BR":return L("ozO2eQ");case "pt-PT":return L("hqEbuA");case "ro-RO":return L("nZ62Dg");case "ru-RU":return L("4YthYA");
case "sd-IN":return L("fPF25Q");case "si-LK":return L("iY/c9g");case "sk-SK":return L("DPOHVQ");case "sl-SI":return L("J6xMxg");case "sn-ZW":return L("6Tz+6A");case "so-SO":return L("QAcNqw");case "sq-AL":return L("sxQCJQ");case "sr-RS":return L("mLCzcA");case "su-ID":return L("92gBRw");case "sv-SE":return L("9hjzTQ");case "sw-KE":return L("6ww/0w");case "ta-IN":return L("rslDRQ");case "te-IN":return L("ta+dMw");case "th-TH":return L("FTxeDA");case "tl-PH":return L("FzlpeQ");case "tr-TR":return L("nzy6kA");
case "uk-UA":return L("WrsOlg");case "ur-PK":return L("2xYYow");case "uz-UZ":return L("NsinDQ");case "vi-VN":return L("s8RRyg");case "wo-SN":return L("sZh9aQ");case "xh-ZA":return L("Ij2dLA");case "yo-NG":return L("0RzYiQ");case "zh-CN":return L("sqAsDg");case "zh-HK":return L("qHT5bA");case "zh-TW":return L("upLoxA");case "zu-ZA":return L("0owqbw");default:throw Error(`Unknown language code: ${a}`);}};
__c.zcf=function({Link:a,qa:b,Eb:c}){const d=({children:g,href:h,onClick:k})=>SK(__c.lg,{variant:"secondary",href:h,onClick:k,children:g}),e=({tag:g})=>SK(a,{model:g.link,gs:d,children:SK(__c.O,{tone:__c.tf,children:g.text})}),f=({wsa:g,KDa:h})=>{const k=__c.Kf(),l=TK(()=>{var n;const p=ycf(g);b.QB(k,{Am:p});((n=k.component)===null||n===void 0?0:n.wb)&&b.bka({rows:[{Id:k.component,type:k.component.wb,Vn:k.component.Vn,Hya:0}]})},[k,g]);return SK(__c.vk,{Eb:c,Ut:n=>n&&l(),Ev:!0,children:({ref:n})=>
SK("div",{ref:n,children:h?SK(__c.PK,{wB:"small",name:void 0,children:g.map(p=>SK(e,{tag:p},p.text))}):SK(__c.we,{spacing:"1u",children:g.map(p=>SK(Oi,{width:"content",children:SK(e,{tag:p})},p.text))})})})};return{g0b:({jy:g,KDa:h})=>SK(__c.If,{wb:g.Ama,children:SK(f,{wsa:g.tags,KDa:h})})}};ycf=function(a){return a.map(b=>{var c;return((c=b.link.Mt)===null||c===void 0?void 0:c.type)==="CATEGORY"?b.link.Mt.Ea:void 0}).filter(__c.Ta)};
Acf=function({jy:a,Hod:b,zdd:c}){if(a!==null&&a!==void 0&&a.tags.length)return b?"MINIFIED_SIDEBAR":c?"IN_PAGE":"MINIFIED_SIDEBAR"};
__c.Kcf=function({Link:a,pq:b,Co:c,XP:d,EJ:e,qa:f,G:g,Eb:h,Sh:k,xF:l,up:n,l2:p}){const q=Bcf(()=>{const H=__c.wbf()>=2?0:__c.Ccf;return __c.Dcf+H}),u=new __c.Ecf(k,void 0,e,d,q),{g0b:w}=__c.zcf({Link:a,qa:f,Eb:h}),{HOc:x}=__c.wcf({EJ:e,KSa:w,G:g,qa:f,up:n,NF:p}),z=({children:H})=>H,B=__c.Fcf({Link:a}),C=__c.Gcf({Link:a}),E=__c.Hcf({Link:a});return{r0b:Icf(H=>{var I,N,M;const T=__c.wc({default:!((I=H.Qr)===null||I===void 0?0:I.yba),ye:!1});I=__c.wc({default:!1,ye:!0});var U;const V=(U=H.Wua)!==null&&
U!==void 0?U:z;var Y;U=(Y=H.Xua)!==null&&Y!==void 0?Y:z;const Z=b&&((N=H.breadcrumbs)===null||N===void 0?0:N.length)?SK(b,{model:H.breadcrumbs}):void 0;UK(()=>{const xa=u.sMb();return()=>{xa()}});const W=Acf({jy:H.jy,Hod:!!H.I3,zdd:I})==="IN_PAGE"?SK(w,{jy:H.jy,KDa:!0}):void 0,ba=H.A$?SK(V,{children:SK(c,{Vr:!0,yt:H.A$})}):void 0,ca=SK(U,{children:SK(__c.md,{spacing:{default:"2u",Fb:"4u"},children:SK(c,{Vr:!0,yt:H.Dk})})}),na=VK(null),ka=H.d2;UK(()=>{if(ka)return u.Eka(ka,()=>{var xa;return(xa=na.current)===
null||xa===void 0?void 0:xa.scrollIntoView({behavior:"smooth"})}),()=>{u.pJc()}},[ka]);const va=!((M=H.d2)===null||M===void 0||!M.filters.length),oa=T&&(l===null||l===void 0?void 0:l.Rn)&&!(l===null||l===void 0?0:l.JIb),pa=Acf({jy:H.jy,Hod:!!H.I3,zdd:I})==="MINIFIED_SIDEBAR",fa=SK(Jcf,{children:()=>SK("div",{className:"_21ljAg",children:SK("div",{className:"DECAMg",children:SK(x,{jy:pa?H.jy:void 0,Mo:l===null||l===void 0?void 0:l.Mo,Rn:l===null||l===void 0?void 0:l.Rn,Cte:va,D$c:oa,j5a:H.j5a})})})});
N=H.search.aAb;let ra;if(N)switch(N.type){case "SPELLING":M=__c.m(H.search.query,"Search query is expected for spelling correction.");ra=SK(B,{K8b:M,f6a:N.f6a,QDd:N.redirect});break;case "LANGUAGE_CORRECTION":M=__c.m(H.search.i4,"Search language override is expected for language correction.");ra=SK(C,{IZc:__c.WK(M),Ilb:__c.WK(N.Jlb),kod:N.redirect});break;case "LANGUAGE_SUGGESTION":ra=SK(E,{LAd:__c.WK(N.OAd),Ilb:__c.WK(N.Jlb),MAd:N.redirect});break;default:throw new __c.r(N);}return SK(Jcf,{children:()=>
SK(__c.yk,{k7:H.k7,Uh:H.Uh,breadcrumbs:Z,wsa:W,Tjb:oa||va||pa||H.j5a?fa:void 0,j2b:ba,Ixc:ra,$E:ca,fJa:H.fJa})})})}};Lcf=function(){const a=new Map;return{setItem:(b,c)=>{a.set(b,c)},getItem:b=>a.get(b)}};Mcf=function(){const [a]=XK(Lcf);return a};
Ncf=function(a,b){return Array.from(a.querySelectorAll("input:not([disabled]):not([type=hidden]),select:not([disabled]),textarea:not([disabled]),button:not([disabled]),a[href],area[href],summary,iframe,object,embed,audio[controls],video[controls],[contenteditable]")).filter(c=>c instanceof HTMLElement&&!c.hidden&&!c.ariaHidden&&(b===!0?c.tabIndex>=0:!0))};
Pcf=function(a){const b=VK(null),[c,d]=XK([]),e=TK(()=>{if(b.current){var f=Ncf(b.current,a===null||a===void 0?void 0:a.Hnd);d(f)}},[b,a===null||a===void 0?void 0:a.Hnd]);Ocf(()=>{if(b!==null&&b!==void 0&&b.current&&(a===null||a===void 0||!a.disabled)){e();var f=new MutationObserver(e);f.observe(b.current,{subtree:!0,childList:!0,attributes:!0,attributeFilter:["tabIndex","disabled"]});return()=>{f.disconnect()}}},[e,b,a===null||a===void 0?void 0:a.disabled]);return{ref:b,bpa:c}};
Scf=function(){const {ref:a,bpa:b}=Pcf(),c=TK(f=>{__c.Dc.dX("keyboard");(f=f<0?b[b.length-1]:b[f])&&f.focus()},[b]),d=TK(f=>{f=(b.findIndex(g=>g===null||g===void 0?void 0:g.matches(":focus"))+f)%b.length;c(f)},[b,c]);var e=Qcf(()=>[["next",f=>{d(1);f.preventDefault()}],["previous",f=>{d(-1);f.preventDefault()}],["Home",f=>{c(0);f.preventDefault()}],["End",f=>{c(-1);f.preventDefault()}]],[c,d]);({ref:e}=__c.gb(e,{Pl:!1}));return{ref:(0,Rcf["default"])(e,a)}};
Tcf=function(a,b,c){return`${a}-${c}-${b.replace(/\s+/g,"")}`};Ucf=function(a,b){var c;return((c=a.compareDocumentPosition)===null||c===void 0?NaN:c.call(a,b))&Node.DOCUMENT_POSITION_PRECEDING?1:-1};Xcf=function(a){const b=VK(null),c=Vcf(Wcf),d=c===null||c===void 0?void 0:c.IQb,e=c===null||c===void 0?void 0:c.aEd;Ocf(()=>{const f=b.current;if(f)return d===null||d===void 0||d(f),()=>{e===null||e===void 0||e(f)}},[d,e]);Ocf(()=>{c&&a&&b.current&&c.tFa!==b.current&&c.VAc(b.current)},[c,a]);return{ref:b}};
Ycf=function(){const a=Vcf(Wcf);var b,c;return{tFa:(b=a===null||a===void 0?void 0:a.tFa)!==null&&b!==void 0?b:null,VAc:a===null||a===void 0?void 0:a.VAc,Zac:(c=a===null||a===void 0?void 0:a.Zac)!==null&&c!==void 0?c:[],IQb:a===null||a===void 0?void 0:a.IQb,aEd:a===null||a===void 0?void 0:a.IQb,E7:a===null||a===void 0?void 0:a.E7,BSb:a===null||a===void 0?void 0:a.BSb}};Zcf=function(a,b){a.scrollLeft+=b.offsetLeft+b.offsetWidth-(a.scrollLeft+a.offsetWidth)+(a.offsetWidth-b.offsetWidth)/2};$cf=__webpack_require__(443763);
tcf=$cf.Fragment;SK=$cf.jsx;RK=$cf.jsxs;var adf=__webpack_require__(214645),vcf=adf.Pi,Jcf=adf.Qj;var YK=__webpack_require__(875604),bdf=YK.Component,cdf=YK.createContext,ddf=YK.createRef,Icf=YK.memo,TK=YK.useCallback,Vcf=YK.useContext,UK=YK.useEffect,edf=YK.useId,Ocf=YK.useLayoutEffect,Qcf=YK.useMemo,VK=YK.useRef,XK=YK.useState;var fdf=__webpack_require__(519427),ZK=fdf.action,Bcf=fdf.computed,gdf=fdf.observable,hdf=fdf.reaction;var idf=__webpack_require__,jdf=idf(993864),bL=idf.n_x(jdf)();var Rcf=__webpack_require__(358579);var kdf=__webpack_require__(361443);var ldf=__webpack_require__(489212);var mdf=__webpack_require__(46239).__decorate;var ndf,odf;ndf=(a,b)=>{const c=new __c.sy;__c.ry(c,"a",(d,e)=>b(a,e));return c};odf=({Eg:a,...b})=>{let c;switch(b.mode){case "spelling":c=b.QDd;b=__c.K("8v3crQ",[b.K8b,b.f6a]);break;case "language-correction":c=b.kod;b=__c.K("y2LGXw",[b.Ilb]);break;case "language-suggestion":c=b.MAd;b=__c.K("iDDKFQ",[b.LAd]);break;default:throw Error("Unhandled query correction mode.");}a=ndf(c,a);return SK(__c.O,{size:"large",children:a.render(b)})};
__c.Fcf=({Link:a})=>b=>SK(odf,{mode:"spelling",...b,Eg:(c,d)=>SK(a,{model:c,gs:e=>SK(__c.Oc,{...e}),children:d})});__c.Gcf=({Link:a})=>b=>SK(odf,{mode:"language-correction",...b,Eg:(c,d)=>SK(a,{model:c,gs:e=>SK(__c.Oc,{...e}),children:d})});__c.Hcf=({Link:a})=>b=>SK(odf,{mode:"language-suggestion",...b,Eg:(c,d)=>SK(a,{model:c,gs:e=>SK(__c.Oc,{...e}),children:d})});__c.WK=a=>xcf(a).replace(/\(.+?\)/g,"").trim();__c.Ecf=class{static F(a){__c.hb(a,{Eka:ZK,pJc:ZK})}Eka(a,b){this.XP({jL:a,AAa:b})}pJc(){var a,b;(a=(b=this.EJ).Twd)===null||a===void 0||a.call(b,{jL:void 0,YX:void 0,AAa:void 0})}sMb(){const a=hdf(()=>this.Vic.get(),ZK(b=>{var c;__c.qcf(this.Sh,{rootMargin:`-${b}px 0px 0px`});(c=this.$Jb)===null||c===void 0||c.call(this).then(d=>__c.qcf(d,{rootMargin:`-${b}px 0px 0px`}))}),{fireImmediately:!0});return()=>{var b;a();this.Sh.dispose();(b=this.$Jb)===null||b===void 0||b.call(this).then(c=>c.dispose())}}constructor(a,
b,c,d,e){this.Sh=a;this.$Jb=b;this.EJ=c;this.XP=d;this.Vic=e;__c.Ecf.F(this)}};__c.Dcf=parseInt("72px",10)||0;__c.Ccf=parseInt("48px",10)||0;__c.pdf=()=>SK("div",{className:"_9rqthw",children:SK(__c.ce,{shape:"rectangle"})});__c.qdf=({Rgd:a,e8c:b,Dba:c})=>RK(__c.md,{spacing:"3u",children:[SK(od,{width:"full",className:bL("_7S1qGQ",c&&"_1Wc3g"),children:a}),SK(od,{className:"_5d4Lfw",padding:{default:"2u",Fb:"0"},children:b})]});var rdf,sdf;rdf=__c.qd*20;sdf=Icf(()=>SK(__c.Aj,{ratio:4/3,children:SK(__c.ce,{shape:"rectangle"})}));__c.tdf=({Dba:a})=>SK(__c.qdf,{Rgd:SK(sdf,{}),e8c:SK(__c.PK,{name:"",Wk:"none",bG:{Q7:rdf},children:[...Array(6).keys()].map(b=>SK("div",{style:{width:`${rdf}px`},children:SK(sdf,{})},b))}),Dba:a});var xdf,udf,ydf,Wcf,zdf;
__c.vdf=({id:a,active:b,onClick:c,Og:d})=>{var e=Vcf(udf);const f=!e||b!=null,g=f?b:e.D2b===a,h=e===null||e===void 0?void 0:e.gWe,k=e===null||e===void 0?void 0:e.Q$e,l=e===null||e===void 0?void 0:e.npb;b=e?Tcf(e.OUb,a,"tab"):a;const n=g?void 0:-1;d=e&&e.H6e.includes(a)?Tcf(e.OUb,a,"tabpanel"):d;UK(()=>{if(!f)return h===null||h===void 0||h(a),()=>{k===null||k===void 0||k(a)}},[f,h,k,a]);const p=TK(()=>{g||(c===null||c===void 0||c(a),f||l===null||l===void 0||l(a))},[f,g,l,a,c]);e=TK(()=>{p()},[p]);
return{active:g,id:b,role:"tab",Og:d,tabIndex:n,onClick:p,onFocus:e}};__c.wdf=()=>{const {ref:a}=Scf();return{ref:a,role:"tablist"}};
xdf=({id:a,active:b,wc:c,children:d,oZc:e="lazy"})=>{const f=Vcf(udf),{ref:g,bpa:h}=Pcf({Hnd:!0}),k=!f||b!=null;b=k?b:f.D2b===a;const l=f===null||f===void 0?void 0:f.hWe,n=f===null||f===void 0?void 0:f.R$e,p=f?Tcf(f.OUb,a,"tabpanel"):a;c=f&&f.kDa.includes(a)?Tcf(f.OUb,a,"tab"):c;UK(()=>{if(!k)return l===null||l===void 0||l(a),()=>{n===null||n===void 0||n(a)}},[k,l,n,a]);const {setItem:q,getItem:u}=Mcf();e==="lazy"?(b&&q(a,d),d=u(a)):e!=="always-remount"||b||(d=null);return{ref:g,active:b,id:p,role:"tabpanel",
wc:c,tabIndex:b?h.length>0?void 0:0:-1,children:d}};udf=cdf(null);
ydf=({D2b:a,L0c:b,onSelect:c})=>{const d=edf(),[e,f]=__c.be({value:a,defaultValue:b}),[g,h]=XK([]),[k,l]=XK([]);a=hd(u=>{h(w=>[...w,u])});b=hd(u=>{h(w=>w.filter(x=>x!==u))});const n=hd(u=>{l(w=>[...w,u])}),p=hd(u=>{l(w=>w.filter(x=>x!==u))});UK(()=>{(!e||g.length>0&&!g.includes(e))&&f(g[0])},[e,f,g]);const q=VK(e);UK(()=>{e!=null&&e!==q.current&&(c===null||c===void 0||c(e,q.current),q.current=e)},[e,c]);return{OUb:d,D2b:e,npb:f,kDa:g,H6e:k,gWe:a,Q$e:b,hWe:n,R$e:p}};Wcf=cdf(null);
zdf=({children:a})=>{const [b,c]=XK(null),[d,e]=XK([]),[f,g]=XK(!1),h=hd(l=>{e(n=>[...n,l].sort(Ucf))}),k=hd(l=>{e(n=>n.filter(p=>p!==l))});return SK(Wcf.Provider,{value:{Zac:d,IQb:h,aEd:k,tFa:b,VAc:c,E7:f,BSb:g},children:a})};var Adf;Adf=({children:a,...b})=>{b=ydf(b);return SK(udf.Provider,{value:b,children:a})};__c.Bdf=({children:a,height:b="auto",...c})=>SK(Adf,{...c,children:SK("div",{className:bL("zvLDlA",b!=="auto"&&"cZc9AA"),style:{"--8ESoXg":typeof b==="number"?`${b}px`:void 0},children:a})});var Cdf;
__c.Ddf=({id:a,active:b,onClick:c,ld:d,ariaLabel:e=d,Og:f,children:g,start:h,end:k,layout:l="horizontal"})=>{a=__c.vdf({id:a,active:b,onClick:c,Og:f});b=__c.Qa();c=__c.Ic();({ref:f}=Xcf(a.active));g=RK("span",{className:"E_B0Sw",children:[SK("span",{className:"D5YrIA","aria-hidden":!0,children:SK(__c.O,{tagName:"span",className:"DR4pTQ",weight:"bold",children:g})}),SK("span",{className:"_4GI03Q",children:SK(__c.O,{tagName:"span",className:"DR4pTQ",tone:__c.tf,children:g})})]});return SK("div",{className:"_1SQJnw",
children:SK(__c.Le,{Ap:f,ariaLabel:e,ld:d,className:bL("Mg_hUw",b&&"_9VqNLw",a.active&&"uNYqug",c&&"k_q5xQ"),size:"medium",OZ:!0,...a,children:SK("span",{className:"Nb4PHw",style:{"--vBf_uQ":"var(--cQVGYw)"},children:SK(Cdf,{start:h,end:k,layout:l,children:g})})})})};
Cdf=Icf(({children:a,start:b,end:c,layout:d})=>b||c?d==="horizontal"?RK(__c.we,{tagName:"span",yg:"center",spacing:"1u",children:[b&&SK(Oi,{tagName:"span",width:"content",children:b}),SK(Oi,{tagName:"span",children:a}),c&&SK(Oi,{tagName:"span",width:"content",children:c})]}):RK(__c.md,{tagName:"span",spacing:"1u",align:"center",children:[b,a,c]}):a);var Edf,Fdf,Hdf,Gdf;
Edf=({tFa:a,align:b,spacing:c,children:d})=>{const e=VK(null),f=__c.Sa(),[g,h]=XK(),[k,l]=XK(!1),n=VK(0),p=TK(()=>{a&&e.current&&(h({x:(f==="RTL"?a.offsetLeft+a.offsetWidth-e.current.offsetWidth:a.offsetLeft)+"px",width:a.offsetWidth+"px"}),l(n.current!==e.current.offsetWidth),n.current=e.current.offsetWidth)},[a,f,d]);Ocf(()=>{p()},[p,c,b]);UK(()=>{if(e.current){const q=new kdf["default"](p);q.observe(e.current);return()=>q.disconnect()}},[e,p]);UK(()=>{if(a&&e.current){Zcf(e.current,a);const q=
new kdf["default"](p);q.observe(a);return()=>q.disconnect()}},[a,p,k]);return{ref:e,B$e:g,G6d:k}};Fdf=parseInt("300ms",10)||0;
Hdf=({align:a,spacing:b,eGa:c,animate:d,children:e,g6a:f})=>{const {tFa:g,BSb:h}=Ycf(),{ref:k,role:l}=__c.wdf(),{ref:n,B$e:p,G6d:q}=Edf({align:a,spacing:b,tFa:g,children:e}),u=VK(p),w=VK(0);UK(()=>{if(h&&p&&d){var x=u.current;!x||x.x===p.x&&x.width===p.width||(h(!0),clearTimeout(w.current),w.current=setTimeout(()=>{h&&h(!1)},Fdf));u.current=p}},[h,d,p]);return SK(Gdf,{Pee:!!g,spacing:b,eGa:c,children:x=>SK("div",{ref:(0,Rcf["default"])(k,n,x),role:l,className:bL("cdPXSw Z1Thkw",{zbprQQ:d&&!q,hc1JNg:f===
"visible"&&p!==void 0,hVVpNg:a==="center",e6ZyGQ:a==="end",WBv1gQ:a==="stretch"}),style:{"--4N5IuA":p===null||p===void 0?void 0:p.x,"--IuauUQ":p===null||p===void 0?void 0:p.width,"--NskXVw":b?__c.Bi[b]:void 0},children:e})})};
Gdf=Icf(({Pee:a,spacing:b,eGa:c,children:d})=>{let e="0px";e=b==="0"?"0px":b==="1u"?__c.Bi["0.5u"]:__c.Bi["1u"];return SK(__c.dcf,{children:({Kj:f,Tl:g,Tpc:h,Upc:k})=>SK(Jcf,{children:()=>RK("div",{className:bL("GWJNnw",!g.zva&&"OmoEvw",!g.yva&&"ntA3sw",c&&"PznWrA"),style:{"--cQVGYw":e},children:[d(f),a&&RK(tcf,{children:[SK(__c.Le,{Pdb:!0,alignment:"start",ariaHidden:!0,tabIndex:-1,size:"tiny",icon:__c.pj,Vf:"medium",onClick:k,className:bL("p0f1_w",!g.zva&&"ruqCcA")}),SK(__c.Le,{Pdb:!0,alignment:"end",
ariaHidden:!0,tabIndex:-1,size:"tiny",icon:__c.Li,Vf:"medium",onClick:h,className:bL("_0DA3uA",!g.yva&&"ruqCcA")})]})]})})})});__c.Idf=({align:a="start",spacing:b="2u",animate:c=!0,eGa:d=!0,g6a:e="visible",children:f})=>{c=__c.Qa()&&c;return SK(zdf,{children:SK(Hdf,{align:a,spacing:a==="stretch"?"0":b,animate:c,eGa:d,g6a:e,children:f})})};var Jdf;Jdf=parseInt("300ms",10)||0;
__c.Kdf=({children:a,id:b,active:c,animate:d=!0,wc:e,oZc:f="lazy"})=>{const {active:g,ref:h,id:k,role:l,wc:n,tabIndex:p,children:q}=xdf({id:b,active:c,wc:e,children:a,oZc:f});({ref:a}=Xcf(g));const {tFa:u,Zac:w,BSb:x}=Ycf();d=__c.Qa()&&u&&d;c=h.current?w.indexOf(h.current):-1;e=u?w.indexOf(u):-1;b=c>e;c=c<e;e=TK(()=>{x&&x(!0)},[x]);f=TK(()=>{x&&x(!1)},[x]);return SK(ldf["default"],{in:g&&!!d,timeout:Jdf,classNames:{enterActive:"RC_ePA"},nodeRef:h,onEnter:e,onEntered:f,children:SK("div",{ref:(0,Rcf["default"])(h,
a),id:k,role:l,"aria-labelledby":n,tabIndex:p,className:bL("huiuBw",g&&"Xi1owQ",d&&"_VyunA",d&&b&&"LFTuaQ",d&&c&&"NXNXww"),children:q})})};var Ldf;__c.Mdf=({children:a})=>SK(zdf,{children:SK(Ldf,{children:a})});Ldf=({children:a})=>{const b=VK(null),{E7:c}=Ycf();return SK("div",{ref:b,className:bL("rhfZhA",c&&"zJBxUg"),children:a})};__c.cL=class extends bdf{static F(a){__c.hb(a,{index:gdf.ref,HZa:Bcf})}get HZa(){const a=this.props.rtl==null?__c.He.direction===2:this.props.rtl;return[["ArrowLeft",a?this.Lld:this.Kld],["ArrowRight",a?this.Kld:this.Lld]]}componentDidMount(){__c.lb(this,hdf(()=>this.index,a=>{this.KT.current&&this.KT.current.Zza(a);this.props.jNa&&this.props.jNa(a)},{fireImmediately:!0}))}render(){const a=this.props.pages,b=this.props.O3d;return a.length===0||a.length===1?SK(this.fvb,{}):SK(__c.pi,{map:this.HZa,
Pl:!1,children:({ref:c})=>SK(Jcf,{children:()=>RK("div",{className:"QoDtFA",ref:c,tabIndex:-1,children:[SK(this.fvb,{}),SK(od,{paddingTop:{default:"2u",Fb:"4u"},rh:{default:"2u",Fb:"0"},display:"flex",justifyContent:"center",children:SK(Ndf,{KT:this.KT,bG:b,children:a.map((d,e)=>SK(__c.Ij,{onClick:()=>this.$Me(e),oz:__c.K("AjPIxg",[e+1]),qCa:"primary",selected:this.index===e,Oa:SK(__c.Gj,{children:d}),layout:"vertical",Zsa:"thumbnail"},e))})})]})})})}constructor(...a){super(...a);this.index=(__c.cL.F(this),
this.props.index||0);this.KT=ddf();this.$Me=ZK(b=>this.index=b);this.Lld=ZK(b=>{b.stopPropagation();b.preventDefault();this.index=Math.min(this.index+1,this.props.pages.length-1)});this.Kld=ZK(b=>{b.stopPropagation();b.preventDefault();this.index=Math.max(this.index-1,0)});this.fvb=()=>{const {kb:b,Sqd:c="center"}=this.props;return SK(od,{display:"flex",justifyContent:"center",children:SK(__c.d$b,{borderRadius:"baseUnit",width:c==="fill"?"full":void 0,children:b})})}}};__c.cL=mdf([__c.qb],__c.cL);
var Ndf=({KT:a,bG:b,children:c})=>{const d=__c.wc({default:!0,Fb:!1});return SK(__c.PK,{name:void 0,KT:a,expand:d?"medium":void 0,wB:d?"small":"medium",Wk:"circular",kna:d?20:0,bG:b,children:c})};
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/742c2627a33170e7.js.map