(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[92627],{

/***/ 761181:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(436066);__web_req__(382925);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var L=__c.L;var hb=__c.hb;var NYf,TYf,PYf,XYf,YYf,GQ,ZYf;NYf=function(a,b,c){if(a.$k!=null&&(b=a.$k.Oha(b))){var d;b.ZY!==void 0&&(d=c?b.ZY+1:b.ZY-1);a.$k.Qja(new __c.sg({Iy:[{...b,zA:c,ZY:d}]}))}};TYf=function({P5d:a,M:b,fV:c,dNb:d}){const e=new OYf(new PYf,a.qN),f=async()=>{d===null||d===void 0||d(a);await c(a.qN);b.SF(e,__c.K("n7TWzA",[a.qN]),2E3)},g=()=>{b.SF(e,a.qN)},h=()=>{b.Nx(e)},k=QYf(()=>GQ(RYf,{J5a:e.J5a,label:e.label,onClick:f,onEnter:g,Lca:h}));return()=>GQ(SYf,{color:a.qN,zUd:k})};
__c.WYf=function({jYc:a,Y3c:b,dNb:c}){let d;if(b){const e=new UYf,f=__c.gf();d=a.map(g=>TYf({P5d:g,M:e,fV:f,dNb:c}))}else d=a.map(e=>()=>GQ(SYf,{color:e.qN}));return()=>GQ(VYf,{R5d:d})};PYf=class{constructor(){({open:a=!1}={});var a;hb(this,{open:__c.Yb.ref});this.open=void 0;this.ov=0;this.open=a}};XYf=__webpack_require__(443763);YYf=XYf.Fragment;GQ=XYf.jsx;ZYf=XYf.jsxs;var $Yf=__webpack_require__(519427),HQ=$Yf.action,aZf=$Yf.observable,bZf=$Yf.runInAction;var cZf=__webpack_require__(875604),dZf=cZf.forwardRef,eZf=cZf.memo,fZf=cZf.useEffect,gZf=cZf.useRef;var hZf=__webpack_require__,iZf=hZf(993864),jZf=hZf.n_x(iZf)();var kZf=__webpack_require__(214645),QYf=kZf.Pi,lZf=kZf.fv;var mZf=__webpack_require__(358579);__c.nZf=class{static F(a){hb(a,{brand:aZf.ref,zA:aZf.ref,T6:aZf.ref,state:aZf.ref})}get CVc(){var a;return(a=__c.dg(this.Zg,this.displayName))!==null&&a!==void 0?a:{content:GQ(__c.kj,{mC:this.brand,name:this.displayName})}}constructor(a,b,c,d,e){this.Zg=d;this.displayName=e;this.brand=(__c.nZf.F(this),void 0);this.state="idle";this.brand=a;this.zA=b;this.T6=c}};
__c.oZf=class{static F(a){hb(a,{toggle:HQ})}async toggle(a,b,c){a.state!=="loading"&&(a.state="loading",a.zA?await this.bR(a,b,c):await this.Kx(a,b,c))}Kx(a,b,c){a.zA=!0;a.T6++;return this.uHa(a.brand).catch(()=>{bZf(()=>{a.zA=!1;a.T6--});__c.Jg(this.$b,{Gl:L("jA6NzQ")})}).then(HQ(()=>{NYf(this,a.brand,!0);const d=new __c.Hk({xa:a.brand});this.Cj.Gc(this.Zeb(b,c.wb),d);c.RT&&__c.Jg(this.$b,{Gl:L("dB9qNw"),fJ:{buttonText:L("4NNxgw"),onClick:HQ(()=>{this.Cj.Gc(this.Zeb(b,c.wb),{type:"VIEW_ALL_CREATORS",
wb:void 0});this.DB.push(__c.af("/following"))})},media:a.CVc})})).finally(HQ(()=>{a.state="idle"}))}async uHa(a){return(await this.Ql()).uHa(new __c.ifc({body:new __c.Tz({zha:this.brand,Aha:this.user,brand:a})})).then(b=>b.Kx)}bR(a,b,c){a.zA=!1;a.T6--;return this.PHa(a.brand).catch(()=>{bZf(()=>{a.zA=!0;a.T6++});__c.Jg(this.$b,{Gl:L("USSG5w")})}).then(HQ(()=>{NYf(this,a.brand,!1);const d=new __c.uXa({xa:a.brand});this.Cj.Gc(b,d);c.RT&&__c.Jg(this.$b,{Gl:L("ToX5WA"),fJ:{buttonText:L("8Xy8KA"),onClick:HQ(()=>
this.Kx(a,b,{RT:!1,wb:"TOAST_BUTTON"}))},media:a.CVc})})).finally(HQ(()=>{a.state="idle"}))}async PHa(a){return(await this.Ql()).PHa(new __c.jfc({body:new __c.Uz({zha:this.brand,Aha:this.user,brand:a})})).then(b=>b.Kx)}Zeb(a,b){return b!=null&&b==="TOAST_BUTTON"?{component:{Vn:this.B8e,wb:"TOAST_BUTTON"}}:a}constructor(a,b,c,d,e,f,g){this.brand=a;this.user=b;this.Cj=c;this.DB=d;this.Ql=e;this.$b=f;this.$k=g;this.B8e=(__c.oZf.F(this),__c.Db())}};__c.pZf=({v7c:a,onClick:b})=>{const c=a?L("dB9qNw"):L("sWvUuw");return GQ(__c.Ud,{size:"small",variant:a?"tertiary":"secondary",onClick:b,children:c})};__c.qZf=dZf(({alignment:a,width:b,display:c,kua:d,backgroundColor:e,hs:f,bY:g,SEa:h,content:k,lk:l,q8a:n},p)=>GQ("div",{ref:p,className:jZf("BcNgaw",e&&"cFcUXw"),style:{backgroundColor:e?__c.Fd(__c.Dd(e)):void 0},children:GQ(__c.Qy,{width:b,display:c,kua:d,hs:f,bY:g,Button:h,children:ZYf(__c.md,{spacing:"2u",children:[(l||n)&&ZYf("div",{className:"_7GH0qA",children:[l&&GQ("div",{className:jZf("KW1HYA",a),children:l}),n&&GQ("div",{className:"oVOTWQ",children:GQ(n,{})})]}),GQ("div",{className:jZf("Nitf6w",
a),children:k})]})})}));var RYf=({label:a,J5a:b,onEnter:c,Lca:d,onClick:e})=>GQ(__c.QKa,{label:a,state:b,x_d:!1,placement:"top",children:GQ("div",{onMouseEnter:c,onMouseLeave:d,onFocus:c,onBlur:d,children:GQ(__c.Le,{className:"_2S8w5g",onClick:e,children:GQ(__c.Nc,{children:a})})})}),SYf=({color:a,zUd:b})=>GQ("li",{className:"Gu5L1Q",style:{backgroundColor:a},children:b?GQ(b,{}):GQ(__c.Nc,{children:a})}),VYf=eZf(({R5d:a})=>GQ("ul",{className:"DM08FA",children:a.map((b,c)=>GQ(b,{},c))}));var OYf=class{static F(a){hb(a,{label:aZf.ref})}constructor(a,b){this.J5a=a;this.label=(OYf.F(this),void 0);this.label=b}},UYf=class{static F(a){hb(a,{SF:HQ,Nx:HQ})}SF(a,b,c){clearTimeout(a.ov);const d=a.J5a.open;a.label=b;a.J5a.open=!0;!d&&c&&c>0&&(a.ov=setTimeout(()=>{this.Nx(a)},c))}Nx(a){clearTimeout(a.ov);a.J5a.open=!1}constructor(){UYf.F(this)}};var rZf;
__c.sZf=eZf(({RRa:a,oba:b,muted:c=!0,isPaused:d=!1,volume:e})=>{const f=gZf(null);fZf(()=>{f.current&&e&&(f.current.volume=e)},[e]);fZf(()=>{f.current&&(d?f.current.pause():f.current.play())},[d]);const g=__c.Ny(a.o2a),h=c?__c.Ny(a.WA):__c.O7b(a.WA),k=h?`min(${"60vh"}, ${h.height}px)`:void 0;return GQ(rZf,{Ss:h.height,Ts:h.width,children:({EH:l,onLoadedMetadata:n})=>GQ(__c.Dj,{ref:(0,mZf["default"])(l,f),onLoadedMetadata:n,controls:!1,playsInline:!0,loop:!0,muted:c,preload:"auto",poster:g===null||
g===void 0?void 0:g.url,src:h===null||h===void 0?void 0:h.url,autoPlay:!0,className:jZf("bvVeIg",{IFdyBg:b}),style:b?void 0:{maxHeight:k}})})});
rZf=QYf(({Ss:a,Ts:b,children:c})=>{const d=gZf(null),e=lZf(()=>({loaded:!1})),f=HQ(()=>e.loaded=!0);fZf(()=>{const g=d.current;g&&g.readyState>=HTMLMediaElement.HAVE_METADATA&&g.videoHeight&&f()},[d,f]);return ZYf(YYf,{children:[!e.loaded&&GQ("div",{className:"P_JLiw",style:{width:`min(${"60vh"} * ${b} / ${a}, ${b}px)`,paddingTop:`calc(${a} / ${b} * 100%)`}}),GQ("div",{className:jZf("AIabWQ",{n2xpHw:!e.loaded}),children:c({EH:d,onLoadedMetadata:f})})]})});
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/b646393a2e4ffe64.js.map