(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[44135],{

/***/ 417979:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(382925);__web_req__(279380);__web_req__(823119);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var L=__c.L;var cz;var q$b,t$b,s$b,r$b,E$b,F$b,dz,fz;q$b=function(a,b,c,d){var e;a.CBa.set(b,{ref:b,g6:c,Yac:"static",position:{left:0,top:0},visible:!1,PZd:d});(e=a.observer)===null||e===void 0||e.observe(b);return()=>{var f;(f=a.observer)===null||f===void 0||f.unobserve(b);a.CBa.delete(b)}};__c.u$b=function(a,b="medium"){const c=(0,__c.sb)(r$b,s$b,t$b),d=__c.Sja(b);return(0,__c.xb)(()=>__c.Tja(a,d,c),[a,c,void 0,d])};
__c.bz=function({Lk:a,children:b}){const c=(0,__c.xb)(()=>({Lk:a}),[a]);return(0,__c.J)(__c.Dra.Provider,{value:c,children:b})};__c.v$b=function(a){const b=(0,__c.x8b)(()=>({render:a,OBc:(0,__c.i8b)(c=>b.render=c)}));(0,__c.q8b)(()=>{b.OBc(a)},[a,b]);return(0,__c.p8b)((0,__c.w8b)(c=>b.render(c))).current};__c.w$b=function(a){a=a.uv;return a.type==="STATIC_VIDEO_SOURCE"&&a.WA.some(b=>b.nN)};
__c.C$b=function({$I:a,xD:b,aJ:c,s$:d,Zs:e}){return{sEa:x$b(({card:f,XL:g,mR:h})=>{const k=__c.lc(),l=y$b(f.actions),n=!l.Cq||cz!==1&&k||!b?null:({className:z})=>dz(b,{model:l.Cq,render:({onClick:B,ma:C,label:E})=>dz(__c.Lj,{icon:C,onClick:B,ariaLabel:E,className:z$b("Nu4jkQ",z)})},"like-button"),p=l.copy?({className:z})=>dz(c,{action:l.copy,render:({onClick:B,ma:C,label:E})=>dz(__c.Kj,{visibility:__c.$b()?"always":"on-hover",location:"bottom-start",children:dz(__c.Lj,{size:k?"small":"medium",icon:C,
onClick:B,ariaLabel:E,className:z$b("Nu4jkQ",z)})})}):null,q=A$b(()=>({isOpen:!1,toggle:ez(()=>{q.isOpen=!q.isOpen;q.isOpen&&e&&e.uK()}),close:ez(()=>q.isOpen=!1)})),u=f.MA,w=f.unb,x=f.Ps;return dz(B$b,{children:()=>fz("div",{className:"phsQvg",children:[(w||u)&&dz(d,{unb:w,MA:u,resourceType:x===null||x===void 0?void 0:x.type}),p&&dz(p,{}),h&&dz(h,{}),fz(__c.Xy,{size:k?"small":"medium",visibility:__c.$b()?"always":"on-hover",location:"top-end",children:[cz!==2&&n&&dz(n,{}),cz===0&&l.lLb.length>0&&
dz(__c.$Na,{className:z$b("FaU_Wg",k&&"K4_fpQ"),ofa:__c.pe,Lxa:dz(a,{card:f,jga:q.close,XL:g}),isOpen:q.isOpen,ZQ:q.toggle})]})]})})})}};__c.gz=function({Ya:[a]}){var b;return(b=a&&__c.H7b(a))!==null&&b!==void 0?b:D$b};t$b=()=>1;s$b=()=>__c.DLa.get();r$b=a=>(0,__c.PEa)(__c.DLa,a);E$b=__webpack_require__(443763);F$b=E$b.Fragment;dz=E$b.jsx;fz=E$b.jsxs;var G$b=__webpack_require__,H$b=G$b(993864),z$b=G$b.n_x(H$b)();var I$b=__webpack_require__(214645),x$b=I$b.Pi,B$b=I$b.Qj,A$b=I$b.fv;var hz=__webpack_require__(875604),J$b=hz.Component,K$b=hz.forwardRef,L$b=hz.memo,M$b=hz.PureComponent,N$b=hz.useEffect,O$b=hz.useState;var P$b=__webpack_require__(519427),ez=P$b.action,Q$b=P$b.computed,R$b=P$b.observable,S$b=P$b.reaction,T$b=P$b.runInAction;var U$b=__webpack_require__(46239).__decorate;var V$b;a:switch(__c.Ue("64f2c514","A")){case "B":V$b=1;break a;case "C":V$b=2;break a;default:V$b=0}cz=__c.cz=V$b;var y$b=a=>a.reduce((b,c)=>{switch(c.type){case "LIKE":return b.Cq=c,b.lLb.push(c),b;case "COPY_ELEMENT":return b.copy=c,b.lLb.push(c),b;default:return b.lLb.push(c),b}},{Cq:void 0,copy:void 0,lLb:[]});var D$b={width:400,height:300};var W$b;
__c.X$b=L$b(K$b((a,b)=>{const c=a.Md,d=a.kb,e=a.overlay,f=a.wJ,g=a.title,h=a.subtitle,k=a.onMouseEnter,l=a.onMouseLeave,n=a.onMouseDown,p=a.onMouseUp,q=a.onFocus,u=a.onBlur,w=a.Woe;a=a.lta;const {isVisible:x,EQb:z}=__c.G8b(),[B,C]=O$b(!1);N$b(()=>{var I=window;I=W$b==null?W$b=!!I.navigator.vendor.match(/apple/i):W$b;return C(I)},[]);const E=cz!==2&&c,H=cz===0&&h;return fz("div",{className:"_6Jw7Rg",ref:b,children:[dz("div",{ref:z,className:"gogj2g",children:dz(__c.Ij,{wJ:fz(F$b,{children:[f,a&&dz(__c.Kj,
{location:"top-start",visibility:"always",children:dz(__c.S9b,{label:L("YhEcCA")})})]}),Dz:"none",Oa:fz("div",{className:"_6Jw7Rg",onMouseUp:p,onMouseDown:n,onMouseEnter:k,onMouseLeave:l,onFocus:q,onBlur:u,children:[dz(__c.Gj,{children:d&&dz("div",{className:"gogj2g",style:{transform:w&&B?"translateZ(0)":void 0},children:d})}),e&&x&&dz("div",{className:"_69kWDg",children:e})]}),layout:"vertical",Iw:"thumbnail"})}),E||g||H?fz("div",{className:"yeMjxA",children:[E&&dz("div",{className:"zvuW2Q",children:c}),
g||H?fz("div",{className:"p1dBAA",children:[g&&g,H&&h]}):null]}):null]})}));__c.Y$b=class extends M$b{render(){const {Xi:a,Scd:b,HVb:c,GVb:d,size:e="small"}=this.props;return fz("div",{className:z$b("KYnMHQ",{C2y5jA:e==="small",RhkwLw:e==="medium"}),children:[dz(__c.Ud,{variant:"tertiary",className:"YsEaLg",size:"xsmall",ariaLabel:a?L("5vUp+w"):L("cSn0vw"),icon:a?__c.Z9b:__c.f8b,Vf:"medium",DA:"start",onMouseDown:this.onMouseDown,onClick:c}),b!=null&&dz(__c.Ud,{variant:"tertiary",className:"YsEaLg",size:"xsmall",ariaLabel:b?L("BBsYIA"):L("96BnfQ"),icon:b?__c.c$b:__c.a$b,
Vf:"medium",DA:"start",onMouseDown:this.onMouseDown,onClick:d})]})}constructor(...a){super(...a);this.onMouseDown=b=>{b.preventDefault()}}};__c.iz=class extends J$b{static F(a){__c.hb(a,{DF:R$b.ref,yB:R$b.ref,isFocused:R$b.ref,xxd:ez.bound,Mw:ez.bound,Lca:ez.bound,mE:ez,$0:Q$b,MP:Q$b})}xxd(a){this.DF=a}componentDidMount(){this.lld();__c.lb(this,S$b(()=>({yB:this.yB,isFocused:this.isFocused}),a=>{a.yB||a.isFocused?this.dqd(this.yB?"hover":"focus"):this.oAd()}))}componentWillUnmount(){var a;(a=this.$Dd)===null||a===void 0||a.call(this)}componentDidUpdate(a){a.Sh===void 0&&this.props.Sh&&this.lld()}get $0(){const a=this.props.Sh;return this.DF&&
a?a.$0(this.DF):!1}get MP(){const a=this.props.Sh;return this.DF&&a?a.MP(this.DF):!1}render(){const a=this.props.children,b=this.props.Sh;return a({DF:this.xxd,$0:this.$0,MP:this.MP,mR:b&&this.mR,Jmb:b&&!__c.$b()?{Mw:this.Mw,Lca:this.Lca,onFocus:this.onFocus,onBlur:this.onBlur,mQ:this.mQ,yF:this.yF,mE:this.mE}:{yF:this.yF,mE:this.mE,mQ:this.mQ}})}constructor(...a){super(...a);this.DF=(__c.iz.F(this),null);this.isFocused=this.yB=!1;this.isLoaded=R$b.box(!1);this.s3b=[];this.lld=()=>{var b;if(__c.$b()){var c=
this.props.Sh;(b=this.$Dd)===null||b===void 0||b.call(this);this.$Dd=c===null||c===void 0?void 0:q$b(c,this.DF,this.props.g6,this.props.dqa)}};this.dqd=b=>{const c=this.props.Sh,d=this.props.A5,e=this.props.dqa;c&&this.DF&&(b&&d&&(b==="click"?this.s3b.push(()=>this.DF&&c.bDd(b,this.isLoaded,e,d)):c.bDd(b,this.isLoaded,e,d)),c.fzc(this.DF,{C4d:!0}))};this.oAd=b=>{const c=this.props.Sh,d=this.props.A5,e=this.props.dqa;c&&this.DF&&(b&&d&&c.A9e(this.DF,e,d),c.uK(this.DF))};this.HVb=()=>{this.onClick();
this.$0?this.oAd("click"):this.dqd("click")};this.GVb=()=>{this.onClick();const b=this.props.Sh,c=this.props.A5,d=this.props.dqa;b&&this.DF&&(this.MP?(c&&b.YCd("mute",this.DF,d,c),b.mute()):(c&&b.YCd("unmute",this.DF,d,c),b.nJc(this.DF,{F4d:!0})))};this.Mw=()=>{this.yB=!0};this.Lca=()=>{this.yB=!1};this.D0c=__c.wb(b=>{T$b(()=>this.isFocused=b)},50);this.onFocus=()=>{this.D0c(!0)};this.onBlur=()=>{this.D0c(!1)};this.onClick=()=>{if(this.yB)this.onBlur()};this.mQ=()=>{for(;this.s3b.length>0;){const b=
this.s3b.shift();b===null||b===void 0||b()}};this.yF=(b,c)=>{if(b.name==="NotAllowedError")if(this.MP){var d;(d=this.props.Sh)===null||d===void 0||d.mute();c===null||c===void 0||c()}else{var e,f;(e=this.props.Sh)===null||e===void 0||e.uK();(f=this.props.Sh)!==null&&f!==void 0&&(f.elc=!1)}};this.mE=()=>{this.isLoaded.set(!0)};this.mR=x$b(()=>dz(__c.Y$b,{Xi:!!this.$0,HVb:this.HVb,Scd:this.props.dqa?this.MP:void 0,GVb:this.GVb}))}};__c.iz=U$b([__c.qb],__c.iz);
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/c1cbffc9fdef1136.js.map