(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[70644],{

/***/ 437917:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var u5b,w5b,v5b,t5b;u5b=function(a,b){return t5b.toArray(Array.from(b,(c,d)=>{if(c instanceof Element){const f=u5b(a,c.childNodes),g=a.hpa.get(c.tagName.toUpperCase());if(g)try{return g(c,f,d)}catch(h){var e;(e=a.onError)===null||e===void 0||e.call(a,h)}return f}if(c instanceof Text)return c.textContent}))};__c.ry=function(a,b,c){a.hpa.set(b.toUpperCase(),c);return a};
w5b=async function(a){const b=Date.now(),c=await a.cache.keys();await Promise.all(c.map(async d=>{const e=await a.cache.match(d);e&&v5b(e,b)&&await a.cache.delete(d)}))};v5b=function(a,b){a=a.headers.get("X-Expire");return!!a&&b>=parseInt(a,10)};t5b=__webpack_require__(875604).Children;__c.sy=class{render(a){return u5b(this,this.LQe.parseFromString(a,"text/html").body.childNodes)}constructor(a){this.onError=a;this.hpa=new Map;this.LQe=new DOMParser}};__c.x5b=class{static async create(a){try{const b=await a.caches.open("blobs");return new __c.x5b(b,a)}catch(b){}}Q2a(a,b,c,d){d=d?Date.now()+d:void 0;const e=new this.window.Headers;c&&e.set("X-Name",encodeURI(c));d&&e.set("X-Expire",d.toString(10));return this.cache.put(`/${encodeURIComponent(a)}`,new this.window.Response(b,{headers:e}))}async getBlob(a){if((a=await this.cache.match(`/${encodeURIComponent(a)}`))&&!v5b(a,Date.now())){var b=a.headers.get("X-Name");b=b?decodeURI(b):void 0;return{blob:await a.blob(),
name:b}}}async b1c(a){await this.cache.delete(`/${encodeURIComponent(a)}`)}constructor(a,b){this.cache=a;this.window=b;this.window.requestIdleCallback?this.window.requestIdleCallback(()=>w5b(this)):setTimeout(()=>w5b(this),6E4)}};
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/c3e6c4a6536496fb.js.map