(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[8669],{

/***/ 190240:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(659506);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var hs;var zAb;__c.es=function(a){return a in yAb?yAb[a]:void 0};zAb=__webpack_require__(519427);__c.AAb=zAb.action;__c.BAb=zAb.autorun;__c.fs=zAb.computed;__c.gs=zAb.observable;__c.CAb=zAb.reaction;var DAb,EAb,FAb;DAb=__webpack_require__(443763);EAb=DAb.Fragment;hs=__c.hs=DAb.jsx;FAb=DAb.jsxs;var GAb=__webpack_require__(358579);var is,IAb,JAb,KAb,OAb;is=__webpack_require__(875604);__c.HAb=is.forwardRef;IAb=is.memo;JAb=is.useCallback;KAb=is.useId;__c.LAb=is.useLayoutEffect;__c.MAb=is.useMemo;__c.NAb=is.useRef;OAb=is.useState;__c.PAb=__webpack_require__(214645).Pi;var QAb;
__c.js=(a,b)=>{const c=(d,e)=>{const f=(0,__c.NAb)(null);(0,__c.LAb)(()=>{const g=[];for(const h of b){const k=d[h],l=(0,__c.CAb)(()=>k.get(),n=>{const p=f.current;if(p!=null)if(h==="children")p.textContent=n.toString();else{var q=QAb.get(h)||h;p.setAttribute(q,n.toString())}},{fireImmediately:!0});g.push(l)}return()=>{g.forEach(h=>h())}},[d]);e={...__c.go(d,(g,h)=>b.has(h)?void 0:g),ref:(0,GAb["default"])(f,e)};return hs(a,{...e})};c.displayName=`AnimatableElement(${typeof a==="string"?a:a.displayName||
a.name||"Component"})`;return IAb((0,__c.HAb)(c))};QAb=new Map([["strokeDasharray","stroke-dasharray"],["strokeWidth","stroke-width"],["fontSize","font-size"],["textAnchor","text-anchor"],["letterSpacing","letter-spacing"],["strokeOpacity","stroke-opacity"],["fillOpacity","fill-opacity"]]);var SAb;__c.RAb=__c.js("line",new Set(["x1","x2"]));SAb=__c.js("circle",new Set(["cx","aria-valuenow","aria-valuetext"]));
__c.TAb=(0,__c.HAb)((a,b)=>{const c=a.fill,d=a.strokeColor,e=a.strokeWidth,f=a.cx,g=a.cy,h=a.r,k=a.onKeyDown,l=a.value;a=a.JE;const [n,p]=OAb("none"),q=JAb(()=>{p("none")},[p]),u=JAb(z=>{z.stopPropagation();__c.Dc.bW&&p("auto")},[p]),w=JAb(()=>p("none"),[p]),x=KAb();return FAb(EAb,{children:[hs("defs",{children:hs("filter",{id:x,x:"0",y:"0",filterUnits:"userSpaceOnUse",children:hs("feDropShadow",{dx:"0",dy:"0",stdDeviation:e!==null&&e!==void 0?e:1.5,floodColor:d})})}),hs(SAb,{ref:b,tabIndex:0,fill:c,
cx:f,cy:g,r:h-(e!==null&&e!==void 0?e:1)*2,filter:`url(#${x})`,onKeyDown:k,onMouseDown:q,onFocus:u,onBlur:w,style:{outline:`${n} -webkit-focus-ring-color`},"aria-valuenow":l,"aria-valuetext":a})]})});
__c.UAb=(0,__c.HAb)((a,b)=>{const c=a.color;var d=a.R4;const e=a.strokeWidth,f=a.strokeColor,g=a.x1,h=a.y1,k=a.x2,l=d+(e!==null&&e!==void 0?e:0);d/=2;const n=l/2,p=g-n,q=h-n;return FAb("g",{children:[hs("line",{ref:b,stroke:"transparent",strokeLinecap:"round",strokeWidth:0,x1:g,y1:h,x2:k,y2:a.y2}),hs("rect",{fill:c,stroke:f!==null&&f!==void 0?f:"rgb(13, 18, 22)",strokeWidth:e!==null&&e!==void 0?e:0,width:k-g+d*2,height:l,rx:n,ry:n,x:p,y:q})]})});__c.VAb=new Set("ymdhs0".split(""));__c.WAb=new Set([",",".","'"," ","\u2019"]);__c.XAb=new Set([",","."]);__c.YAb=RegExp('^("[^"]*" *)?(?: *\\[\\$([^\\]-]{0,10})?(?:-([a-z]{2,3}(?:-[A-Z]{2}|-\\d{3})?))?\\] *)?([#0,.]+)(E\\+0)?(\\s?%)?(?: *\\[\\$([^\\]-]{0,10})?(?:-([a-z]{2,3}(?:-[A-Z]{2}|-\\d{3})?))?\\] *)?( *"[^"]*")?$');__c.ZAb={start:0,end:1,fw:0,group:(a,b)=>b.toString(),easing:__c.pf.X_c,eh:!1,z9a:!1};var yAb;yAb={thin:100,extralight:200,light:300,normal:400,medium:500,semibold:600,bold:700,ultrabold:800,heavy:900};__c.$Ab=Object.entries(yAb).reduce((a,[b,c])=>{__c.ja(!(c in a),"duplicate entry for weight {}",c);a[c]=b;return a},{});var aBb;__c.bBb=IAb((0,__c.HAb)(function({textAnchor:a="start",dominantBaseline:b="hanging",fill:c,fontWeight:d,...e},f){return hs("text",{ref:f,className:"tVQpqQ",textAnchor:a,dominantBaseline:b,fill:c,style:{"--Ll7Axw":c},textRendering:"geometricPrecision",onDragStart:aBb,fontWeight:d!=null?__c.es(d):void 0,...e})}));aBb=a=>a.preventDefault();
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/d15c6fe7db063129.js.map