(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[74283],{

/***/ 382925:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(671399);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var M7b,I7b,K7b,L7b,N7b,P7b,Q7b,R7b,Py,S7b;__c.G7b=function(a){return`${__c.xg(__c.vg(["lesson-templates",a]))}/`};
__c.H7b=function(a){let b;switch(a.type){case "SINGLE_IMAGE":b=a.Ob[0];break;case "CONTEXTUAL":case "CONTEXTUAL_VIDEO":b=a.ZK[0];break;case "VIDEO":a.uv.type==="STATIC_VIDEO_SOURCE"&&(b=a.uv.WA[0]);break;case "DESIGN":b=a;break;case "RESPONSIVE_IMAGE":var c;b=(c=a.c4[0])===null||c===void 0?void 0:c.Ob[0];break;case "GALLERY":b=void 0;break;case "DIAGONAL_OVERLAP":b=void 0;break;default:throw new __c.r(a);}return b&&{width:b.width,height:b.height}};
M7b=function({WQa:a,Irb:b,Jrb:c}){const d=c/14;b-=d*2;c-=d*2;a=I7b(a,b,c,a.length<4?.25:J7b);const {XIe:e,YIe:f}=K7b(b,c,a);return{qpe:L7b(a,e,f),v3d:e,w3d:f}};I7b=function(a,b,c,d){const e=b*c*d;return a.map(f=>{const g=Math.sqrt(e/(f.width/f.height));return{src:f.src,width:e/g,height:g}})};K7b=function(a,b,c){const d=c.reduce((e,f)=>e+f.width,0);c=c.reduce((e,f)=>e+f.height,0);d<b+.1*b&&(b=d-.1*b);c<a+.1*a&&(a=c-.1*a);return{XIe:a,YIe:b}};
L7b=function(a,b,c){const d=a.reduce((l,n)=>l+n.width,0),e=a.reduce((l,n)=>l+n.height,0),f=d-c,g=e-b,h=d-a[0].width,k=e-a[0].height;return a.map((l,n)=>n===0?{...l,xuc:0,yuc:0}:{...l,xuc:f/(h/l.width),yuc:g/(k/l.height)})};N7b=function(a){let b=0,c=0;return a.map(d=>{const e=b-d.xuc;b+=d.width-d.xuc;const f=c-d.yuc;c+=d.height-d.yuc;return{...d,x:e,y:f}})};__c.Ny=function(a,b=Infinity){if(a.length!==0){var c=a.filter(d=>d.width>=b);return c.length===0?__c.Od(a,d=>d.width):__c.Pd(c,d=>d.width)}};
__c.O7b=function(a,b=Infinity){if(a.length!==0&&(a=a.filter(c=>c.nN),a.length!==0))return __c.Ny(a,b)};P7b=function(a){switch(a){case "none":return"0";case "compact":return"1u";case "comfortable":return"2u";default:throw new __c.r(a);}};
__c.Oy=function(a,b="medium"){var c=Math.floor(a*10)/10;if((b==="short"||b==="shorter"||b==="detailed")&&c<60)return`${b==="shorter"?c:c.toFixed(1)}${__c.L("tojkXQ")}`;b=b==="detailed"?c:Math.floor(a);c=Math.floor(b/60);if(a=Math.floor(c/60))c%=60,c=c<10?`0${c}`:c;b=Math.round(b%60*10)/10;return`${a?a+":":""}${c}:${b<10?`0${b}`:b}`};Q7b=__webpack_require__(443763);R7b=Q7b.Fragment;Py=Q7b.jsx;S7b=Q7b.jsxs;var T7b=__webpack_require__(875604),U7b=T7b.forwardRef,V7b=T7b.useMemo,W7b=T7b.useState;var X7b=__webpack_require__(984956);var Y7b=__webpack_require__,Z7b=Y7b(993864),$7b=Y7b.n_x(Z7b)();__c.a8b=new Map([[1,{width:1,height:1}],[2,{width:4,height:3}],[3,{width:5,height:2}],[4,{width:16,height:9}],[5,{width:16,height:10}],[6,{width:20,height:13}]]);var J7b=1/6;var b8b,c8b;
b8b=({WQa:a,Eid:b=4,Irb:c,Jrb:d,rj:e="aspectRatio",backgroundColor:f="#F8F9F9"})=>{if(a.length===0)throw Error("Minimum 1 frame is required to create a overlap thumbnail");a=a.slice(0,b);e=e==="defaultOrder"?a:a.sort((l,n)=>n.width/n.height-l.width/l.height);const {qpe:g,v3d:h,w3d:k}=M7b({WQa:e,Irb:c,Jrb:d});e=N7b(g);return Py("div",{className:"ZyjxmA",style:{backgroundColor:f,height:c,width:d},children:Py("div",{className:"nugFQw",style:{height:h,width:k},children:e.slice().reverse().map(l=>Py("img",
{className:"HJ45dg",src:l.src,height:l.height,width:l.width,style:{bottom:l.y,left:l.x},alt:""},l.src))})})};
__c.d8b=a=>{const b=__c.wc({default:3,Fb:4}),[c,d]=W7b(void 0),[e,f]=W7b(void 0),[g,h]=W7b(!0),k=V7b(()=>__c.wb(n=>{n!==null&&n!==void 0&&n.bounds&&(d(n.bounds.width),f(n.bounds.height),h(!1))},100),[]),l=V7b(()=>n=>{h(!0);k(n)},[k]);return Py(X7b["default"],{bounds:!0,onResize:l,children:({measureRef:n})=>Py(c8b,{aspectRatio:a.aspectRatio,children:Py("div",{ref:n,style:{height:"100%",width:"100%",backgroundColor:a.backgroundColor||"#F8F9F9"},children:Py(__c.Ii,{expand:!0,loading:g,FYd:"fast",content:Py(b8b,
{Jrb:c||400,Irb:e||300,WQa:a.WQa,backgroundColor:a.backgroundColor,rj:a.rj,Eid:a.Eid||b}),placeholder:Py(__c.ce,{shape:"rectangle"})})})})})};c8b=({children:a,aspectRatio:b})=>b?Py(__c.Aj,{ratio:b,children:a}):a;__c.Qy=U7b(({hs:a,bY:b,kua:c="none",Button:d,display:e="compact",width:f,children:g},h)=>S7b("section",{ref:h,className:$7b("_sBzQQ",{hHCGKA:e==="compact",YTq_LA:f==="contained"}),children:[(()=>{if(a!=null&&b!=null){var k=Py("div",{className:"T7H5hQ",children:Py(a,{})}),l=Py(__c.oe,{size:P7b(c),direction:"vertical"}),n=Py("div",{className:"sLd6Fg",children:Py(b,{})});a:switch(c){case "none":var p="0";break a;case "compact":p="2u";break a;case "comfortable":p="4u";break a;default:throw new __c.r(c);
}return S7b(R7b,{children:[k,l,n,Py(__c.oe,{size:p,direction:"vertical"})]})}if(a!=null)return S7b(R7b,{children:[Py("div",{className:"T7H5hQ",children:Py(a,{})}),Py(__c.oe,{size:P7b(c),direction:"vertical"})]});if(b!=null)return S7b(R7b,{children:[Py("div",{className:"sLd6Fg",children:Py(b,{})}),Py(__c.oe,{size:P7b(c),direction:"vertical"})]})})(),Py("div",{className:"wQhSMw",children:g}),d&&Py("div",{className:"MXTkEQ",children:Py(d,{})})]}));var e8b='<svg width="16" height="16" fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="m5.674 2.159 7.803 4.93a1.053 1.053 0 0 1 0 1.822l-7.803 4.93a1.115 1.115 0 0 1-1.511-.35A1.049 1.049 0 0 1 4 12.93V3.068C4 2.48 4.492 2 5.098 2c.203 0 .403.055.576.159z" fill="currentColor"/></svg>';__c.f8b=__c.Ei({small:e8b,medium:__c.aLb});__c.g8b=U7b(function({className:a,borderRadius:b="none",...c},d){return Py(__c.od,{...c,ref:d,className:$7b(a,"P5tQlQ",{_0KfMcQ:b==="small",EAl2xw:b==="large",_3vWvTw:b==="defaultUnsetSmallUpSmall",_2nEN_g:b==="defaultSmallSmallUpLarge",zqG3PQ:b==="defaultSmallSmallUpNone"})})});
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/e1bb8b767706f3d5.js.map