(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[48690],{

/***/ 649153:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(443861);__web_req__(705468);__web_req__(437917);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var Ud=__c.Ud;var L=__c.L;var oe=__c.oe;var O=__c.O;var Ggf,Hgf,Igf,Jgf,Kgf,Lgf,Egf;
__c.Fgf=function(a,b){var c=a.options;switch(c.type){case "TEMPLATES":return new __c.xh({path:__c.Ywa(a.query,"templates"),target:__c.uh(b===null||b===void 0?void 0:b.target)});case "YOUR_DESIGNS":return new __c.xh({path:__c.Ywa(a.query,"designs"),target:__c.uh(b===null||b===void 0?void 0:b.target)});case "UNIVERSAL":c=a.query;if(a=a.Qa){var d=Egf.serialize;a=JSON.stringify(d(a));a=btoa(a).replace(/[+]/g,"-").replace(/[/]/g,"_").replace(/[=]/g,"")}else a=void 0;c=__c.xg(__c.wg(__c.wg(__c.vg(["search"]),
"q",c),"ui",a));return new __c.xh({path:c,target:__c.uh(b===null||b===void 0?void 0:b.target)});default:throw new __c.r(c);}};Ggf=__c.G(()=>[0,6,1,2,3,4,5]);Hgf=__c.F(()=>({type:__c.t("A?",1,"ALL")}));Igf=__c.F(()=>({type:__c.t("A?",2,"SHARED_WITH_YOU")}));Jgf=__c.F(()=>({type:__c.t("A?",3,"SPECIFIC_OWNER"),id:__c.P(1)}));Kgf=__c.Ia(()=>({type:[1,Hgf,2,Igf,3,Jgf]}),()=>({}));Lgf=__c.G(()=>[1,2,3,4,5,6]);Egf=__c.F(()=>({domain:__c.Ca(1,Ggf),vt:__c.y(2,Kgf),Ea:__c.Q(3),GMf:__c.Ca(4,Lgf),jBg:__c.gi(5)}));
__c.Xua.prototype.q3=__c.ea(37,async function(a){await this.Y3a.q3(a)});__c.Rua.prototype.q3=__c.ea(36,async function(a){const b=__c.m(this.store.search,"Search proto must exist to navigateToSearch"),c=__c.m(a.yAc?b.Nm.find(d=>d.type===a.yAc):this.store.G2b,`No SearchTab proto found for searchTabType: ${a.yAc}`);c.type==="PRIVATE_CONTENT"?this.Ze.q3({query:a.query,options:{type:"YOUR_DESIGNS"}},{target:"_self"}):__c.dte(this,{Bvd:b,Evd:c,params:__c.ete(this,a),u4:!1})});
__c.Jh.prototype.q3=__c.ea(35,async function(a,b){await this.Nj.rW(__c.Fgf(a,b))});var GL=__webpack_require__(875604),Mgf=GL.createContext,Ngf=GL.Fragment,Ogf=GL.memo,Pgf=GL.useCallback,Qgf=GL.useContext,Rgf=GL.useMemo;var Sgf=__webpack_require__(443763),HL=Sgf.Fragment,IL=Sgf.jsx,JL=Sgf.jsxs;var Tgf=__webpack_require__,Ugf=Tgf(993864),Vgf=Tgf.n_x(Ugf)();var Wgf=__webpack_require__(74252),Xgf=Wgf.Z5,Ygf=Wgf.LW;var Zgf=__webpack_require__(708666),$gf=Zgf.ZP,ahf=Zgf.hm;var bhf=__webpack_require__(214645).Pi;var chf=Mgf(null);var fhf=Ogf(a=>{const b=Qgf(chf),{variant:c="surface",isOver:d,icon:e=__c.HB,title:f,description:g,PJc:h="singleFile",aRc:k,disabled:l}={...b,...a};a=f!==null&&f!==void 0?f:dhf(h);return IL("div",{className:Vgf("SQN18w",{WXIb6w:c==="input",d_2dQg:c==="surface",IzY8Ww:d,g_nr_w:l}),"aria-hidden":!d||l,children:JL(__c.md,{spacing:"0",align:"center",children:[IL(e,{size:"large",tone:"primary"}),IL(O,{tone:"primary",size:"large",weight:"bold",tagName:"span",alignment:"center",children:a}),g!=null&&IL(O,
{tone:"secondary",size:"small",tagName:"span",alignment:"center",children:g}),k!=null&&JL(HL,{children:[IL(oe,{direction:"vertical",size:"3u"}),IL(ehf,{aRc:k,kie:h==="filesAndFolders"})]})]})})}),dhf=a=>{switch(a){case "singleFile":return L("UC2lUg");case "multipleFiles":return L("tMZBmQ");case "filesAndFolders":return L("mZBfcA");default:return L("UC2lUg")}},ghf=({category:a,icon:b,description:c})=>JL(__c.md,{spacing:"0",children:[JL(__c.Si,{align:"center",yg:"center",spacing:"0.5u",children:[b&&
IL(b,{size:"small",tone:"secondary"}),IL(O,{weight:"bold",tone:"secondary",children:a})]}),IL(O,{size:"small",tone:"secondary",alignment:"center",children:c})]}),ehf=({aRc:a,kie:b})=>JL(__c.md,{spacing:"2u",children:[a.file!=null&&IL(ghf,{category:L("qJdDrA"),icon:__c.pue,description:hhf(a.file)}),a.image!=null&&IL(ghf,{category:L("hMQrTQ"),icon:__c.zF,description:hhf(a.image)}),a.video!=null&&IL(ghf,{category:L("kZla1Q"),icon:__c.CF,description:hhf(a.video)}),a.audio!=null&&IL(ghf,{category:L("lcAHAA"),
icon:__c.woc,description:hhf(a.audio)}),b&&IL(ghf,{category:L("3GTUeA"),icon:__c.IB,description:L("gkzBmw")})]}),hhf=a=>a.map(b=>b.toUpperCase()).join(L("aJKXUQ")),ihf=a=>IL(fhf,{...a});var jhf=(a,b,c)=>{b||(a=a.slice(0,1));if(c&&c.length>0){const [d,e]=__c.fte(a,f=>{const g=f.name.split(".").pop();return!!((c===null||c===void 0?0:c.includes(f.type))||(c===null||c===void 0?0:c.includes(`.${g}`))||(c===null||c===void 0?0:c.some(h=>f.type.match(h))))});return{l2b:d,Ayc:e}}return{l2b:a,Ayc:[]}};__c.khf=({disabled:a,multiple:b,accept:c,m8:d,n8:e,children:f,gea:g=!0})=>{const h=Pgf(p=>{if(!a){var {l2b:q,Ayc:u}=jhf(p,b,c);q.length>0&&(d===null||d===void 0||d(q));u.length>0&&(e===null||e===void 0||e(u))}},[c,a,b,d,e]),[{isOver:k},l]=Ygf({accept:[ahf.FILE],collect:p=>({isOver:p.isOver()}),drop(p){(p=p.files)&&h(p)}}),n=Rgf(()=>({isOver:k,disabled:a,accept:c,m8:d,n8:e}),[c,a,k,d,e]);return IL("div",{className:"rJPECQ",ref:Pgf(p=>{l(p)},[l]),children:JL(chf.Provider,{value:n,children:[f,g&&IL(ihf,
{})]})})};__c.lhf=Xgf($gf)(Ngf);var mhf=new Map([["image/","image"],["video/","video"],["audio/","audio"],["application/","file"],["text/","file"]]),nhf=new Map([["image",new Set(".png .jpg .jpeg .gif .svg .heic .heif .apng .tiff".split(" "))],["video",new Set(".mp4 .mpeg .mpg .m4v .avi .mov .webm .wmv .mkv".split(" "))],["audio",new Set(".mp3 .wav .ogg .m4a .flac .wma .aac".split(" "))],["file",new Set(".pdf .ppt .pptx .doc .docx .xsl .xslx .csv .tsv .ai .psd .json".split(" "))]]),ohf=[{Ji:1,src:__webpack_require__.p+"images/b8aba3b3c47b98ab16ad428ec0bde1c8.png"},
{Ji:2,src:__webpack_require__.p+"images/e442f071ae0c58eca935c84f5b6e85be.png"}],phf=new Map([["image",[{Ji:1,src:__webpack_require__.p+"images/75ccdc1a3df2028e0c17058b89326cda.png"},{Ji:2,src:__webpack_require__.p+"images/8078e359e5621f13a83e5eefca290179.png"}]],["video",[{Ji:1,src:__webpack_require__.p+"images/27e0f818f52ec9da47437e75b0cfb0ec.png"},{Ji:2,src:__webpack_require__.p+"images/c7108516a50617327a032dbaf37e1198.png"}]],["audio",[{Ji:1,src:__webpack_require__.p+"images/38f39cda96be884ad08f3907bb76fad3.png"},
{Ji:2,src:__webpack_require__.p+"images/1884e99eb159e4266a717e340459aa76.png"}]],["file",[{Ji:1,src:__webpack_require__.p+"images/ef942780d5b72b24b6d2ca63f378c2ad.png"},{Ji:2,src:__webpack_require__.p+"images/7570828e1a8ee6e5fe9ec168c87b5807.png"}]],["multiple",ohf]]),qhf=a=>{a:{let c;if(a==null||a.length===0)a="multiple";else{for(const d of a){let e;for(const [f,g]of mhf.entries())if(d.startsWith(f)){e=g;break}if(e==null)for(const [f,g]of nhf.entries())if(g.has(d)){e=f;break}if(e==null||c!=null&&
e!==c){a="multiple";break a}c=e}a=c!==null&&c!==void 0?c:"multiple"}}var b;return(b=phf.get(a))!==null&&b!==void 0?b:ohf};var rhf=bhf(({mode:a="droparea",variant:b="compact",image:c="none",multiple:d,accept:e,disabled:f,error:g,Og:h,onClick:k,id:l,wc:n,Se:p,SCg:q})=>{const u=Pgf(w=>{f||(w.stopPropagation(),k())},[f,k]);h=IL(Ud,{variant:"secondary",icon:__c.HB,onClick:u,disabled:f,Og:h,id:l,wc:n,Se:p,stretch:q&&a==="button",children:d?L("896QMQ"):L("HyNk1A")});l=__c.Ic();if(a==="button")return h;a=c!=="none"?c:b==="display"?"filetype":"none";return IL("div",{className:Vgf("WW0FRA",{DbstuA:g,_8hYd1g:f,IdBJMw:!f&&l}),onClick:u,
children:JL(__c.md,{spacing:"1u",align:"center",children:[a!=="none"&&IL(__c.kd,{sources:a==="filetype"?qhf(e):a,alt:"",className:"qSjzXA",draggable:!1}),IL("span",{className:"vSa9PA",children:IL(O,{tone:__c.tf,size:"small",tagName:"span",alignment:"center",children:d?L("HV14og"):L("mZsLrg")})}),h]})})});var shf;__c.thf=a=>{const b=Qgf(chf),{disabled:c,accept:d,m8:e,n8:f,multiple:g,mode:h="droparea"}={...b,...a},k=IL(__c.GB,{hT:l=>{const {l2b:n,Ayc:p}=jhf(l,g,d);n.length>0&&(e===null||e===void 0||e(n));p.length>0&&(f===null||f===void 0||f(p))},mimeTypes:d,multiple:g,children:({onClick:l})=>IL(rhf,{...a,disabled:!!c,accept:d,multiple:g,onClick:l})});return b!=null||h==="button"?k:IL(shf,{disabled:c,accept:d,multiple:g,m8:e,n8:f,children:k})};
shf=Ogf(({children:a,...b})=>JL(__c.khf,{...b,gea:!1,children:[a,IL(fhf,{variant:"input"})]}));var uhf;
__c.vhf=({title:a,o$:b,wld:c,xnd:d,ZM:e,mimeTypes:f,multiple:g,C3:h,u7d:k={visible:!1},ief:l=!1,Kk:n})=>{const p=Pgf(z=>{c(z,"click");n===null||n===void 0||n()},[c,n]),q=Rgf(()=>({accept:[...f],multiple:g!==null&&g!==void 0?g:!1,m8:p,n8:d,hT:p}),[f,g,p,d]);var u=IL(O,{size:"medium",weight:"bold",children:a});u=h?IL(uhf,{onClick:h,children:u}):u;var w=IL(O,{size:"medium",weight:"bold",children:L("Py5fUg")});w=h&&!e?IL(uhf,{onClick:h,children:w}):w;const x=b&&JL(HL,{children:[w,IL(oe,{size:"1u",direction:"vertical"}),
IL(b,{Kyd:!1,tvd:"circular"})]});h=k.visible&&JL(__c.we,{spacing:"1u",children:[IL(__c.Oi,{children:IL(Ud,{variant:"secondary",stretch:!0,onClick:k.xn,children:L("on3JXg")})}),IL(__c.Oi,{children:IL(Ud,{variant:"primary",stretch:!0,onClick:k.onSubmit,children:L("XSljaQ")})})]});if(b&&e)return JL("div",{className:l?"_4ZOX7w":"gWJWzg",children:[a&&JL(HL,{children:[u,IL(oe,{size:"2u",direction:"vertical"})]}),IL(__c.thf,{...q,variant:"compact"}),IL(oe,{size:"2u",direction:"vertical"}),x,IL(oe,{size:"2u",
direction:"vertical"}),h]});if(e)return JL("div",{className:l?"_4ZOX7w":"gWJWzg",children:[a&&JL(HL,{children:[u,IL(oe,{size:"2u",direction:"vertical"})]}),IL(__c.thf,{...q,variant:"display"}),IL(oe,{size:"2u",direction:"vertical"}),h]});a=IL(HL,{children:IL(__c.GB,{...q,children:({onClick:z})=>IL(Ud,{variant:"secondary",icon:__c.HB,onClick:z,stretch:!0,children:L("646gqw")})})});k=k.visible&&!k.fke;return(b=b&&JL(HL,{children:[w,IL(oe,{size:"1u",direction:"vertical"}),IL(b,{Kyd:k,tvd:"circular"})]}))?
JL("div",{className:l?"_4ZOX7w":"gWJWzg",children:[b,IL(oe,{size:"2u",direction:"vertical"}),k?null:a,IL(oe,{size:"2u",direction:"vertical"}),h]}):JL("div",{className:l?"_4ZOX7w":"gWJWzg",children:[JL("div",{className:"vBTE1w",children:[IL(__c.kd,{className:"tBtWhg",sources:qhf([...f]),alt:""}),IL(oe,{size:"2u",direction:"vertical"}),IL(O,{weight:"bold",alignment:"center",children:L("WAUgIQ")})]}),a]})};
uhf=({children:a,onClick:b})=>JL("div",{className:"wzGWsA",children:[IL(Ud,{variant:"tertiary",onClick:b,icon:__c.pj,Vf:"medium",ariaLabel:L("rBQJNQ"),className:"_6txFnQ"}),IL(oe,{size:"1u",direction:"horizontal"}),a]});
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/e32a5329f5fafb20.js.map