(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[34795],{

/***/ 728027:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(813110);__web_req__(55182);self._5880d4398c473aa67256e87589eaef11 = self._5880d4398c473aa67256e87589eaef11 || {};(function(__c) {var K=__c.K;var L=__c.L;var nbf,pbf,rbf,sbf,tbf,ubf,vbf,xbf,ybf,GK,HK;__c.mbf=function(a){return`${__c.xg(__c.vg(["template-sets",a]))}/`};nbf=function({id:a,scrollMarginTop:b,label:c}){return(0,__c.J)("div",{id:a,tabIndex:-1,style:b?{paddingTop:b,marginTop:-b}:void 0,children:c&&__c.J(__c.Nc,{children:c})})};__c.obf=function(a){return btoa(JSON.stringify(__c.Ck.serialize(a)))};pbf=function({bounds:a,title:b,VGa:c}){return!a||a.height<103?null:a.width<200?c!==null&&c!==void 0?c:b:b};
__c.qbf=function(a){if(a)return a.ox?`${a.ox}__${a.id}`:a.id};rbf=function(a,b,c,d){const e=c+b*d;a=a.reduce((f,g,h)=>{f.push(g+f[h]);return f},[0]);if(d>0)return d=a.findIndex(f=>f>e)-1,Math.abs(a[d]-c)<=1&&(d+=1),a[d]||a[a.length-1];d=a.findIndex(f=>f>=e);Math.abs(a[d]-c)<=1&&--d;return a[d]||0};sbf=function(a,b,c,d,e){const f=Math.min(Math.max(d,0),a.length);d=a.slice(0,f).reduce((h,k)=>h+k,0);var g;a=(g=a[f])!==null&&g!==void 0?g:0;g=d+a>c+b;return d<c||g?e==="nearest"&&g?d-b+a:d:c};
tbf=function(a,b){const c=b&&(b.direction==="backward"?1:-1);b=c&&b.VGb*c;return{"--pgVeSg":b?`${b}px`:void 0,"--jSvNCQ":a?`${a}px`:void 0}};ubf=function(a,b){return(a=typeof a==="function"?a():a)&&GK("span",{className:b,children:a})};vbf=function({role:a,active:b,selected:c,pressed:d}){switch(a){case "switch":return{q2pazA:!1,njAsng:c!==null&&c!==void 0?c:b};case "button":case "combobox":return{q2pazA:d!==null&&d!==void 0?d:b,njAsng:c};default:throw new __c.r(a);}};
__c.wbf=()=>{var a=__c.jc().width;return a>=__c.CHa?4:a>=__c.BHa?3:a>=__c.AHa?2:a>=__c.kc?1:0};xbf=__webpack_require__(443763);ybf=xbf.Fragment;GK=xbf.jsx;HK=xbf.jsxs;var zbf=__webpack_require__,Abf=zbf(993864),IK=zbf.n_x(Abf)();var Bbf=__webpack_require__(214645).Pi;var JK=__webpack_require__(875604),Cbf=JK.Children,Dbf=JK.forwardRef,KK=JK.memo,LK=JK.useCallback,Ebf=JK.useEffect,Fbf=JK.useId,Gbf=JK.useImperativeHandle,Hbf=JK.useLayoutEffect,Ibf=JK.useMemo,MK=JK.useRef,Jbf=JK.useState;var Kbf=__webpack_require__(984956);var Lbf=__webpack_require__(519427),Mbf=Lbf.action,NK=Lbf.computed,OK=Lbf.observable,Nbf=Lbf.runInAction;var Obf=__webpack_require__(112581).polyfill;var Pbf=__webpack_require__(361443);__c.Qbf=__c.Vc({gs:__c.Ij,cG:__c.Ij});var Rbf;__c.Sbf=KK(({onClick:a,...b})=>GK(__c.Ij,{onClick:a,ariaLabel:b.title,oz:b.title,Oa:GK(Rbf,{...b}),layout:"vertical"}));__c.Tbf=KK(({gb:a,onClick:b,target:c,...d})=>GK(__c.Qbf,{gb:a,onClick:b,target:c,ariaLabel:d.title,oz:d.title,Oa:GK(Rbf,{...d}),layout:"vertical"}));
Rbf=Bbf(({title:a,VGa:b,dOc:c,ma:d=__c.CA})=>{const e=__c.$ma(),f=__c.ana(),g=__c.bna(),[h,k]=Jbf(a);return GK(Kbf["default"],{bounds:!0,onResize:({bounds:l})=>{l=pbf({bounds:l,title:a,VGa:b});h!==l&&k(l)},children:({measureRef:l})=>GK(__c.od,{ref:l,border:"low",borderRadius:"baseUnit",className:IK("ufrwPQ",{CwyHxw:(e||f)&&!g,Dw_fBw:g}),height:"full",width:"full",display:"flex",alignItems:"center",children:HK(__c.md,{spacing:"0.5u",align:"center",children:[c!=null?GK(c,{children:GK(d,{size:"medium",
tone:"primary"})}):GK(d,{size:"medium",tone:"primary"}),h&&GK(__c.O,{alignment:"center",children:h})]})})})});__c.Ubf=({Dse:a,groupId:b,options:c,Aze:d,Ukb:e})=>{const [f,g]=Jbf(d);d=LK(()=>{g(h=>!h);e===null||e===void 0||e({wm:f,groupId:b,zse:a})},[f,b,a,e]);return GK(__c.FMa,{label:a,role:"list",wm:f,wja:d,children:c})};__c.Vbf=({selected:a,onClick:b,label:c,ma:d})=>GK(__c.zf,{label:c,active:a,onClick:b,start:d&&GK(d,{})});__c.Wbf=({options:a,lm:b,c4a:c,N1e:d=!0,xld:e,Ukb:f,onSelect:g,ZMc:h,$Mc:k,dh:l,jI:n})=>{const p=LK((q,u,w)=>{if(q.EGa!==void 0){var x;w=((x=q.EGa)!==null&&x!==void 0?x:[]).map(z=>p(z,u,q.id));return GK(h,{dh:l,jI:n,groupId:q.id,Dse:q.label,options:w,Aze:c.includes(q.id),Ukb:f,index:u},q.key)}return GK(k,{label:q.label,dh:l,jI:n,lmb:w,Vx:q.id,selected:__c.qbf(b)===__c.qbf(q),index:u,onClick:()=>g(q)},__c.qbf(q))},[h,k,l,n,f,g,b,c]);return HK(__c.ve,{className:"tv9Ung",role:"list",variant:"rounded",
spacing:"0",children:[d&&GK(__c.Vbf,{selected:!b,onClick:e,label:L("OXELJw")}),a.map((q,u)=>p(q,u))]})};var Xbf,Ybf;__c.Zbf=class{static F(a){__c.hb(a,{c1:OK.ref,lm:OK.ref,clear:Mbf,options:NK,selectedOptions:NK,PT:NK,c4a:NK})}clear(){this.lm=void 0}get options(){return Xbf(this.c1)}get selectedOptions(){return this.lm?[this.lm]:[]}get PT(){var a;return((a=this.lm)===null||a===void 0?void 0:a.label)||""}get c4a(){return this.lm?Ybf(this.c1,this.lm):[]}constructor(a){this.type=(__c.Zbf.F(this),"category");this.c1=[...a.c1];this.lm=a.lm;this.id=a.id;this.title=a.title}};
__c.$bf=class{static F(a){__c.hb(a,{f9:Mbf})}f9(a,b){a.lm=b}clear(a){a.clear()}constructor(){__c.$bf.F(this)}};Xbf=a=>a.flatMap(b=>{var c;return b.EGa!=null?Xbf((c=b.EGa)!==null&&c!==void 0?c:[]):[b]});Ybf=(a,b,c)=>a.flatMap(d=>{if(d.EGa!=null){var e;const f=Ybf((e=d.EGa)!==null&&e!==void 0?e:[],b,d.id);return f.length>0?[c,...f].filter(__c.Ta):[]}return d.id===b.id&&c?[c]:[]});var acf=!1;acf||typeof document==="undefined"||typeof document.documentElement.style==="undefined"||(Obf(),acf=!0);var bcf,ccf;bcf=a=>a instanceof HTMLElement?a.offsetWidth:a.clientWidth;ccf=class{static F(a){__c.hb(a,{fh:OK.ref,f4b:OK.ref,g4b:OK.ref,r5d:OK.ref,zva:NK,yva:NK})}get zva(){return this.fh?this.g4b:this.f4b}get yva(){return this.fh?this.f4b:this.g4b}constructor(a){this.fh=(ccf.F(this),void 0);this.fh=a}};
__c.dcf=Dbf((a,b)=>{const c=a.children,d=a.innerRef,e=a.Q7,f=a.IDc,g=a.ffe,h=a.onScroll,k=__c.Sa()==="RTL",l=__c.Qa(),n=MK(new ccf(k)),p=MK({qo:null,bu:null}),q=LK(()=>f!=null?f?"smooth":void 0:l?"smooth":void 0,[f,l]),u=LK(()=>p.current.bu?e!==null&&e!==void 0?e:Array.from(p.current.bu.children,bcf):[],[e]),w=LK(()=>{Nbf(()=>{if(p.current.bu&&p.current.bu.offsetParent!=null){var I=(0,__c.Vh)(p.current.bu,__c.nf(n.current.fh));const N=p.current.bu.scrollWidth-p.current.bu.clientWidth-I;n.current.f4b=
I<=2;n.current.g4b=N<=2;const M=n.current.fh?N:I,T=u();I=T.map((V=>Y=>V+=Y)(0)).map((V,Y)=>Math.abs(V-T[Y]-M));const U=Math.min(...I);n.current.r5d=I.findIndex(V=>V===U)}})},[u]);a=LK(I=>{if(p.current.bu!==I){p.current.qo||(p.current.qo=new Pbf["default"](w));d&&(typeof d==="function"?d(I):d.current=I);p.current.bu&&(p.current.qo.unobserve(p.current.bu),p.current.bu.removeEventListener("scroll",w));p.current.bu=I;if(p.current.bu)p.current.qo.observe(p.current.bu),p.current.bu.addEventListener("scroll",
w);else{var N;(N=p.current.qo)===null||N===void 0||N.disconnect();p.current.qo=null}w()}},[d,w]);const x=LK((I,N)=>{var M,T;if(p.current.bu!=null){var U=(0,__c.Vh)(p.current.bu,__c.nf(n.current.fh)),V=p.current.bu.clientWidth,Y=u();if(n.current.fh){const Z=p.current.bu.scrollWidth;I=I(Y,V,Z-V-U);V=Z-V-I}else V=I(Y,V,U);(M=(T=p.current.bu).scrollTo)===null||M===void 0||M.call(T,{left:__c.Qpa(p.current.bu,V,n.current.fh),behavior:N?void 0:q()})}},[u,q]),z=LK((I,N="start",M)=>{x((T,U,V)=>sbf(T,U,V,I,
N),M)},[x]),B=LK(I=>I!==0&&x((N,M,T)=>rbf(N,M,T,I)),[x]),C=LK(()=>B(1),[B]),E=LK(()=>B(-1),[B]),H=Ibf(()=>{if(h)return f?__c.wb(()=>{h===null||h===void 0||h(n.current)},500):()=>h===null||h===void 0?void 0:h(n.current)},[h,f]);Ebf(()=>{Nbf(()=>n.current.fh=g?!1:k);w();const I=p.current.bu;if(H)return I===null||I===void 0||I.addEventListener("scroll",H),()=>{I===null||I===void 0||I.removeEventListener("scroll",H)}},[g,w,k,H]);Gbf(b,()=>({Zza:z,Tpc:C,Upc:E,Bsg:w}),[z,C,E,w]);return GK(ybf,{children:c({Kj:a,
Tpc:C,Upc:E,Tl:n.current,Zza:z})})});var ecf={colorBlackA07:"rgba(64, 87, 109, 0.07)",baseUnit:"8px",radiusElementRound:"9999px",colorBorder:"var(--Zya5eQ)",colorBorderActive:"var(--xAYPzA)",colorBorderHover:"var(--9_Lxmw)",colorSurface:"var(--4RaSjg)",colorSurfaceTransparent:"var(--389KIw)",colorTypographyPrimary:"var(--VNXpSw)",vSize:"40px",transitionDuration:"0.2s",horizontalOffset:"var(--pgVeSg, 0px)",verticalOffset:"var(--jSvNCQ, 0px)",fadeBleed:"-1px",iconOffset:"-7px",icon:"lslDOg",base:"o8cjRg",circular:"m1krnA",hoverSupported:"sz6d6w",
active:"oi8Wzw",forward:"OofttQ",backward:"_8lEyVA",chevron:"vDei3g"};var fcf=({className:a,active:b,direction:c,variant:d,Ogb:e})=>IK("o8cjRg",ecf[d],{oi8Wzw:b,sz6d6w:e,OofttQ:c==="forward",_8lEyVA:c==="backward"},a),gcf=a=>{var b;a===null||a===void 0||(b=a.current)===null||b===void 0||b.focus()},hcf=Bbf(a=>{const b=MK(!1);Hbf(()=>{b.current&&(a.Tl.zva&&(__c.Dc.qt?gcf(a.VNb):gcf(a.Hqb)),a.Tl.yva&&(__c.Dc.qt?gcf(a.VNb):gcf(a.Fdb)))},[a.Tl.zva,a.Tl.yva,a.VNb,a.direction,a.Ap,a.Hqb,a.Fdb]);const c=()=>{b.current=!0;a.onClick()},d=__c.Ic();return a.Tl.zva===!1&&a.direction===
"backward"||a.Tl.yva===!1&&a.direction==="forward"?GK("button",{onClick:c,className:fcf({active:a.active,variant:a.variant,direction:a.direction,Ogb:d}),"aria-controls":a.wvd,"aria-label":a.direction==="forward"?L("ApXdXg"):L("9sSB0g"),style:a.style,type:"button",ref:a.Ap,children:a.direction==="forward"?GK(__c.Li,{size:"medium",className:"lslDOg"}):GK(__c.pj,{size:"medium",className:"lslDOg"})}):null}),icf=a=>GK(hcf,{...a,variant:"circular",style:tbf(a.yKc,a.VGb?{VGb:a.VGb,direction:a.direction}:
void 0)}),jcf=a=>GK(hcf,{...a,variant:"chevron",style:tbf(a.yKc)});var ocf,mcf,lcf,kcf,ncf;
__c.PK=KK(({name:a,children:b,KT:c,onScroll:d,expand:e="none",wB:f="medium",jea:g="none",xBg:h="start",bG:k,Kj:l,IDc:n,u3e:p,gcb:q=!1,...u})=>{const w=MK(null),x=MK(null),z=MK(null),B=MK(null),C=kcf(f),E=IK("_80nAtQ Jv5dNg ndkgmg",{_4_bM8A:g==="mandatory",tHpxdA:g==="proximity"});a:{switch(f){case "none":break;case "small":f="vMIRQg _1kUSIQ";break a;case "medium":f="BN1Mrg _1kUSIQ";break a;case "large":f="dW7ZuQ _1kUSIQ";break a;default:throw new __c.r(f);}f=void 0}const H=IK(f,"D5BVoA LFBd9g",{U7dUcQ:h===
"initial"}),I=Ibf(()=>{if(k){var N=Array.isArray(k.Q7)?k.Q7.map(M=>M+C):Array(b.length).fill(k.Q7+C);N.length>0&&(N[N.length-1]-=C);return N}},[b.length,C,k]);return GK(__c.dcf,{innerRef:l,ref:c,Q7:I,IDc:n,onScroll:d,children:({Kj:N,Upc:M,Tpc:T,Tl:U})=>GK("div",{className:IK("jpmDSA",{_7aFgAw:e==="small",XUDH2A:e==="medium",u9Updg:e==="large"}),children:GK(lcf,{N3d:a,gcb:q,scrollMarginTop:p,Hqb:z,Fdb:B,children:GK(__c.Tc,{children:V=>HK(ybf,{children:[GK(mcf,{wvd:V,direction:"backward",onClick:M,
Tl:U,Ap:w,VNb:x,Hqb:z,Fdb:B,...u}),k?GK(ncf,{id:V,innerRef:N,bG:k,iBe:I,children:b,K3d:E,BLa:H,mGb:C,jea:g}):GK("div",{ref:N,id:V,className:E,children:Cbf.map(b.filter(Boolean),Y=>GK("div",{className:H,children:Y}))}),GK(mcf,{wvd:V,direction:"forward",onClick:T,Tl:U,Ap:x,VNb:w,Hqb:z,Fdb:B,...u})]})})})})})});ocf=KK(({width:a})=>GK("span",{className:"o0qdKw",style:{width:a}}));
mcf=KK(a=>{const b=a.Wk;switch(b){case "none":return null;case "chevron":return GK(jcf,{...a,yKc:a.kUa});case "circular":case void 0:return GK(icf,{...a,VGb:a.kna,yKc:a.kUa});case "custom":return GK(a.Puf,{...a});default:throw new __c.r(b);}});
lcf=KK(function({N3d:a,children:b,scrollMarginTop:c,gcb:d,Hqb:e,Fdb:f}){const g=Fbf(),h=Fbf();return d?b:HK(ybf,{children:[GK(nbf,{id:g,scrollMarginTop:c,label:a?K("LckcsA",[a]):L("maTNiA")}),GK(__c.fo,{to:h,position:"top",ref:e,children:a?K("70xSVA",[a]):L("m8gVcA")}),b,GK(__c.fo,{to:g,position:"bottom",ref:f,children:a?K("EtH2Sg",[a]):L("XiRPqg")}),GK(nbf,{id:h,scrollMarginTop:c,label:a?K("RK5cHQ",[a]):L("zBSOaw")})]})});
kcf=a=>{switch(a){case "none":return 0;case "small":return __c.qd;case "medium":return __c.qd*2;case "large":return __c.qd*3;default:throw new __c.r(a);}};
ncf=KK(({id:a,innerRef:b,bG:c,iBe:d,children:e,K3d:f,BLa:g,mGb:h,jea:k})=>GK(__c.zgc,{innerRef:b,layout:"horizontal",children:({Kj:l,Tl:n})=>GK("div",{ref:l,id:a,className:f,children:GK(__c.ik,{Tl:n,itemSizes:d,KW:c.KW,children:(p,q)=>{var u;const {AC:w,QC:x}=p!==null&&p!==void 0?p:{AC:0,QC:Math.min((u=c.J8f)!==null&&u!==void 0?u:1,q.length-1)};if(k!=="none")return Cbf.map(e,(z,B)=>{const C=Array.isArray(c.Q7)?c.Q7[B]:c.Q7;return GK("div",{className:g,children:w<=B&&B<x?z:GK(ocf,{width:C})})});p=
q[w];q=q[q.length-1]-q[x];q>0&&(q+=h);return HK(ybf,{children:[GK(ocf,{width:p}),Cbf.map(e.slice(w,x),z=>GK("div",{className:g,children:z})),GK(ocf,{width:q})]})}})})}));__c.QK=Dbf(({text:a,size:b="small",shape:c,active:d,selected:e,pressed:f,disabled:g,maxWidth:h="25u",nNa:k,onClick:l,start:n,end:p,id:q,role:u="button",pi:w=u==="combobox",ariaLabel:x,wc:z,Se:B,Og:C,ariaHasPopup:E,DD:H,ld:I,fC:N,Pn:M,N9:T},U)=>{const V=__c.Ic(),Y=IK("KpncAQ",{Mk7oNw:!k,_336cvg:b==="tiny",QNHArA:b==="small",ilYYXw:b==="medium",MFWj2A:c==="rectangle",Wdwfeg:I!=null,IUH4gg:g,yt9Bhw:h==="25u",_0E9Wig:V,...vbf({role:u,active:d,selected:e,pressed:f})}),Z=ubf(n,"p0GsKw");c=ubf(p,"lm_klw");
const W=GK(__c.O,{tagName:"span",className:"_SDvMQ",tone:__c.tf,size:b==="tiny"?"small":"medium",lineClamp:1,children:a});return k!=null&&I!=null?GK(__c.cj,{label:I,disabled:N,lineClamp:T,placement:M,children:({yea:ba,...ca})=>HK("span",{id:q,className:Y,"aria-label":x,"aria-labelledby":z,"aria-describedby":B,...ca,children:[Z,W,GK(__c.Ud,{ref:U,onClick:k,size:b==="medium"?"small":"tiny",variant:"tertiary",className:"aDxY_Q",icon:__c.hj,Vf:"small",ariaLabel:K("kZXcBA",[a]),disabled:g})]})}):k!=null?
HK("span",{id:q,className:Y,"aria-label":x,"aria-labelledby":z,"aria-describedby":B,children:[Z,W,GK(__c.Ud,{ref:U,onClick:k,size:b==="medium"?"small":"tiny",variant:"tertiary",className:"aDxY_Q",icon:__c.hj,Vf:"small",ariaLabel:K("kZXcBA",[a]),disabled:g})]}):HK(__c.Le,{ref:U,id:q,onClick:l,className:Y,OZ:!0,role:u==="button"?void 0:u,active:d,selected:e,pressed:f,disabled:g,pi:w,ariaLabel:x,wc:z,Se:B,Og:C,DD:H,ariaHasPopup:E,ld:I,fC:N,Pn:M,N9:T,children:[Z,W,c]})});__c.pcf=(a=>function(b){const c=MK(null),d=MK(!1);Ebf(()=>{if(c.current){var e=new a,f=__c.Pc(e,null,"0px");d.current=!1;e.observe(c.current,g=>{d.current?b===null||b===void 0||b(g):d.current=!0});return()=>{f()}}},[b]);return{qBd:c}})(__c.$f);
}).call(self, self._5880d4398c473aa67256e87589eaef11);}

}])
//# sourceMappingURL=sourcemaps/e448dfe9676d6e38.js.map