spring.application.name=SpringBoot-Hiber-App6
server.port=5600

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/25june25jeespring
spring.datasource.username=root
spring.datasource.password=mishthu99


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect