/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-08-22 10:24:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forgotPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <title>Change Password - Space App</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600&family=Inter:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body, html {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      font-family: 'Inter', sans-serif;\r\n");
      out.write("      background: black;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Scene Background */\r\n");
      out.write("    .scene {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Stars layers */\r\n");
      out.write("    .stars, .stars2, .stars3 {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      width: 200%;\r\n");
      out.write("      height: 200%;\r\n");
      out.write("      background: transparent url('https://www.transparenttextures.com/patterns/stardust.png') repeat;\r\n");
      out.write("      z-index: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stars { animation: moveStars 100s linear infinite; }\r\n");
      out.write("    .stars2 { animation: moveStars 200s linear infinite; opacity: 0.7; }\r\n");
      out.write("    .stars3 { animation: moveStars 300s linear infinite; opacity: 0.5; }\r\n");
      out.write("\r\n");
      out.write("    @keyframes moveStars {\r\n");
      out.write("      from { background-position: 0 0; }\r\n");
      out.write("      to { background-position: -10000px 5000px; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Shooting star */\r\n");
      out.write("    .shooting-star {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      width: 2px;\r\n");
      out.write("      height: 100px;\r\n");
      out.write("      background: linear-gradient(white, transparent);\r\n");
      out.write("      opacity: 0.8;\r\n");
      out.write("      transform: rotate(45deg);\r\n");
      out.write("      animation: shoot 6s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes shoot {\r\n");
      out.write("      0% { top: -200px; left: 100%; opacity: 0; }\r\n");
      out.write("      10% { opacity: 1; }\r\n");
      out.write("      50% { top: 50%; left: 50%; opacity: 1; }\r\n");
      out.write("      100% { top: 120%; left: -200px; opacity: 0; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Planet */\r\n");
      out.write("    .planet {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      bottom: -60px;\r\n");
      out.write("      right: 8%;\r\n");
      out.write("      width: 220px;\r\n");
      out.write("      height: 220px;\r\n");
      out.write("      background: radial-gradient(circle at 30% 30%, #7d5fff, #2d1b64);\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      z-index: 0;\r\n");
      out.write("      box-shadow: 0 0 60px rgba(125, 95, 255, 0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Form card */\r\n");
      out.write("    .card {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("      backdrop-filter: blur(14px);\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      padding: 40px 30px;\r\n");
      out.write("      width: 340px;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("      box-shadow: 0 0 25px rgba(255,255,255,0.2);\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card h1 {\r\n");
      out.write("      font-family: 'Orbitron', sans-serif;\r\n");
      out.write("      margin-bottom: 25px;\r\n");
      out.write("      font-size: 22px;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      letter-spacing: 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .field {\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .field input {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .field input::placeholder {\r\n");
      out.write("      color: #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      background: linear-gradient(45deg, #7d5fff, #00c6ff);\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: transform 0.2s ease, background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn:hover {\r\n");
      out.write("      transform: scale(1.05);\r\n");
      out.write("      background: linear-gradient(45deg, #00c6ff, #7d5fff);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p.message {\r\n");
      out.write("      margin-top: 18px;\r\n");
      out.write("      color: #ff4f4f;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back-link {\r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("      display: block;\r\n");
      out.write("      color: #00c6ff;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back-link:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"scene\">\r\n");
      out.write("    <div class=\"stars\"></div>\r\n");
      out.write("    <div class=\"stars2\"></div>\r\n");
      out.write("    <div class=\"stars3\"></div>\r\n");
      out.write("    <div class=\"shooting-star\"></div>\r\n");
      out.write("    <div class=\"planet\"></div>\r\n");
      out.write("\r\n");
      out.write("    <form class=\"card\" action=\"updatepasswords\" method=\"post\">\r\n");
      out.write("      <h1>Change Password</h1>\r\n");
      out.write(" 		\r\n");
      out.write(" 		<div class=\"field\">\r\n");
      out.write("        <input type=\"username\" name=\"username\" placeholder=\"username\" required />\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <input type=\"password\" name=\"newPassword\" placeholder=\"New Password\" required />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <input type=\"password\" name=\"confirmPassword\" placeholder=\"Confirm Password\" required />\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button class=\"btn\" type=\"submit\">Update Password</button>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("		<div class=\"back-link\">\r\n");
      out.write("			 <a href=\"backL\" >← Back to Home</a>\r\n");
      out.write("		</div>\r\n");
      out.write("     \r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
