/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-08-23 03:11:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <title>3D Space Login</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600&family=Inter:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    :root{\r\n");
      out.write("      --bg1:#090a1a;\r\n");
      out.write("      --bg2:#0b1a3a;\r\n");
      out.write("      --accent:#03e9f4;\r\n");
      out.write("      --accent-2:#8a5cf6;\r\n");
      out.write("      --text:#e7f3ff;\r\n");
      out.write("      --muted:#9fb3c8;\r\n");
      out.write("      --card-w: 360px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    *{box-sizing:border-box}\r\n");
      out.write("    html,body{height:100%}\r\n");
      out.write("    body{\r\n");
      out.write("      margin:0;\r\n");
      out.write("      font-family: Inter, Arial, sans-serif;\r\n");
      out.write("      color:var(--text);\r\n");
      out.write("      background: radial-gradient(1200px 800px at 70% 10%, #1b2a68 0%, transparent 60%),\r\n");
      out.write("                  radial-gradient(900px 700px at 20% 80%, #3a0a53 0%, transparent 55%),\r\n");
      out.write("                  linear-gradient(135deg, var(--bg1), var(--bg2));\r\n");
      out.write("      overflow:hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .scene{ position:relative;height:100%;display:grid;place-items:center;perspective:1000px; }\r\n");
      out.write("\r\n");
      out.write("    /* starfield layers */\r\n");
      out.write("    .stars,.stars2,.stars3{\r\n");
      out.write("      position:absolute; inset:0; pointer-events:none; z-index:-3;\r\n");
      out.write("      background-repeat:repeat;\r\n");
      out.write("      animation: drift 120s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("    .stars{background-image:radial-gradient(2px 2px at 20px 30px,#fff 50%,transparent 51%),\r\n");
      out.write("      radial-gradient(1.5px 1.5px at 130px 80px,#dff 50%,transparent 51%),\r\n");
      out.write("      radial-gradient(1.5px 1.5px at 300px 200px,#fff 50%,transparent 51%);}\r\n");
      out.write("    .stars2{z-index:-2;opacity:.6;filter:blur(.3px);animation-duration:180s;}\r\n");
      out.write("    .stars3{z-index:-1;opacity:.35;filter:blur(1px);animation-duration:240s;}\r\n");
      out.write("    @keyframes drift{to{background-position:-2000px 1000px;}}\r\n");
      out.write("\r\n");
      out.write("    /* shooting star */\r\n");
      out.write("    .shooting-star{position:absolute;top:10%;left:-10%;width:2px;height:2px;background:#fff;border-radius:50%;\r\n");
      out.write("      box-shadow:0 0 6px 2px #fff,0 0 18px 6px var(--accent);animation:shoot 5s ease-in-out infinite;}\r\n");
      out.write("    .shooting-star::after{content:\"\";position:absolute;right:2px;top:50%;height:2px;width:140px;\r\n");
      out.write("      transform:translateY(-50%);background:linear-gradient(90deg,#fff,transparent);}\r\n");
      out.write("    @keyframes shoot{0%{transform:translate(-10vw,-10vh) rotate(15deg)}20%{transform:translate(30vw,5vh) rotate(15deg)}21%{opacity:0}100%{opacity:0}}\r\n");
      out.write("\r\n");
      out.write("    /* planet */\r\n");
      out.write("    .planet{position:absolute;right:8vw;bottom:12vh;width:160px;height:160px;border-radius:50%;\r\n");
      out.write("      background:radial-gradient(120px 120px at 35% 35%,#7bdcff 0%,#1f6fb2 55%,#0a2550 100%);\r\n");
      out.write("      box-shadow:inset -10px -20px 40px rgba(0,0,0,.45),0 0 60px 10px rgba(138,92,246,.35);}\r\n");
      out.write("    .ring{position:absolute;inset:0;border-radius:50%;\r\n");
      out.write("      background:conic-gradient(from 0deg,rgba(3,233,244,.0),rgba(3,233,244,.7),rgba(138,92,246,.6),rgba(3,233,244,.0));\r\n");
      out.write("      transform:rotateX(70deg) scale(1.35);}\r\n");
      out.write("\r\n");
      out.write("    /* login card */\r\n");
      out.write("    .card{\r\n");
      out.write("      width:var(--card-w);\r\n");
      out.write("      padding:34px 28px;\r\n");
      out.write("      background:rgba(255,255,255,.08);\r\n");
      out.write("      border:1px solid rgba(255,255,255,.15);\r\n");
      out.write("      border-radius:20px;\r\n");
      out.write("      backdrop-filter:blur(12px);\r\n");
      out.write("      box-shadow:0 10px 35px rgba(0,0,0,.55);\r\n");
      out.write("      transform-style:preserve-3d;\r\n");
      out.write("      transition:.4s;\r\n");
      out.write("    }\r\n");
      out.write("    .card:hover{transform:rotateY(10deg) rotateX(5deg);}\r\n");
      out.write("    h1{font-family:Orbitron,sans-serif;text-align:center;margin-bottom:20px;}\r\n");
      out.write("\r\n");
      out.write("    .field{margin:18px 0;position:relative;}\r\n");
      out.write("    .field input,.field select{\r\n");
      out.write("      width:100%;padding:12px 14px;font-size:15px;color:var(--text);\r\n");
      out.write("      background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.25);\r\n");
      out.write("      border-radius:10px;outline:none;transition:.3s;}\r\n");
      out.write("    .field input:focus,.field select:focus{border-color:var(--accent);background:rgba(255,255,255,.12);}\r\n");
      out.write("\r\n");
      out.write("    .btn{\r\n");
      out.write("      width:100%;margin-top:16px;padding:12px 16px;\r\n");
      out.write("      background:linear-gradient(135deg,rgba(3,233,244,.6),rgba(138,92,246,.5));\r\n");
      out.write("      color:#fff;font-weight:600;border:0;border-radius:12px;\r\n");
      out.write("      cursor:pointer;transition:.2s;\r\n");
      out.write("    }\r\n");
      out.write("    .btn:hover{box-shadow:0 0 25px rgba(3,233,244,.6);}\r\n");
      out.write("    .meta{margin-top:14px;display:flex;justify-content:space-between;font-size:13px;color:var(--muted);}\r\n");
      out.write("    .meta a{color:#b7d8ff;text-decoration:none;}\r\n");
      out.write("    .meta a:hover{text-decoration:underline;}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"scene\" id=\"scene\">\r\n");
      out.write("    <div class=\"stars\"></div>\r\n");
      out.write("    <div class=\"stars2\"></div>\r\n");
      out.write("    <div class=\"stars3\"></div>\r\n");
      out.write("    <div class=\"shooting-star\"></div>\r\n");
      out.write("    <div class=\"planet\"><div class=\"ring\"></div></div>\r\n");
      out.write("\r\n");
      out.write("    <form class=\"card\" action=\"checkUser\" method=\"post\">\r\n");
      out.write("      <h1>Login</h1>\r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <select name=\"role\" required>\r\n");
      out.write("          <option value=\"USER\">User</option>\r\n");
      out.write("          <option value=\"ADMIN\">Admin</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <input id=\"username\" name=\"username\" type=\"text\" placeholder=\"Username\" required />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <input id=\"password\" name=\"password\" type=\"password\" placeholder=\"Password\" required />\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"btn\" type=\"submit\">Launch</button>\r\n");
      out.write("      <div class=\"meta\">\r\n");
      out.write("        <a href=\"forgotpassword\">Forgot password?</a>\r\n");
      out.write("        <a href=\"register\">Create account</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
