/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-08-23 06:23:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <title>Register - Space App</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600&family=Inter:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      font-family: \"Inter\", sans-serif;\r\n");
      out.write("      background: radial-gradient(circle at bottom, #000010, #000);\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .scene { position: relative; width: 100%; height: 100%; perspective: 1000px; }\r\n");
      out.write("    .stars, .stars2, .stars3 {\r\n");
      out.write("      position: absolute; width: 200%; height: 200%; background-repeat: repeat; background-size: contain;\r\n");
      out.write("      animation: moveStars 100s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("    .stars { background-image: url(\"https://www.transparenttextures.com/patterns/stardust.png\"); animation-duration: 200s; }\r\n");
      out.write("    .stars2 { background-image: url(\"https://www.transparenttextures.com/patterns/stardust.png\"); animation-duration: 150s; }\r\n");
      out.write("    .stars3 { background-image: url(\"https://www.transparenttextures.com/patterns/stardust.png\"); animation-duration: 100s; }\r\n");
      out.write("    @keyframes moveStars { from { transform: translateY(0); } to { transform: translateY(-1000px); } }\r\n");
      out.write("    .shooting-star { position: absolute; top: 20%; left: -10%; width: 150px; height: 2px; background: linear-gradient(90deg, white, transparent); animation: shoot 5s linear infinite; }\r\n");
      out.write("    @keyframes shoot { 0% { transform: translateX(0) translateY(0) rotate(45deg); opacity: 1; } 80% { opacity: 1; } 100% { transform: translateX(1200px) translateY(600px) rotate(45deg); opacity: 0; } }\r\n");
      out.write("    .planet { position: absolute; bottom: -50px; right: -100px; width: 200px; height: 200px; background: radial-gradient(circle, #4f46e5, #1e1b4b); border-radius: 50%; box-shadow: inset -20px -20px 40px rgba(0,0,0,0.6); }\r\n");
      out.write("    .planet .ring { position: absolute; top: 50%; left: 50%; width: 300px; height: 80px; border: 4px solid rgba(255,255,255,0.3); border-radius: 50%; transform: translate(-50%, -50%) rotateX(65deg); }\r\n");
      out.write("    .card { position: relative; background: rgba(255,255,255,0.05); padding: 2rem; border-radius: 20px; box-shadow: 0 8px 32px rgba(0,0,0,0.5); backdrop-filter: blur(10px); width: 350px; text-align: center; transform-style: preserve-3d; }\r\n");
      out.write("    .card h1 { font-family: \"Orbitron\", sans-serif; font-size: 1.5rem; margin-bottom: 1.5rem; color: #fff; }\r\n");
      out.write("    .field { position: relative; margin-bottom: 1.5rem; }\r\n");
      out.write("    .field input, .field select { width: 100%; padding: 0.8rem; border: none; outline: none; border-radius: 10px; background: rgba(255,255,255,0.1); color: white; font-size: 1rem; }\r\n");
      out.write("    .field label { position: absolute; left: 12px; top: 12px; color: rgba(255,255,255,0.7); pointer-events: none; transition: 0.3s ease; }\r\n");
      out.write("    .field input:focus + label, .field input:not(:placeholder-shown) + label { top: -10px; left: 8px; font-size: 0.8rem; color: #60a5fa; }\r\n");
      out.write("    .btn { background: linear-gradient(45deg, #3b82f6, #8b5cf6); border: none; padding: 0.8rem 1.5rem; border-radius: 12px; color: white; font-size: 1rem; cursor: pointer; transition: transform 0.2s ease; width: 100%; }\r\n");
      out.write("    .btn:hover { transform: scale(1.05); }\r\n");
      out.write("    .meta { margin-top: 1rem; font-size: 0.9rem; }\r\n");
      out.write("    .meta a { color: #93c5fd; text-decoration: none; }\r\n");
      out.write("    .meta a:hover { text-decoration: underline; }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("  <div class=\"scene\" id=\"scene\">\r\n");
      out.write("    <div class=\"stars\"></div>\r\n");
      out.write("    <div class=\"stars2\"></div>\r\n");
      out.write("    <div class=\"stars3\"></div>\r\n");
      out.write("    <div class=\"shooting-star\"></div>\r\n");
      out.write("    <div class=\"planet\"><div class=\"ring\"></div></div>\r\n");
      out.write("\r\n");
      out.write("    <form class=\"card\" action=\"saveUser\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("      <h1>Create Account</h1>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <input id=\"username\" name=\"username\" type=\"text\" required placeholder=\" \" />\r\n");
      out.write("        <label for=\"username\">Username</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <input id=\"password\" name=\"password\" type=\"password\" required placeholder=\" \" />\r\n");
      out.write("        <label for=\"password\">Password</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Role dropdown -->\r\n");
      out.write("      <div class=\"field\">\r\n");
      out.write("        <select name=\"role\" required>\r\n");
      out.write("          <option value=\"\" disabled selected>Select Role</option>\r\n");
      out.write("          <option value=\"USER\">User</option>\r\n");
      out.write("          <option value=\"ADMIN\">Admin</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button class=\"btn\" type=\"submit\">Register</button>\r\n");
      out.write("      <div class=\"meta\">\r\n");
      out.write("        <a href=\"login\">Already have an account? Login</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    // tilt effect for 3D\r\n");
      out.write("    const card = document.querySelector(\".card\");\r\n");
      out.write("    document.addEventListener(\"mousemove\", (e) => {\r\n");
      out.write("      let x = (window.innerWidth / 2 - e.pageX) / 25;\r\n");
      out.write("      let y = (window.innerHeight / 2 - e.pageY) / 25;\r\n");
      out.write("      card.style.transform = `rotateY(${x}deg) rotateX(${y}deg)`;\r\n");
      out.write("    });\r\n");
      out.write("    document.addEventListener(\"mouseleave\", () => {\r\n");
      out.write("      card.style.transform = \"rotateY(0deg) rotateX(0deg)\";\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("  </center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
