/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-08-22 08:51:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.univ.pojo.Course;
import java.util.List;

public final class searchcourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1755581585404L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1755581614976L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.univ.pojo.Course");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>Search Course</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/templatemo-style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Background video for space theme -->\r\n");
      out.write("  <video autoplay muted loop id=\"bg-video\">\r\n");
      out.write("    <source src=\"video/gfp-astro-timelapse.mp4\" type=\"video/mp4\">\r\n");
      out.write("  </video>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("<!-- header.html -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-xs-12\">\r\n");
      out.write("      <div class=\"cd-slider-nav\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg\" id=\"tm-nav\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">Astro Motion</a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("            data-bs-target=\"#navbar-supported-content\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("            aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbar-supported-content\">\r\n");
      out.write("            <ul class=\"navbar-nav mb-2 mb-lg-0\">\r\n");
      out.write("              <li class=\"nav-item selected\">\r\n");
      out.write("                <a class=\"nav-link\" aria-current=\"page\" href=\"#0\" data-no=\"1\">Home</a>\r\n");
      out.write("                <div class=\"circle\"></div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#0\" data-no=\"2\">Gallery</a>\r\n");
      out.write("                <div class=\"circle\"></div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#0\" data-no=\"3\">About</a>\r\n");
      out.write("                <div class=\"circle\"></div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#0\" data-no=\"4\">Contact</a>\r\n");
      out.write("                <div class=\"circle\"></div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"page-container\">\r\n");
      out.write("    <div class=\"container tm-content-container\">\r\n");
      out.write("      <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-6\">\r\n");
      out.write("          <div class=\"tm-bg-black-transparent p-5 rounded\">\r\n");
      out.write("            <h3 class=\"text-center\">Select Course Id To Search</h3>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"getCourse\" method=\"post\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"courseId\">Choose Course Id:</label>\r\n");
      out.write("                <select class=\"form-control\" id=\"courseId\" name=\"s1\">\r\n");
      out.write("                  ");

                    List<Course> lst = (List<Course>) request.getAttribute("allcourse");
                    if (lst != null) {
                      for (Course c : lst) {
                  
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(c.getId());
      out.write("\">\r\n");
      out.write("                          ");
      out.print(c.getId());
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(c.getCourseName());
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                  ");

                      }
                    }
                  
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <br>\r\n");
      out.write("              <input type=\"submit\" class=\"btn btn-primary btn-block\" value=\"Search Course\">\r\n");
      out.write("              <br>\r\n");
      out.write("              <a href=\"home\" class=\"btn btn-link\">â¬ Back To  Home</a>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("<!-- footer.html -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("  <footer class=\"row mx-auto tm-footer\">\r\n");
      out.write("    <div class=\"col-md-6 px-0\">\r\n");
      out.write("      Copyright 2021 Astro Motion Company Limited. All rights reserved.\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-6 px-0 tm-footer-right\">\r\n");
      out.write("      Designed by <a rel=\"sponsored\" href=\"https://templatemo.com\" target=\"_blank\" class=\"tm-link-white\">TemplateMo</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
