/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-06-23 08:58:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/sidebar.jsp", Long.valueOf(1749812576633L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1749812576607L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>BlogTube - Your Blogging Platform</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Header section start -->\r\n");
      out.write("   		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 <header>\r\n");
      out.write("        <div class=\"menu-toggle\">\r\n");
      out.write("            <i class=\"fas fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <i class=\"fas fa-blog\"></i>\r\n");
      out.write("            <h1>BlogTube</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"search-bar\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Search blogs...\">\r\n");
      out.write("            <button><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"user-actions\">\r\n");
      out.write("            <i class=\"fas fa-search mobile-search\"></i>\r\n");
      out.write("            <i class=\"fas fa-video\"></i>\r\n");
      out.write("            <i class=\"fas fa-bell\"></i>\r\n");
      out.write("            <div class=\"user-avatar\" onclick=\"window.location.href='profile.jsp'\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- Header section end -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <!-- sidebar section start -->\r\n");
      out.write("   		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<aside class=\"sidebar\">\r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <div class=\"sidebar-item active\">\r\n");
      out.write("                    <i class=\"fas fa-home\"></i>\r\n");
      out.write("                    <span>Home</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-fire\"></i>\r\n");
      out.write("                    <span>Trending</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-bookmark\"></i>\r\n");
      out.write("                    <span>Subscriptions</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-folder\"></i>\r\n");
      out.write("                    <span>Library</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-history\"></i>\r\n");
      out.write("                    <span>History</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                    <span>Watch later</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-thumbs-up\"></i>\r\n");
      out.write("                    <span>Liked posts</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <h3>CATEGORIES</h3>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-utensils\"></i>\r\n");
      out.write("                    <span>Food</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-plane\"></i>\r\n");
      out.write("                    <span>Travel</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-dumbbell\"></i>\r\n");
      out.write("                    <span>Fitness</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-gamepad\"></i>\r\n");
      out.write("                    <span>Gaming</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-music\"></i>\r\n");
      out.write("                    <span>Music</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"sidebar-section\">\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-cog\"></i>\r\n");
      out.write("                    <span>Settings</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class=\"fas fa-flag\"></i>\r\n");
      out.write("                    <span>Report</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-item\">\r\n");
      out.write("                    <i class='fa fa-sign-out'style=\"color:#9147ff\"></i>\r\n");
      out.write("                    <span><a href=\"login.jsp\">Log-out</a></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("        </aside>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- sidebar section end -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <main class=\"main-content\">\r\n");
      out.write("            <div class=\"content-header\">\r\n");
      out.write("                <h2>Recommended Blogs</h2>\r\n");
      out.write("                <div class=\"filter-buttons\">\r\n");
      out.write("                    <button class=\"filter-btn active\">All</button>\r\n");
      out.write("                    <button class=\"filter-btn\">Today</button>\r\n");
      out.write("                    <button class=\"filter-btn\">This week</button>\r\n");
      out.write("                    <button class=\"filter-btn\">This month</button>\r\n");
      out.write("                    <button class=\"filter-btn\">Most viewed</button>\r\n");
      out.write("                    <button class=\"filter-btn\">Top rated</button>\r\n");
      out.write("                    <button class=\"filter-btn\">Newest</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"posts-grid\">\r\n");
      out.write("                <!-- Blog Post 1 -->\r\n");
      out.write("                <div class=\"post-card\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1506744038136-46273834b3fb\" alt=\"Mountain landscape\">\r\n");
      out.write("                        <span class=\"duration\">5 min read</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"post-details\">\r\n");
      out.write("                        <h3 class=\"post-title\">10 Tips for Better Photography in 2023</h3>\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <div class=\"author-avatar\"></div>\r\n");
      out.write("                            <div class=\"post-info\">\r\n");
      out.write("                                <div class=\"author-name\">Photo Pro</div>\r\n");
      out.write("                                <div class=\"post-stats\">15K views • 3 days ago</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-ellipsis-v more-options\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Blog Post 2 -->\r\n");
      out.write("                <div class=\"post-card\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1546069901-ba9599a7e63c\" alt=\"Healthy food\">\r\n");
      out.write("                        <span class=\"duration\">8 min read</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"post-details\">\r\n");
      out.write("                        <h3 class=\"post-title\">The Ultimate Guide to Vegan Cooking for Beginners</h3>\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <div class=\"author-avatar\"></div>\r\n");
      out.write("                            <div class=\"post-info\">\r\n");
      out.write("                                <div class=\"author-name\">Vegan Kitchen</div>\r\n");
      out.write("                                <div class=\"post-stats\">42K views • 1 week ago</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-ellipsis-v more-options\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Blog Post 3 -->\r\n");
      out.write("                <div class=\"post-card\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1506929562872-bb421503ef21\" alt=\"Travel destination\">\r\n");
      out.write("                        <span class=\"duration\">12 min read</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"post-details\">\r\n");
      out.write("                        <h3 class=\"post-title\">How I Traveled to 15 Countries in One Year With a Full-Time Job</h3>\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <div class=\"author-avatar\"></div>\r\n");
      out.write("                            <div class=\"post-info\">\r\n");
      out.write("                                <div class=\"author-name\">Travel Enthusiast</div>\r\n");
      out.write("                                <div class=\"post-stats\">105K views • 2 weeks ago</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-ellipsis-v more-options\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Blog Post 4 -->\r\n");
      out.write("                <div class=\"post-card\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1555774698-0b77e0d5fac6\" alt=\"Coding on laptop\">\r\n");
      out.write("                        <span class=\"duration\">6 min read</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"post-details\">\r\n");
      out.write("                        <h3 class=\"post-title\">Building Your First Mobile App: A Step-by-Step Guide</h3>\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <div class=\"author-avatar\"></div>\r\n");
      out.write("                            <div class=\"post-info\">\r\n");
      out.write("                                <div class=\"author-name\">Code Master</div>\r\n");
      out.write("                                <div class=\"post-stats\">28K views • 5 days ago</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-ellipsis-v more-options\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Blog Post 5 -->\r\n");
      out.write("                <div class=\"post-card\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1513519245088-0e12902e5a38\" alt=\"Minimalist workspace\">\r\n");
      out.write("                        <span class=\"duration\">10 min read</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"post-details\">\r\n");
      out.write("                        <h3 class=\"post-title\">Minimalist Living: How to Declutter Your Life and Find Happiness</h3>\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <div class=\"author-avatar\"></div>\r\n");
      out.write("                            <div class=\"post-info\">\r\n");
      out.write("                                <div class=\"author-name\">Simple Life</div>\r\n");
      out.write("                                <div class=\"post-stats\">76K views • 3 weeks ago</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-ellipsis-v more-options\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Blog Post 6 -->\r\n");
      out.write("                <div class=\"post-card\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"https://images.unsplash.com/photo-1454165804606-c3d57bc86b40\" alt=\"Productive workspace\">\r\n");
      out.write("                        <span class=\"duration\">7 min read</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"post-details\">\r\n");
      out.write("                        <h3 class=\"post-title\">The Science Behind Productivity: How to Get More Done in Less Time</h3>\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <div class=\"author-avatar\"></div>\r\n");
      out.write("                            <div class=\"post-info\">\r\n");
      out.write("                                <div class=\"author-name\">Productivity Guru</div>\r\n");
      out.write("                                <div class=\"post-stats\">53K views • 4 days ago</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"fas fa-ellipsis-v more-options\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"create-new\">\r\n");
      out.write("        <i class=\"fas fa-plus\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Toggle sidebar on mobile\r\n");
      out.write("        document.querySelector('.menu-toggle').addEventListener('click', function() {\r\n");
      out.write("            document.querySelector('.sidebar').classList.toggle('active');\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // Close sidebar when clicking outside on mobile\r\n");
      out.write("        document.addEventListener('click', function(event) {\r\n");
      out.write("            const sidebar = document.querySelector('.sidebar');\r\n");
      out.write("            const menuToggle = document.querySelector('.menu-toggle');\r\n");
      out.write("            \r\n");
      out.write("            if (window.innerWidth <= 768 && \r\n");
      out.write("                !sidebar.contains(event.target) && \r\n");
      out.write("                !menuToggle.contains(event.target) &&\r\n");
      out.write("                sidebar.classList.contains('active')) {\r\n");
      out.write("                sidebar.classList.remove('active');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // Make filter buttons scrollable\r\n");
      out.write("        const filterButtons = document.querySelector('.filter-buttons');\r\n");
      out.write("        let isDown = false;\r\n");
      out.write("        let startX;\r\n");
      out.write("        let scrollLeft;\r\n");
      out.write("        \r\n");
      out.write("        filterButtons.addEventListener('mousedown', (e) => {\r\n");
      out.write("            isDown = true;\r\n");
      out.write("            startX = e.pageX - filterButtons.offsetLeft;\r\n");
      out.write("            scrollLeft = filterButtons.scrollLeft;\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        filterButtons.addEventListener('mouseleave', () => {\r\n");
      out.write("            isDown = false;\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        filterButtons.addEventListener('mouseup', () => {\r\n");
      out.write("            isDown = false;\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        filterButtons.addEventListener('mousemove', (e) => {\r\n");
      out.write("            if(!isDown) return;\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const x = e.pageX - filterButtons.offsetLeft;\r\n");
      out.write("            const walk = (x - startX) * 2;\r\n");
      out.write("            filterButtons.scrollLeft = scrollLeft - walk;\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // Active filter button\r\n");
      out.write("        document.querySelectorAll('.filter-btn').forEach(btn => {\r\n");
      out.write("            btn.addEventListener('click', function() {\r\n");
      out.write("                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));\r\n");
      out.write("                this.classList.add('active');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
